### ISSUE TITLE
possible to make "similar notes" more salient (via shared attributes)?

### ISSUE THREAD

**Issue by lerone-b** [zadam/trilium#1001]
hello zadam + community,

**prelude:** I am continuing to wonder about different **ways to create info-density and meaningful note retrievability and 'findability'** (does this word exist?) of notes. this is of course with a view on Trilium as _main_ and _large scale_ personal knowedge repo. 
– so I am thinking around a base scenario where _not losing sight of existing notes in relavant (use-)contexts_ and contextual sensibility is central / key... [see also #980]

**issue / proposal:** would it be possible / feasible to **load notes into the 'similar notes' pane which share (a certain number of?) attributes with the existing note?** certainly would a) 'make sense' and make true on the meaning/function of 'similar notes' and b) leverage the semantic importance of – already existing! – attributes _as helpful metadata_...

**Comment by zadam** [comment]
Yes, I have been thinking exactly about this - I want to focus on "similar notes" more in the future since it is IMHO very important to be able to automatically find related notes in large knowledge bases.

Actually what I mentioned in the other thread is kind of a prerequisite - part of the search overhaul will be about keeping attributes in memory which will allow fast universal search and also allow to quickly find related notes.

However I think this will come after 0.43 ...

**Comment by jaroet** [comment]
For me the other way around would be great.

Keep the current attribute functions (they work fine) but adding them to
the notes is a lot of work. I do not know if anybody used to work with
Evernote version 2.2? There you could add like definition rows (plural) and
when you edited a note those definition rows were executed. Those
definition rows could have different functions (like search based, data
based or tasklist based) and would allow you to dynamically add attributes
to a note (or tags in Evernote).

What does that mean? For example I can add a definition row where I want to
look at the note creation date, extract the year and add it as a attribute
to the note. Like year=2020. Or you add two yearCreated and yearLastEdited.
Or use a search based definition row where I search for example '@
microsoft.com' and all notes where that value is found the tag
company=microsoft is added. Together with a similar attributes function =
instant linked of networked notes.

In Evernote all notes where scanned when you added a new definition row and
when you edited a note all existing definition rows where executed for that
note. Processing was an issue and probably the reason they abandoned this
functionality but something like that would be assume.

It is a little hard to explain in text only, but that functionality made
the use of tags usable in Evernote 2.2. Because when you have 1000's of
notes then correctly managing tags (evernote) or attributes (Trilium) is a
pain. It was truly a shame to see that functionality go.

Op wo 6 mei 2020 om 11:42 schreef zadam <notifications@github.com>:

**Comment by zadam** [comment]
> What does that mean? For example I can add a definition row where I want to look at the note creation date, extract the year and add it as a attribute to the note. Like year=2020. Or you add two yearCreated and yearLastEdited. Or use a search based definition row where I search for example '@ microsoft.com' and all notes where that value is found the tag company=microsoft is added.

But that seems like it could be done with existing search:

```
@dateCreated=*2020
```

Will find all the notes created in 2020. This will not create the tag like in Evernote, but usually you would create such tag for searching purposes ...

**Comment by lerone-b** [comment]
> when you have 1000's of notes then correctly managing tags (evernote) or attributes (Trilium) is a pain

– yes, agreed! the question of _managable_ tags (more generally metadata) is core.

this is why I floated another possible take: focusing on possible mechanisms of automatically 'handing over' the tags (or more generally: all possible attributes) to the tree hierarchy (see #989). 

given the flexibility and centrality of the tree in Trilium (not least bec of _clones_), one could have a versatile 'mirror structure' which could allow all kinds of controlled and visible representation / management of the personalized tag (attribute) system.  (and: given the possibility to duplicate and clone plus the multiplicity of attribute taxonomies Trilium allows, such a linkage would allow different (flexible, adaptable) metadata systems, far beyond what Evernote & co can offer. 
– different take on _same_ question.

...  maybe it´s good to map / float _different ways and experiences_ with metadata systems so Zadam can see / decide what fits Triliums architecture / pathway ... and also what is reasonably codable...
– plus we ourselves learn and adapt in the course.

**Comment by jaroet** [comment]
But that seems like it could be done with existing search:

@dateCreated=*2020

Will find all the notes created in 2020. This will not create the tag like
in Evernote, but usually you would create such tag for searching purposes
...
I stand corrected, this is indeed already possible with the current search
options. Thanks for pointing that out.

Op wo 6 mei 2020 om 16:22 schreef zadam <notifications@github.com>:

**Comment by zadam** [comment]
Similar notes consider attributes as well in v0.44 so closing ..
