### ISSUE TITLE
Allow search results for protected notes in protected session. 

### ISSUE THREAD

**Issue by jaroet** [zadam/trilium#1003]
Using Trilium Notes 0.41.6 on a Mac. 

I truly like the protect subtree function to protect notes. In combination with the 10 minutes protected session timeout this is keeping notes private. 

One of the side-effects of this is that the note is not found when searching for it (even when you are in a protected session, you supplied the protection password). The jump-to-note function is working correctly (can find the note) when in a protected session and it can not find the note when not in a protected session. 
Would it be possible to have the same logic apply to the search functionality?

So no result when not in a protected session and the correct result when in a protected session?

An alternative (if possible) would be to allow not only to protect whole notes but also parts of a note. I for instance log username/password in certain notes together with some text about that site. If I can just protect the part of the note with the username/password part that would allow me to find that note when using the search or jump-to-note function (when not in protected session). 

Regards,
JeRoen

**Comment by zadam** [comment]
This will be partially fixed/mitigated by the upcoming search overhaul - whatever is findable by "Jump to note" will be also findable by standard search. This is possible by the fact that after entering protected session, all note titles are decrypted and kept in memory.

However this solution can't be used for note content since that would limit the scalability - we can't keep all the note contents decrypted in memory for searching as that might be too much.

So the goal is that searching for protected notes will be the same as for not protected, with the sole exception of full text search in the protected note's content.

**Comment by zadam** [comment]
> An alternative (if possible) would be to allow not only to protect whole notes but also parts of a note. I for instance log username/password in certain notes together with some text about that site.

This is rather difficult to do. But there's an easy workaround, create a subnote just for the secret data, protect that and link to it from the parent note.

**Comment by jaroet** [comment]
Hello,

Thanks for the explanation of all things to consider. As enduser
(non-developer) some things look easy while they might not be easy.
The subnotes method is what I use now. It works but feels a bit awkward.
But I will get used to it :-).

Op wo 6 mei 2020 om 17:29 schreef zadam <notifications@github.com>:

**Comment by zadam** [comment]
Searching in protected notes when in protected session is available since v0.44.
