### ISSUE TITLE
Unable to restore deleted notes

### ISSUE THREAD

**Issue by mursilsayed** [zadam/trilium#1014]
I am using version trilium desktop version 0.41.6 on Kubuntu 20.0.4. 
When I am deleting notes, they don't appear in the recent changes and therefore there is no way for me to restore notes in case I decide to change my mind later. 

[trilium-2020-05-12.log](https://github.com/zadam/trilium/files/4616044/trilium-2020-05-12.log)

**Comment by zadam** [comment]
Hi, please try 0.42.1, I think this was a (display) bug fixed recently.

**Comment by meichthys** [comment]
@zadam Wow! you've been busy since the last time I updated my Trilium version! Lots of great fixes & improvements! 🚀

@mursilsayed 
v0.42.1 and newer fixed this issue for me. There is now an 'undelete' option in the recent changes dialog:

<img width="278" alt="image" src="https://user-images.githubusercontent.com/10717998/86083683-f485dc80-ba68-11ea-9926-9c034924a13c.png">

**Comment by meichthys** [comment]
@zadam I think we can close this issue.
