### ISSUE TITLE
Recent changes not in chronological order (caused by web clipper saving to server)

### ISSUE THREAD

**Issue by FliegendeWurst** [zadam/trilium#1055]
Trilium version (server): 0.42.3

Steps to reproduce:

1. Install the web clipper extension (v0.1.1) and configure a sync server connection
2. Close desktop Trilium instance (if open)
3. Create a new (text) note in the extension popup

Result:

The creation and modification timestamp of the new note are the current UTC date and time.  
The list of recent changes ignores timezone data, which results in wrong ordering of changes (if the user's timezone is not UTC).

Log file: probably not needed? (only `POST /api/clipper/notes` and `Creating clipped note from undefined` appear to be related)

**Comment by zadam** [comment]
Hi, thanks for reporting. This is caused by the fact that the server runs in UTC and it does not get information about which timezone the user's browser is in. I fixed this in zadam/trilium-web-clipper@7a42d7e but also need to build a release.

Workaround is to have desktop Trilium running - when the web clipper detects locally running Trilium instance then it will create the clip note using that one and that will record the timezone correctly.
