### ISSUE TITLE
New Feature: Expose export API endpoint with authToken authentication

### ISSUE THREAD

**Issue by hellerbarde** [zadam/trilium#1073]
Expose export endpoint with the authToken authorization and not only with the session auth.

I am willing to make the changes, if someone points me in the right direction.

That would allow the user to automatically pull subtrees in HTML/Markdown to serve somewhere as a read-only website.

**Comment by zadam** [comment]
Hi, this is an interesting feature which I've thought about few times ...

As a starting point look up `routes.js` and `auth.js` and search for "export". There is already support for API token authentication (for Trilium Sender) - there's a table and the auth logic, but there isn't a UI to generate/manage the tokens.

There's also a question whether to export to FS directly or export ZIP as normally and let the client to handle the rest. The latter would be easier since the export is tied to the ZIP ...

**Comment by hellerbarde** [comment]
Thanks for the pointers. I'll look into it over the weekend.

I didn't completely understand the last paragraph. Can you elaborate? Apologies...

**Comment by hellerbarde** [comment]
How can I build my own docker container? there is a server-package.json referenced in the Dockerfile that I can't find.

**Comment by zadam** [comment]
run `bin/build-docker.sh`

**Comment by hellerbarde** [comment]
Oh! Awesome, thanks.

**Comment by zadam** [comment]
ETAPI supports ZIP export in 0.54: github.com/zadam/trilium/wiki/ETAPI
