### ISSUE TITLE
shortcut to go to last created child of today's note

### ISSUE THREAD

**Issue by nil0x42** [zadam/trilium#1092]
Hi, i'm trying to add a shortcut to go to the last created note, which is a direct child of today note (so i can quickly access last clipped note)

The logic would be to get today note, then iterate direct childs and return noteid of the most recent one
But i suck at javascript, so could you help me getting `most recent direct child of today note` ?

**Comment by leeyaunlong** [comment]
use this search query to get last created today note , 
```
@dateNote and @orderBy=-dateCreated and @limit=1
```
you can save this search query for next , you can also add a shortcut for this ( add label : keyboardShortcut, value is your defined shortcut).

**Comment by zadam** [comment]
Actually that will not work since the child note won't have `datNote` label. I think this is actually not expressible using current search syntax, but it's a nice example of power of the new syntax (#1041) where you could express it like this:

```
# note.parents.labels.dateNote orderBy note.dateCreated desc limit 1
```

And plugged into the API call:

```
const lastNote = await api.searchForNote('# note.parents.labels.dateNote orderBy note.dateCreated desc limit 1');
```

However this is not yet released so I guess it does not help.

Going by the memory I would implement it in JS something like this:

```javascript
const todayNote = await api.getTodayNote();
const children = (await todayNote.getChildNotes()).slice(); // make a copy for sorting

children.sort((a, b) => a.dateCreated > b.dateCreated ? -1 : 1); // sort descending

const lastChild = children[0];
```

**Comment by nil0x42** [comment]
Wow, the new syntax rocks !
From now i'm using the code you gave, thank you @leeyaunlong & @zadam :)
