### ISSUE TITLE
App crashes at startup after bulk file upload and abnormal termination

### ISSUE THREAD

**Issue by 4asifm** [zadam/trilium#1093]
So last night i got very excited and tried uploading about 40 documents (pdf and images mostly) in the desktop version of Trillium V0.42.3. I don't know what happened - the ui disappeared. And then I tried starting it again. Now every time try starting the desktop version the application crashes.

Attached logs for both last night and today.

Is there any chance of a manual cleanup? For example, remove the defective items from SQLite db?
[trilium-2020-06-08.log](https://github.com/zadam/trilium/files/4746554/trilium-2020-06-08.log)
[trilium-2020-06-07.log](https://github.com/zadam/trilium/files/4746555/trilium-2020-06-07.log)

**Comment by zadam** [comment]
Hello, this is quite strange. The logs don't make much sense it's filled with many 404 requests with some mysterious IDs.

I'm very interested in your case since this is quite troublesome. When you open the desktop app, it crashes. Is it still possible to open the developer console using CTRL-SHIFT-I. If yes, what is in the console? Could you post the output and/or screenshot?

Thanks!

**Comment by 4asifm** [comment]
Nothing much in the dev console - or from what I could make out.

![trilium1](https://user-images.githubusercontent.com/7342520/84138148-d4d83700-aa1b-11ea-82b9-a6c407440d77.PNG)

**Comment by 4asifm** [comment]
Interesting discovery - so I realized my server (localhost) was running in the background all this time. I stopped the server and restarted the desktop and everything seems to be fine.
My initial setup was done like this.
1. On my laptop, Trillium installed as desktop
2. Server setup on laptop. 
3. Desktop instance setup to sync data to server
4. Tablet setup to connect to server on desktop
5. Upload some pdf files on desktop 

Before I restart the server and try a synch of data - let me know if there is any other logs/debug i can collect?
![trilium2](https://user-images.githubusercontent.com/7342520/84138709-b6267000-aa1c-11ea-8dcc-25c2632fbfea.PNG)

**Comment by 4asifm** [comment]
Some more information.

1. My server instance was started with TRILIUM_DATA_DIR=<different-location-than-desktop-instance-data-dir>
2. I have attached a snapshot of developer console from the now running desktop instance which seems to work fine.
![trilium3](https://user-images.githubusercontent.com/7342520/84141265-e7a13a80-aa20-11ea-9bce-edbdefd3588a.PNG)

**Comment by 4asifm** [comment]
Final update - :) I hope so! So I kinda figured out how to reproduce the problem.
Applicable to my setup - 
1. Start server, and then desktop application - desktop crashes at startup
2. stop server, run desktop application - and then start server. Everything fine (so far! I haven't yet tried adding/editing or deleting notes)

**Comment by zadam** [comment]
Hello, thank you for the detailed report. It sounds a bit like #1018 

It looks like a platform (electron) issue. Could you do a little experiment?

Open your settings in the desktop client and the the proxy with special value "noproxy"

![](https://user-images.githubusercontent.com/617641/84370037-ff6eef00-abd7-11ea-8e8f-be3b63bfe6b8.png)

(server instance address leave as you have already). Save the settings.

Now try to reproduce the crash as you wrote before. I'm interested if it keeps crashing with this setting or not.

Some background info - trilium has 2 different implementations of sync requests - one is using the chromium/electron API (which supports system proxy) and one node.js API (which supports explicit configured proxy). Setting the value to "noproxy" forces usage of node.js API instead of default electron API (which I suspect might be the source of the problem).

Thanks.

**Comment by 4asifm** [comment]
Thanks for guiding me. So I executed what you suggested and it still crashes

I set no proxy
![trilium5](https://user-images.githubusercontent.com/7342520/84499895-7f9d5f00-ac81-11ea-9733-27a341138fd5.PNG)

and then exited the app. Started the server. then started the app - and boom ! it crashed :(
![trilium4](https://user-images.githubusercontent.com/7342520/84500149-f9cde380-ac81-11ea-9107-f2e1065a5bac.PNG)

**Comment by zadam** [comment]
Hello, I managed to reproduce the issue and it has been fixed. I need to test it a bit more, but I should be able to release the fix soon. Thanks for help!

**Comment by 4asifm** [comment]
Any chance I can get hold of a patch or something. My server is grossly out of synch and hence the other devices too.

**Comment by zadam** [comment]
Hi, this fix should be in 0.43.0-beta, could you try that?

**Comment by 4asifm** [comment]
I setup a 0.43.1 desktop instance with the old data directory from my previous desktop installation.

It started properly.

I then setup a fresh server installation of 0.43.1- with a completely empty data directory.

the first synch handshake went through fine. - but during synch the desktop app crashed again - I have a feeling it is something with the data/files that has been uploaded?
![trilium6](https://user-images.githubusercontent.com/7342520/85398078-a893de80-b522-11ea-8c19-5eb5fa69ebc9.PNG)

**Comment by zadam** [comment]
That's unfortunate. I don't think it's the data, but the sync itself - I think it's the electron's native net handling which causes the crash.

Could you try one more time the "noproxy" as described in https://github.com/zadam/trilium/issues/1093#issuecomment-642535709 ? I think it should help now. Otherwise is anything weird appearing in the log files?

**Comment by 4asifm** [comment]
It crashes with both options "noproxy" or empty.

Here is the last logs from the desktop

07:58:16.608 INFO  Notes deleted: 64, not deleted 729 
07:58:16.610 INFO  Note revisions deleted: 1, not deleted 14 
07:58:16.611 INFO  Branches deleted: 96, not deleted 741 
07:58:16.613 INFO  Attributes deleted: 97, not deleted 1498 
07:58:16.615 INFO  API tokens deleted: 0, not deleted 2 
07:58:17.053 INFO  Slow query took 414ms: 
                    SELECT noteId
                    FROM notes
                             JOIN note_contents USING (noteId)
                    WHERE isDeleted = 0
                      AND isProtected = 0
                      AND content IS NULL 
07:58:17.065 INFO  All consistency checks passed (took 459ms) 
07:58:58.326 INFO  Slow query took 348ms: SELECT * FROM note_contents WHERE noteId = ?

**Comment by 4asifm** [comment]
My workaround.

I copied the db file (just the document.db file) to the server's store. I set proxy as "noproxy". Everything went through fine.

I will check if there is a way to put more log lines and test where exactly the crash was.
