### ISSUE TITLE
Allow adding text nodes to UI

### ISSUE THREAD

**Issue by adityavm** [zadam/trilium#1097]
Currently the only UI element available to scripts are buttons. Allowing text nodes to be created would let us add bits of information to the UI.

Eg. my current use case is to add a time widget so that I don't have to move my mouse around while in full screen / zen mode. Second use case would be to add a "word count" indicator for the currently active note.

**Comment by zadam** [comment]
Hi, the proper way to implement this would be a custom widget which would then be inserted into a layout. Unfortunately there isn't a proper documentation for this yet. Part of the reason is that it's not completely stable API-wise and might change slightly. If you still want to give it a go, here's an example:

```javascript
const TPL = `<div></div`;

class TestWidget extends api.TabAwareWidget {
    get position() { return 15; }
    
    get parentWidget() { return 'center-pane'; }
    
    doRender() {
        this.$widget = $(TPL);
        return this.$widget;
    }
    
    async refreshWithNote(note) {
        if (!note.hasOwnedLabel('showTestWidget')) { // show widget only on notes with this label
            this.toggleInt(false); // hide
            
            return;
        }
        
        this.toggleInt(true); // display

        this.$widget.empty().append($("Hello world!"));
    }
}

module.exports = new TestWidget();
```

The script note must be marked with label `widget`

**Comment by adityavm** [comment]
@zadam this does the trick for now. thanks!
