### ISSUE TITLE
Hiding items from right sidebar

### ISSUE THREAD

**Issue by msbentley** [zadam/trilium#1113]
I may be going crazy, but I had the feeling that the various items in the right side-bar could be hidden in the past, but I cannot find that setting now.

It's not a big deal, but there are some sections I rarely use (e.g. link map, similar notes) and I was hoping to remove these. Can this be done e.g. in CSS somehow, if not in the settings?

**Comment by zadam** [comment]
Hi, you're not going crazy, this was possible in 0.40 and older, but with the new layout this was removed. I want to make it possible for the user to modify the application layout, but no fixed roadmap yet.

However, instead of completely hiding the individual boxes, you can just collapse them by clicking on their title, that should do the trick for the most part ...

**Comment by msbentley** [comment]
Thanks @zadam - yes, I already have them minimised. Good to know I'm not (completely) crazy ;-)
