### ISSUE TITLE
sorting children not working?

### ISSUE THREAD

**Issue by voidplayer** [zadam/trilium#1126]
v0.42.7

Maybe im using it wrong, I added the attribute sorted and hit f5 and restarted trilium but still is not ordered
I added it to another book a couple of days ago and didnt work back then, but now its ordered (so it worked in the end) but im not sure what triggered it to actually execute the ordering

![2020-06-23_17-07](https://user-images.githubusercontent.com/4019910/85421216-77dc9500-b574-11ea-8a17-a0dcc6fc581f.png)

**Comment by zadam** [comment]
Hi, thanks for reporting this issue. The problem was in lack of triggers to resort the children - it was triggered only when you added a new child note to the `sorted` note. This whole functionality was added mainly for "day notes" to work better and for that it worked OK, but otherwise it wasn't that useful generally.

But now I added a trigger to resort when you add the label to the note and also when you rename a child note so it should cover most (or all?) needs.
