### ISSUE TITLE
Searching empty attributes

### ISSUE THREAD

**Issue by voidplayer** [zadam/trilium#1128]
I inherit a ```label-definition | tag | text multivalue promoted: true```

I added a few tags and now im trying to search notes with empty tags. I looked at the [search page](https://github.com/zadam/trilium/wiki/Search) and tried a few patterns, but i dont seem to be able to figure out how :S

Could you add it explicitly to the wiki? Im sorry if it is obvious

Thanks!

**Comment by zadam** [comment]
I'm not sure what you mean by "empty attribute" - does it mean attribute with empty value (then search for it with `@tag`

or notes without a certain attribute (then you should search with `@!tag`).

**Comment by voidplayer** [comment]
empty attribute means the labe-definition has empty value

I tried a few things, including ```@tag!="*"```

**Comment by zadam** [comment]
So I tried to understand again: you have a label definition inherited but not set - in that case the label for the note does not exist (it is created when you fill it in) - syntax for that would be `@!tag`

However that will return all the notes without this label but you probably want only those notes which have this label definition inherited. This is unfortunately not easy to do with the current search since search does not take inheritance into account. You could workaround that using `@in` that you would reduce the result set to only those notes which are inside the subtree from which the label definition is inherited (unless it is inherited from template).

This will be solved in 0.44 which has overhauled search and it does support inheritance. Then it would be expressed like this:

```
#label:tag #!tag 
```

where: - 

*   `#label:tag` - searches for notes which do have this label definitions (inherited or note)
*   `#!tag` - but those notes don't have the "tag" label set

However for this you would have to wait a bit ...

**Comment by voidplayer** [comment]
Yeah, the ```@in= @!tag``` trick worked!

Thanks!

Looking forward to the new syntax!
