### ISSUE TITLE
What is the meaning of the asterisk next to note names

### ISSUE THREAD

**Issue by voidplayer** [zadam/trilium#1139]
I noticed some notes have a little ```*``` next to them

I read the whole wiki and couldnt find what does that mean :)

**Comment by zadam** [comment]
It's a little mark that this note is cloned into at least 2 places in the tree.

**Comment by meichthys** [comment]
@zadam It looks like the Cloning [Demo](https://github.com/zadam/trilium/wiki/Cloning-notes#demo) is a little outdated. It doesn't show the asterisk and it shows a "Paths" dropdown box next to the note title. I don't think that dropdown exists anymore even if the note is a clone.

I'd submit a pull request for the fix but i don't think github allows pull requests for wikis :/

**Comment by zadam** [comment]
Yes, the demos are outdated for the most part. "Paths" changed a bit and is now above the tree:

![image](https://user-images.githubusercontent.com/617641/86092919-7c420a00-baae-11ea-93dd-f7abbc9125b6.png)

I think there's no need for PR in wiki, it's publically editable. From time to time I see somebody fixes something there on their own ...

**Comment by voidplayer** [comment]
Oh, thats nice

I was looking for all the clone notes by myself just by clicking in UI and couldnt find it

Maybe change that down arrow to something more auto descriptive? some clone icon would be nice

I googled a few to make a suggestion and i like these 3:

https://www.iconbros.com/icon_font/ib-pe-f-clone
https://www.onlinewebfonts.com/icon/448879
https://www.onlinewebfonts.com/icon/49506

**Comment by LiamFry** [comment]
I'm new to Trilium. I've been migrating notes from plain text documents to Trilium. As I go, I've been reorganizing things within my tree structure. All has been uneventful for the past two days. This morning, I moved two notes from one branch to another. Suddenly, the destination branch - NOT THE NOTES - had an `*` suffix. It took me forever to discover this means "cloned." Here are the issues:

1. I cloned nothing. I selected the two notes to move, right-clicked, and chose "Move to ..."
2. The "container note"/folder receiving the moved notes was adorned with the `*` suffix; **NOT** the notes themselves.
3. I have been unable to find any way to identify, isolate, or other list these "clones," meaning: If an item is tagged as a clone, I want to know where all its "siblings" are.
4. As I worked on trying to understand `*` and what it meant - toggling between the browser and Trilium - more and more and more `*` started to appear all over my tree. Within 10 minutes, **EVERY** "container note"/folder had a `*`. I had to quit Trilim and restart. After that, **NO** "container note"/folder had a `*`

I've also been unable to find documentation on how to "break cloning." (If I understand cloning, it's more like a "symbolic link" than it is a "copy." To me, a "clone" is a copy - not a link - but the Clone documentation describes them more as links.) If I understand cloning correctly - that there's really "one note" but it's referenced in two or more "container notes"/folders - how do I say "split the link and make them two separate, independent notes?"

**Comment by zadam** [comment]
Hi,

> I have been unable to find any way to identify, isolate, or other list these "clones," meaning: If an item is tagged as a clone, I want to know where all its "siblings" are.

This button will show list of clones:

![image](https://user-images.githubusercontent.com/617641/114926803-10f4d900-9e31-11eb-91f2-63f4a3de4fa1.png)

> 
As I worked on trying to understand * and what it meant - toggling between the browser and Trilium - more and more and more * started to appear all over my tree. Within 10 minutes, EVERY "container note"/folder had a *. I had to quit Trilim and restart. After that, NO "container note"/folder had a *

That's definitely weird, I haven't seen anything like this yet ... :-/

> I've also been unable to find documentation on how to "break cloning." (If I understand cloning, it's more like a "symbolic link" than it is a "copy." To me, a "clone" is a copy - not a link - but the Clone documentation describes them more as links.)

I realize that "cloning" is not the best name, but I haven't been able to figure out a better name. "link" is too generic and is also used for too many other concepts. 

> that there's really "one note" but it's referenced in two or more "container notes"/folders - how do I say "split the link and make them two separate, independent notes?"

There is such a functionality, but it has nothing to do with clones so there's no "clone breaking":

![image](https://user-images.githubusercontent.com/617641/114927281-95475c00-9e31-11eb-8340-640ba6e4cf2c.png)

**Comment by WidgetMidget** [comment]
While simply calling them links is probably too generic and widely used for something else for users to be able to pick up on contextual information, perhaps consider renaming them to symlinks or [symbolic links](https://en.wikipedia.org/wiki/Symbolic_link) as they're called.

**Comment by meichthys** [comment]
I also like the `symbolic link` term, although i could see how that would be confusing for non-technical users. Perhaps another option would be to call it a `linked clone` which would indicate that the note would be an identical clone but also linked to the  original note.

**Comment by zadam** [comment]
`symbolic link` has quite specific technical meaning and trilium "clones" differ on a number of points. [Hard link](https://en.wikipedia.org/wiki/Hard_link) is very close concept but it's rarely used (especially directory hard links which are normal in trilium) and it's not widely understood ...

**Comment by chee** [comment]
https://en.wikipedia.org/wiki/Aliasing_(computing)

perhaps it is an alias

**Comment by GreatestFool** [comment]
Despite the fact that symbolic links differ in some aspects from cloning, it is still something closer to what is actually being done as opposed to the word cloning, which simply from the meaning of the word lends itself to a separate -if similar- copy of the file. Regardless of it is a technical word or not, the users will have to look up what is meant by cloning as it is now either way. I would not think of something so close to symbolic links when I see a context menu saying it'll clone something. I'd assume it'd do just that, make a separate identical copy. Meanwhile, for those who know about symlinks, they would be able to infer the meaning from it. While other users will know it is at least not the act of copying and can look it up on the wiki here.

**Comment by chee** [comment]
"symbolic link" indicates a relationship where one file is the origin (a real file), and the other file is a pointer to that file (not a real file, but a shortcut to a file).

In Trilium, "clones" are two separate names to access the same memory. That's an `alias`. That's what hard links are too. If the terminology is going to change it should change towards expressing the relationship more clearly. "Symlink" is at best a horizontal move. `Alias` is more clear.

> Meanwhile, for those who know about symlinks, they would be able to infer the meaning from it. 
I don't think so. For those who know about symlinks, "symlink" is just as unclear as "clone". It's terminology that's already used for a different concept.

**Comment by zadam** [comment]
@chee Yes, that's my thinking as well. 

In my mind "alias" also implies "origin" (as in "alias of XXX", see e.g. [wiktionary](https://en.wiktionary.org/wiki/alias#English)). But otherwise it's pretty good and seems strictly better than "clone". Let me think about this a bit more ...

The way I sometimes explain this concept is that there's a note and this note can be "placed" into multiple locations in the tree. That leads me to sometimes name this as "note placement" or "note location". This also maps very clearly to the internal concepts - that there's a separate "note" object and separate branch(es) which place the note into the tree.

But these sound weird and also most of the time it's quite unnatural for the end user to think about these two concepts separately. Cloning/aliasing is rather a special case from the user's point of view where probably the big majority of notes don't have just one "placement" and thus it's easier to think about it as "alias" rather as a "second location".

**Comment by chee** [comment]
@zadam I agree with you there, though I think the term `alias` in computing is actually accurate here https://en.m.wikipedia.org/wiki/Aliasing_(computing)

the same location accessible via different symbolic names

you can also see it used that way on the Wikipedia page for _hard link_ :) 
https://en.m.wikipedia.org/wiki/Hard_link

> Creating an additional hard link has the effect of giving one file multiple names (e.g. different names in different directories) all of which independently connect to the same data on the disk, none of which depends on any of the others. This causes an alias effect: e.g. if the file is opened by any one of its names, and changes are made to its content, then these changes will also be visible when the file is opened by an alternative name. By contrast, a soft link or “shortcut” to a file is not a direct link to the data itself, but rather is a short file that contains the text of a file name, or a location that gives direct access to yet another file name within some directory. 

I think this is the exact distinction we've been driving at ^_^

**Comment by meichthys** [comment]
The only difference I see is that we don't use different names, but otherwise 'alias' seems to fit the bill.

**Comment by chee** [comment]
> The only difference I see is that we don't use different names, but otherwise 'alias' seems to fit the bill.

for us the `name` is the complete path

**Comment by HermasciousLevander** [comment]
There is a very important distinction to be made here. What was linked by @chee is specifically [_aliasing_](https://en.m.wikipedia.org/wiki/Aliasing_(computing)) not _alias_. An [alias](https://en.wikipedia.org/wiki/Alias_(command)) is an interpreter that replaces a string with another. This allows you to make `ls` actually run `ls -alF` without having to write anything more than `ls`.

If we are to avoid end-user confusion with less known technical terms like @zadam mentioned earlier, then a programming term like aliasing is _not_ the way to go. It even mentions that it can make things difficult for a programmer, simply because of how it functions. Likewise, Trilium 'cloning' is not changing a value that only lives in memory, it is changing a file that lives in storage. It is a term that will only cause confusion if you do not at the very least dabble in programming, and in this use-case it will only cause further confusion for those who do know about it and use shells with any frequency. I was certain that the discussion was about aliases and not aliasing until I looked at the article.

Clones, currently, is the go to. While it most certainly isn't perfect, it is far better than calling it an alias. On the other hand, a symbolic link is a much more widely known term that also _fits_ the use-case. [Symbolic links](https://man.archlinux.org/man/symlink.7.en) are files that act as _pointers_ to _other_ files, which is essentially exactly what cloning is doing. It is not creating permanent duplicate files, nor is it changing values of memory-only data, it is just a pointer in the note tree to another file in the directory structure.

**Comment by voidplayer** [comment]
Theres nothing perfect with this, but id go with hard links, which describes what it is, a pointer indistinguishable to the enduser from the original pointer, to the same file 

All other terms are biased to the users depending on what they already know, because all are already loaded terms

symbolic link are not a good fit because if you delete the original, you end up with nothing, but in trillium if you delete the original, you end up with the same note

Clone implies that you have 2 separates copies in every program i have used

Theres is no perfect solution for this name, but the original problem here is not to understand what it does, but discoverability of what the asterisk even means

**Comment by HermasciousLevander** [comment]
Not sure if functionality for this is implemented or not, but perhaps having a small pop-up appear when hovering the asterisk that says "Hard link" also? That would at least help the discoverability of what causes it a little more.
