### ISSUE TITLE
Do you have a Trilium Road Map you can share?

### ISSUE THREAD

**Issue by Engr-AllanG** [zadam/trilium#1165]
Hi,
I am wondering if you have a Trilium development road map you'd be willing to share? I am curious what plans you my have for the app in the future

**Comment by zadam** [comment]
Hi, there's a backlog https://github.com/zadam/trilium/milestone/5 but that paints a very incomplete picture.

Otherwise I don't have a public roadmap. There's many things in my head but they are not written down. Maybe I should do that.

Overall theme of the roadmap is refinement, stabilization, UX improvements, speed optimization (if possible) and adding smaller features etc. I'm fairly happy with the scope of features of Trilium and I don't really have plans for any really ground breaking stuff (such as multi-user support or android app).

From top of my head some features I'd like to add are:

*   Math/equation support - there's a CKEditor plugin for that so should be relatively easy
*   Some form of diagramming and/or free-form drawing - probably long-term since this is rather big
*   Table of Contents support and improvements to "Include note" concept
*   Improvements to search interface and saved notes - more view modes (list, book-style view ...) - this is probably coming in 0.45 or so ...

**Comment by jaroet** [comment]
If you could include somehow the mermaid diagram JS library ... that would
be awesome...

https://mermaid-js.github.io/mermaid/#/

Op do 30 jul. 2020 om 09:30 schreef zadam <notifications@github.com>:

**Comment by Engr-AllanG** [comment]
@zadam Thanks for the reply - it is great to see that list you put together of potential features, and you're overall directive of stabilization, UX improvements and optimization.

I too, am happy with the feature set

I am working on a theme based on the theme used in the [IMF Obsidian demo](https://forum.obsidian.md/t/imf-v3-soon-to-be-known-as-the-lyt-framework/390). Can you upload it here when I'm done?

**Comment by zadam** [comment]
@Engr-AllanG sure, I think other people would be interested as well!

**Comment by msbentley** [comment]
That sounds great - I'm especially looking forward to "more view modes" - thanks for all your hard work!

**Comment by danielandastro** [comment]
That sounds awesome, I'm personally looking forward to math and equations support
