### ISSUE TITLE
TOC widget question

### ISSUE THREAD

**Issue by Engr-AllanG** [zadam/trilium#1169]
Hi,
I'd like to working on creating a sidebar widget that would scan a note and create a TOC based on Headings. I have some background in programming (c++, python, labview) so I have some ability to try and figure out how to code this. I was going to start by looking at the word count widget code you provided. If you have any other quick tips or references to get me started, would you mind commenting?

**Comment by zadam** [comment]
Hi, one tip would be to use browser DOM instead of parsing the HTML yourself. Walking the DOM object structure should be then pretty easy.

One area where I expect problems is when you already have a built TOC, you want to be able to scroll to the paragraph/heading on click. I'm not sure how to do this - standard way is to assign an ID/anchor and scroll using that, but CKEditor doesn't generate IDs for headings (which would be problematic anyway because of tabs). You can also scroll to the element programmatically using JS but then you need to correctly identify the element in the CKEditor instance.

**Comment by Engr-AllanG** [comment]
@zadam Thanks for the feedback. I'll look into DOM and start there.

Making the TOC/outline clickable would be secondary for me. I'll start with just getting the basic outline displayed in a widget and go from there. Scrolling programmatically by manually identifying the heading and its location doesn't sound terribly hard, but I will cross that bridge when/if I get there.

Thanks for the help

**Comment by Engr-AllanG** [comment]
Closing - this isn't something I'm going to get to anytime soon

**Comment by ericens** [comment]
have you solve this problem? can you share the plugin /widget  out, i  also need the table of content

**Comment by ericens** [comment]
@Engr-AllanG  have you get the "TOC feature" done? can you share this widget/plugin  out ?

thank you !

**Comment by Engr-AllanG** [comment]
@ericens No, I never started this project
