### ISSUE TITLE
[BUG] Import html page can cause whole instance lockdown

### ISSUE THREAD

**Issue by HiFiPhile** [zadam/trilium#1176]
Version 0.43.3

I'm trying to import a html file with scripts into trilium, which result the whole instance turns into a locked down state.
Here is the [page](https://gist.githubusercontent.com/HiFiPhile/c8b44b0366674261440912fa8d8a2d60/raw/d60f26d8e9736948621a7238d11c8fc93ec6594e/Table%2520based%2520NTC%2520Code%2520Generator.html).

Server log:
```
10:22:27.205 INFO  Router not found for request /Table%20based%20NTC%20Code%20Generator_files/ntc.png
{"status":404}
Error: Router not found for request /Table%20based%20NTC%20Code%20Generator_files/ntc.png
    at /usr/local/trilium/src/app.js:73:17
    at Layer.handle [as handle_request] (/usr/local/trilium/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/local/trilium/node_modules/express/lib/router/index.js:317:13)
    at /usr/local/trilium/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/usr/local/trilium/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/local/trilium/node_modules/express/lib/router/index.js:275:10)
    at Layer.handle [as handle_request] (/usr/local/trilium/node_modules/express/lib/router/layer.js:91:12)
    at trim_prefix (/usr/local/trilium/node_modules/express/lib/router/index.js:317:13)
    at /usr/local/trilium/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/usr/local/trilium/node_modules/express/lib/router/index.js:335:12) 
10:22:28.151 INFO  GET /api/notes/hENIOfHrA3PN/revisions 
10:22:28.151 INFO  GET /api/similar-notes/hENIOfHrA3PN 
10:22:29.097 INFO  GET /api/script/startup 
10:22:29.106 INFO  POST /api/tree/load 
10:22:29.114 INFO  POST /api/tree/load 
10:22:29.123 INFO  POST /api/tree/load 
10:22:29.132 INFO  POST /api/tree/load 
10:22:29.141 INFO  POST /api/tree/load 
10:22:29.151 INFO  POST /api/tree/load 
10:22:29.160 INFO  POST /api/tree/load 
10:22:32.130 INFO  POST /api/recent-notes 
10:22:32.140 INFO  POST /api/recent-notes 
10:22:41.890 INFO  GET / 
10:22:41.898 INFO  GET /login 
10:22:48.462 INFO  POST /login 
10:22:48.515 INFO  GET / 
10:22:48.518 INFO  Generated CSRF token iasE1PHs-k9W5PDTlh5lYDHI-gJLj3Mf7DxY with secret _csrf=F7GCgvEPKWLYZnxv229RWAuE; Path=/ 
10:22:48.518 INFO  Generated sourceId=FyliN8Z3vb0F 
10:22:48.676 INFO  GET /api/tree 
10:22:48.677 INFO  GET /api/options 
10:22:48.679 INFO  GET /api/keyboard-actions 
10:22:48.680 INFO  GET /api/keyboard-shortcuts-for-notes 
10:22:48.687 INFO  GET /api/notes/download/Yg6n7JsizskA 
10:22:48.688 INFO  GET /api/notes/download/Ns4oXvv1oOWc 
10:22:48.693 INFO  GET /api/script/widgets 
10:22:50.754 INFO  GET /api/script/startup 
10:22:50.763 INFO  POST /api/tree/load 
10:22:50.770 INFO  POST /api/tree/load 
10:22:50.778 INFO  POST /api/tree/load 
10:22:50.785 INFO  POST /api/tree/load 
10:22:50.791 INFO  POST /api/tree/load 
10:22:50.801 INFO  POST /api/tree/load 
10:22:50.808 INFO  POST /api/tree/load 
10:23:16.025 INFO  PUT /api/options 
10:23:16.026 INFO  Updating option leftPaneVisible to false 
10:23:16.038 INFO  GET /api/similar-notes/A7dP7NDDrln9 
10:23:16.634 INFO  PUT /api/options 
10:23:16.635 INFO  Updating option leftPaneVisible to true 
10:23:21.032 INFO  JS Error: Encountered error Process exceeded time limit 5000: Error: Process exceeded time limit 5000
   at Anonymous function (https://note.xxx.com/app-dist/desktop.js:1:70357), reloading frontend.
Stack: Error
   at y (https://note.xxx.com/app-dist/desktop.js:1:72530)
   at Anonymous function (https://note.xxx.com/app-dist/desktop.js:1:75856)
   at Generator.prototype.throw (native code) 
10:23:21.053 INFO  GET / 
10:23:21.055 INFO  Generated CSRF token r6V22vWh-GLC23TndFclxC7l-CdK3xWmtzUo with secret undefined 
10:23:21.055 INFO  Generated sourceId=Qd0STL27gEt5 
10:23:21.193 INFO  GET /api/tree 
10:23:21.194 INFO  GET /api/options 
10:23:21.195 INFO  GET /api/keyboard-actions 
10:23:21.197 INFO  GET /api/keyboard-shortcuts-for-notes 
10:23:21.206 INFO  GET /api/notes/download/Ns4oXvv1oOWc 
10:23:21.210 INFO  GET /api/script/widgets 
```

**Comment by zadam** [comment]
Hi, what do you mean by "lockdown". When I try to import the file, this happens:

![](https://user-images.githubusercontent.com/617641/89582661-4aecf480-d839-11ea-9eb9-67be68fd00a8.png)

Which is of course incorrect - the script hijacks the whole application. This is pretty bad and has been already fixed in master branch (future 0.44) by sanitizing the imported HTML.

However I'm guessing this is not what you want - instead you want to have this script working inside Trilium. This would be normally possible by using "render note" functionality, however it is not possible with this particular script because of the way it is written. Script uses `document.writeln` (very obsolete technique) which discards the whole existing loaded document (= Trilium application) and replaces it with itself. Normal, well-behaving custom scripts can run in Trilium, but this isn't one of them ...

**Comment by HiFiPhile** [comment]
Hi,

>Hi, what do you mean by "lockdown"

I was to vague. The import was done in Chrome, which result the whole application hijacked.
Then I tried open a new Edge window, from there I could login but no note is displayed.

> This is pretty bad and has been already fixed in master branch (future 0.44) by sanitizing the imported HTML.

That's a great news.

> However I'm guessing this is not what you want - instead you want to have this script working inside Trilium.

It would be great but I don't want to ask too much :) I'm not a web guy, if I translate the page to DOM instead of `document.writeln` would it work ?

**Comment by zadam** [comment]
Now the problem is that after login, Trilium will try to visit the last opened note - which is this hijacking page.

You can recover from this, open http://[your-trilium-domain]/#root 

After that I recommend deleting the hijacking note, but you must be careful to not click on it / activate it. Locate it in the tree, right click on it and click on "delete"

> It would be great but I don't want to ask too much :) I'm not a web guy, if I translate the page to DOM instead of `document.writeln` would it work ?

Yes, that sounds correct. Well behaving script will operate only on data (DOM nodes) which it itself created ...

**Comment by HiFiPhile** [comment]
No worries, I always make backups :)

Close since http sanity check is implemented in latest version.
