### ISSUE TITLE
Attribute Menu ignores font size, is cut off at bottom

### ISSUE THREAD

**Issue by LorenAmelang** [zadam/trilium#1185]
As the title says, the Attribute Menu ignores font size selections, and long lists are cut off at the bottom of the main window. 
![Attribute Menu ignores font size](https://user-images.githubusercontent.com/1297090/89980818-7bf96a80-dc27-11ea-9e10-283f62b43a0b.JPG)

I can blind type entries I know, but my tag list will quickly outrun the page. Would be nice to be able to see the dropdown  in a tiny font, single spaced. Could my Windows screen scaling be affecting this? Maybe there is a beter way to attach tags to notes? 

0.43.3

**Comment by zadam** [comment]
Hi, this whole dialog is removed in master branch (future 0.44) since there will be new attribute UI (discussed a little bit in #1068).

I did a quick test and the new attribute UI seems to scale just as the rest of the UI.

So I'm going to close this since there won't be any new changes to the old attribute UI ...
