### ISSUE TITLE
Using reverse proxy, customResourceProvider url path error

### ISSUE THREAD

**Issue by NKid** [zadam/trilium#1187]
Trilium：0.43.3
Docker server：`docker run -d --name trilium --restart=always --network="my-bridge" -v ~/trilium:/root/trilium-data 
zadam/trilium:0.43-latest`

nginx config
```nginx
server {
    listen 443 http2 ssl;
    listen [::]:443 http2 ssl;
    server_name demo.com;

    location /trilium/ {
        client_max_body_size 0;
        proxy_pass http://trilium:8080/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}
````

Steel Blue (build in theme), don't apply font-family 'Raleway'.
Network panel show the font url is `https://demo.com/custom/fonts/raleway.woff2` (http 404)
It should be `https://demo.com/trilium/custom/fonts/raleway.woff2` (paste this link into url bar can be download)

**Comment by zadam** [comment]
Hi, thanks for reporting, this has been fixed in master (in demo document).

In your document you can fix it easily by locating the "Steel blue" note and removing the first `/` from `/custom/fonts/raleway.woff2` and `/custom/fonts/garamond.woff2`, thus making the links relative which plays well with non-root paths.
