### ISSUE TITLE
44.1-beta chrome word count widget cut off

### ISSUE THREAD

**Issue by Engr-AllanG** [zadam/trilium#1224]
44.1-beta, server. On Chrome (multiple computers), the word count widget is displayed too low, and half cut off. It appears correct when using Safari for some reason

I messed around with the return position code but did not see a change
`Class WordCountWidget extends api.TabAwareWidget {
    get position() { return 100; } // higher value means position towards the bottom/right`

![image](https://user-images.githubusercontent.com/3161759/92637930-60b56580-f28e-11ea-9b90-5b83983c71a4.png)

**Comment by zadam** [comment]
Hi, thanks for reporting this issue. Since v0.44 Trilium uses new CSS `contain` which is sort of a performance optimization, hinting to the rendering engine which helps especially with large note trees/long notes but also means that you need to set the dimensions manually. The easiest way to fix that is to opt out of this optimization for a specific widget by adding `contain: none;`

So replace:

```html
const TPL = `<div style="padding: 10px; border-top: 1px solid var(--main-border-color);">
```

With:

```html
const TPL = `<div style="contain: none; padding: 10px; border-top: 1px solid var(--main-border-color);">
```

**Comment by Engr-AllanG** [comment]
excellent, that fixed it!
