### ISSUE TITLE
Can't get template to work for Day note children

### ISSUE THREAD

**Issue by wwwald** [zadam/trilium#1236]
Using latest release Trilium 0.43.4.

I'm trying to configure a default template for children of Day notes in the journal.

- day notes have a template configured via relation `child:child:child:template` on the root "journal" note. This works, the template note is called "template-day".
- On this "template-day" note, I configured relation "`child:template`" with value "template-snippet" (another template note).
This does NOT work, newly created child notes of a day note do not follow the template.

I have the feeling that I'm overlooking something silly. Any clues to why this is not working?

**Comment by zadam** [comment]
Hi, you're not doing anything wrong. The problem here is that the child: attribute is defined on a template and not on a note directly. As a performance optimization some operations in Trilium don't take into account inherited attributes (since that's slightly more expensive) and this copy inheritance was one of them.

I just enabled this in f5f48ef so it should be possible in the next release.

**Comment by tmaleshafske** [comment]
I attempted this and it fails to create the child note under the primary note. Currently using version 0.45.2
