### ISSUE TITLE
Questions about interface design（UI）

### ISSUE THREAD

**Issue by Rsose** [zadam/trilium#1252]
Don't you think the new beta versions of ATTRIBUTE and SIMILAR NOTES take up a lot of space,I mean UP space and down space in the middle.
**Look at old vesion**
![image](https://user-images.githubusercontent.com/51273534/93502443-02842480-f917-11ea-89c3-003429ef0498.png)
I don't think there should be too much in the middle section, the simpler the better. 
You don't really need a lot of extra information when reading the content
It doesn't feel as nice as the old version
Just in my opinion.

**Comment by zadam** [comment]
I added both of them to the center pane to make them more prominent since I consider them important. Of course I understand that in some cases it's better to maximize actual note content view (especially with smaller window), but then both attributes and similar notes are collapsible and when collapsed they take up almost no space.
