### ISSUE TITLE
When I import index.html Trilium will crash!

### ISSUE THREAD

**Issue by Rsose** [zadam/trilium#1261]
I accidentally imported the wrong file(Index.html) yesterday.
The Trilium Notes just crashed, causing the software to be unable to log back in.
It could be caused by an error INDEX.HTML.
Luckily I save my data to the cloud, otherwise I wouldn't be able to restore it again without the historical version of the data.Cos, the software wouldn't open at all.
You can try importing the following HTML file,Trilium Notes will crash

Attach index.html file
[index.zip](https://github.com/zadam/trilium/files/5263876/index.zip)

Suggestion:Can we put some mechanism in place to prevent these crashes from happening?

Waiting for a reply
Thanks

**Comment by zadam** [comment]
I'm going to rant a bit.

There's this in the issue template:

> For bug reports, **PLEASE mention version of Trilium you're using**

People either don't read it or just ignore that and proceed to remove the template text. I wonder what should I do that people start to include that critical piece of information.

You mention that the application crashes, but don't bother providing any further details. Screenshot of "crash" would be super helpful.

All this leads to me just having to guess those things - I spent time on trying to reproduce it on the current betas and wondering what could you mean by "crash" and only after a while it occurred to me that you could be using the latest stable version where I could finally reproduce it.

/ rant over

This is caused by import not sanitizing web pages and importing as is, inline JS can then "hijack" the application leading to this "crash". In 0.44 we sanitize imported HTML and thus there's no "crash".
