### ISSUE TITLE
How to recover login credentials?

### ISSUE THREAD

**Issue by eantropix** [zadam/trilium#1270]
I use self-hosted Trilium server on Docker, and after a computer restart, my username and password no longer work and I'm locked out of my notes, either because my login credentials no longer work, or I am using the wrong credentials.

As I don't use Trilium for its security, but its usability, I do not remember ever going out of my way to encrypt any of my notes.

Is there a way for me to recover my login credentials, or at least the files so I can transfer them to a new Trilium instance?

**Comment by zadam** [comment]
Hi, I wrote the following guide you can follow to recover your notes: https://github.com/zadam/trilium/wiki/Troubleshooting#forgotten-usernamepassword

**Comment by 1dnagy** [comment]
i have also run into being locked out without remembering what the password is.  nothing is protected but don't want to lose all my work.  followed these steps exactly, thank you.  but it is not working for me after a restart it wont accept password.  I am running latest stable built "2025-06-15"  has the db changed since this solution appreciate any help

**Comment by eliandoran** [comment]
Hi, @1dnagy ,

There is a chance that the password authentication mechanism has changed slightly.
Either way, you could bypass authentication by going to `config.ini` on the server and setting `noAuthentication` to `true`. Then restart the server and try to access the web interface, you should be back on track.

Afterwards, simply go to Settings and change the password from there and then revert the change to `config.ini`.

Also, which version are you running on? 2025-06-15 sounds old.
