### ISSUE TITLE
[Feature Request] Decouple Note Encryption From User Password

### ISSUE THREAD

**Issue by bonedaddy** [zadam/trilium#1295]
Right now note encryption uses the same password you use when logging into the application. If your user-level password is compromised, then encrypted notes are also compromised. It would be great if you could create a separate password for encrypting notes. 

~This could be extended to allowing multiple different passwords to be used for encryption, allowing the user to have certain notes protected by stronger passwords. Obviously this increases user-overhead to manage passwords, but with a password manager this is basically a moot point. Default to user-login derived password provides an easy default that is suitable for all users.~

**Comment by zadam** [comment]
I understand the point. This is mostly relevant only for the web app use since in desktop app you don't need to enter the password to enter the application.

So yes, I think separating the login and encryption password makes sense. But the second option with multiple passwords etc. seems rather like corner case / overengineering / difficult to use ...

**Comment by bonedaddy** [comment]
> So yes, I think separating the login and encryption password makes sense. But the second option with multiple passwords etc. seems rather like corner case / overengineering / difficult to use ...

Yea, perhaps I should remove this from the issue as it is indeed not really needed and a dedicated encryption key would be more than fine.
