### ISSUE TITLE
Add support of heading level 1 in Markdown

### ISSUE THREAD

**Issue by koutto** [zadam/trilium#1369]
Hello,
It would be great if Trilium supports Markdown heading 1.
```
This is a title
==========
```
Here, it supports headings 2 to 6.

Thanks

**Comment by cebas** [comment]
+1

importing from cherrytree, that supports H1, I had to replace all H1 with H2+strong in the exported html files to have the H1 titles somehow distinguishable from normal text

thanks

**Comment by zadam** [comment]
Hi, H1 is not allowed since note title is semantically H1. I fixed the import code to convert from H1 to H2, which is not perfect, but better than converting it to plain text.

**Comment by koutto** [comment]
Thanks a lot for your reactivity. This is a good workaround I think.

**Comment by cebas** [comment]
> Hi, H1 is not allowed in the note content since note title is semantically H1. I fixed the import code to convert from H1 to H2, which is not perfect, but better than converting it to plain text.

why don't you use <title> for the note title, and H1 for headings at level 1?
I think it can allow for more smooth imports/exports

**Comment by zadam** [comment]
\<title> is mostly invisible, not putting note title as H1 would hurt the readability way too much.

**Comment by cebas** [comment]
ok
thanks

**Comment by koutto** [comment]
Maybe an alternative would be to translate h1 to h2, h2 to h3, and so on. And finally h6 to <span class="h7">
By doing so, we could keep different level of headings when importing from other sources. And would make the process more smooth, without having to adjust manually title styles after import

**Comment by cebas** [comment]
> Maybe an alternative would be to translate h1 to h2, h2 to h3, and so on. And finally h6 to `<span class="h7">`
> By doing so, we could keep different level of headings when importing from other sources. And would make the process more smooth, without having to adjust manually title styles after import

+1

I has about to suggest the same idea.

**Comment by zadam** [comment]
Theoretically possible, but IMHO too complicated (there's some additional logic needed that this can be applied only in case there is at least one H1, but not H1 equal to the note title) for the expected benefit, therefore I prefer minimal fix ...

**Comment by meichthys** [comment]
I can cope with the minimal fix, but I did want to provide a use case that suffers from this minimal fix. 
I currently use Trilium to write draft blog posts for Wordpress. This works really well, however whenever i copy and paste the text from Trilium to Wordpress, i have to update all the headings up one level. Also, when copying from a Wordpress blog into Trillium, the headings are mangled. As an example, if I copy the following from a Wordpress blog, and paste it into Trilium, the Heading1 is removed an H2 remains - resulting in very poor readability of pasted markdown. I realize the fix for this is difficult, but I wanted to provide a use case for this issue.

<img width="823" alt="Screen Shot 2021-03-13 at 11 14 10 PM" src="https://user-images.githubusercontent.com/10717998/111056986-da065e80-8451-11eb-833e-1e6e996c79bc.png">


<img width="1140" alt="Screen Shot 2021-03-13 at 11 11 04 PM" src="https://user-images.githubusercontent.com/10717998/111056940-68c6ab80-8451-11eb-9fae-7e6e318ce89c.png">
