### ISSUE TITLE
[Feature Request] Play videos and audios inside trilium 

### ISSUE THREAD

**Issue by libantas** [zadam/trilium#1388]
It would be incredibly useful a built-in video-audio player in trilium. In that way one wouldn' t need to download the stored files.

**Comment by patrickjm** [comment]
Trilium can do this already with render notes. This is how I set up audio notes on my server (sorry if this is hard to read):

```
MyFolder/
> myAudio.mp3
    #originalFileName=myAudio.mp3 
    #customResourceProvider="audio/myAudio.mp3"
> Player (render note)
    ~renderNote=audioPlayer
> audioPlayer (type: HTML)
    contents:
      <audio controls>
        <source src="/custom/audio/myAudio.mp3" type="audio/mpeg">
      </audio>
```
A better solution would probably be to make a custom widget that you apply to the audio files you want, though.

**Comment by zDEFz** [comment]
@patrickjm this is helpful, I would love to see this in the Wiki.

**Comment by zDEFz** [comment]
Nevermind, I gave up, cause simply the work gotten too much!

I've used W3 Css templates. https://www.w3schools.com/code/tryit.asp?filename=GKFAVC9LHAF6

The issue was simply, normal tables were so much easier to create, todo this, is simply not feasible.

**Comment by patrickjm** [comment]
@zDEFz Would it work if you had a structure like this?

```
MyTextNote (embed MyFolder here)
MyFolder
>  VideoRenderNote1
>  VideoRenderNote2
```

Shouldn't the book note view automatically display the videos side by side?

**Comment by zDEFz** [comment]
> @zDEFz Would it work if you had a structure like this?
> 
> ```
> MyTextNote (embed MyFolder here)
> MyFolder
> >  VideoRenderNote1
> >  VideoRenderNote2
> ```
> 
> Shouldn't the book note view automatically display the videos side by side?

Yea sure does, but not with preview. Also, in the current version is a bug on MacOS, where if u click open from the Book View, it doesn't open it, instead it navigates to the node. But it got already fixed and will be pushed next release if I got this right.

**Comment by zDEFz** [comment]
Updating here - I currently run a small http server to circumvent the bug.

**Comment by patrickjm** [comment]
If it helps, Trilium has code notes for server sided code. I've never used them / don't know much about them, but could it make an endpoint to do what you needed the http server for?

**Comment by zDEFz** [comment]
> If it helps, Trilium has code notes for server sided code. I've never used them / don't know much about them, but could it make an endpoint to do what you needed the http server for?

I don't understand. Is Trilium able to run bash for starting up the http server or does it self-host it? Or something else?

**Comment by zadam** [comment]
Trilium can host files as a web server: https://github.com/zadam/trilium/wiki/Custom-request-handler#custom-resource-provider

**Comment by zDEFz** [comment]
@zadam I don't understand! If the file has the custrom-resource-provider tag, for instance the way I wrote in the Wiki:

> Note: The file that is supposed to be exposed needs to wear an "#customResourceProvider="fonts/myFont.woff" For >example, your file is in custom/fonts, you can call it via custom/fonts/myFont.woff But only if myFont.woff wears the >customRessourceProvider label. Otherwise, nothing would be found.

Then, the HTML5 media control wouldn't seek the video! It must be a valid address, path Regex seems to hurt!
**`http://localhost/[...]` does work but with path RegEx it wouldn't even seek. How to tell on what address it is reachable?**

**I repeat myself. When the file has the custom resource provider tag, it won't seek at all from the media control, since it's internal and has no `http://` before assumedly. #1395** 
```
<video  controls>
 <source src="custom/video/video.mp4" type="video/mp4">
</video>

```

Sorry for bolding, I'm not sure if you overread this priorly...

**Comment by zadam** [comment]
I have no idea why it does not seek, sorry.

**Comment by zDEFz** [comment]
@zadam Could you give me a guide on how to debug this? My assumption is that when you want to seek media, it wants another GET which it doesn't get.

Here is the debug log of the http server from the link I gave you. https://hastebin.com/odosoxisec.pl

**Comment by zadam** [comment]
I don't have any specific knowledge regarding these builtin media players.

**Comment by zDEFz** [comment]
@zadam where does this hosting functionality come from? If this is an `electron` functionality, it might be helpful to open an issue on the electron github page. 

If it's custom code, it might be an trilium issue.

I just need the mapping just right.

**Comment by zDEFz** [comment]
Add: Is servers fault.

[snip]
`As it turns out, looping (or any sort of seeking, for that matter) in <video> elements on Chrome only works if the video file was served up by a server that understands partial content requests. i.e. the server needs to honor requests that contain a "Range" header with a 206 "Partial Content" response. This is even the case if the video is small enough to be fully buffered by chrome, and no more server-round trips are made: if your server didn't honor chrome's Range request the first time, the video will not be loopable or seekable.`
[/snip]

**Comment by zDEFz** [comment]
Please close the issue, I create a new one with details @zadam
