### ISSUE TITLE
[Feature Request] Make templates inherit note type

### ISSUE THREAD

**Issue by Mangiola** [zadam/trilium#1475]
In my current setup, I have a need for a template to be a render note. However, templates only seem to inherit attributes and text content rather than the note type. All instances of this template are created as text notes irregardless of what the original type is.

I don't think that applying a template should immediately change the note type--rather, any notes created with the template already applied (using `~child:template`, for example) should have their type synced with the original.

If this is too specific, maybe a more general `#child:defaultNoteType` attribute would be better?

**Comment by zadam** [comment]
Hi, use case makes sense, I implemented a change so that instance notes will inherit type (and mime) just like the content.

> I don't think that applying a template should immediately change the note type

Logic is same as for content - if at the point of template relation assignment the note is empty, the type and mime will change. So this works also if you assign the relation after the note is created (but is still empty).
