### ISSUE TITLE
Cluttered 'Jump To' dialog

### ISSUE THREAD

**Issue by meichthys** [zadam/trilium#1488]
Version: 0.45.4

I'm not sure if this is a bug or intended functionality, but whenever I try to jump to a note, the results include a lot of tags:

![image](https://user-images.githubusercontent.com/10717998/102232166-ca13c880-3ebc-11eb-88e3-1462ee236144.png)

In the past (and in the [Wiki](https://raw.githubusercontent.com/wiki/zadam/trilium/gifs/jump-to.gif)) the 'Jump to Note' dialog is much cleaner (excludes all `externallink` tags).

If this is a feature, is there a way to turn it off? I loved the simplicity of seeing only page paths instead of so many 'externallink' tags that clutter the results.

**Comment by zadam** [comment]
Hi, there's multiple points here:

*   in the past trilium parsed all external links and created them as labels, but it turns out it really spams this dialog (and others) so this was disabled and does not happen anymore. However, old labels stayed. It would be possible to delete all of these external link labels with a simple script.
*   recently Jump To dialog searches also in atttributes which is the reason you see this and didn't in the past. With the exception of these "spam labels" I consider it to be a good thing. It's not possible to turn it off at the moment.
*   in upcoming version (0.46) search results are weighted and notes with hits in the title are prioritized higher, which should at least mitigate this issue ...

**Comment by meichthys** [comment]
@zadam Perfect. Thanks. I think my situation is your first bullet point. 
I'll try to figure out a script to remove those spam labels.

Also great news about the weighted results!

**Comment by wwwald** [comment]
@zadam: does the weighting also change the order for the "Create new note" item? 

With it being always on top right now, I frequently inadvertently create new notes while I intended to just link an existing one...

**Comment by zadam** [comment]
No, it doesn't. I understand the problem, but currently know how to fix this. Proposals are welcome.
