### ISSUE TITLE
Code font looks horrible on Dark/Black mode.

### ISSUE THREAD

**Issue by lflare** [zadam/trilium#1489]
![image](https://user-images.githubusercontent.com/22326991/102345027-b27d3280-3fd7-11eb-8657-45707b120105.png)
![image](https://user-images.githubusercontent.com/22326991/102345055-ba3cd700-3fd7-11eb-9dde-9913c9bbf3d7.png)
![image](https://user-images.githubusercontent.com/22326991/102345076-c032b800-3fd7-11eb-80ea-34142a7767e6.png)

I've attached the comparisons of the different themes affecting code notes. Since I particularly like the black theme, the code note font looks particularly jarring. Is this a CKEditor issue?

**Comment by lflare** [comment]
In comparison, a code snippet looks much much cleaner.

![image](https://user-images.githubusercontent.com/22326991/102345263-0c7df800-3fd8-11eb-9cbe-decab4da4323.png)

**Comment by zDEFz** [comment]
The theming functionality in Trilium is in general not very good, due to the fact that it's complicated.
You assume each component can have it's own style?

It's basically one HTML Page, AFAIK.
It would be neat, to just right click the area in layout mode and assign styles/fonts etc to it.

No more going to that weird assigning system anymore...

**Comment by lflare** [comment]
One more thing, it appears more apparent in the application than the website in Chrome.

**Comment by wwwald** [comment]
It's actually not _that_ hard to customize the font with some theming. See this [wiki section on "custom Css"](https://github.com/zadam/trilium/wiki/Themes#custom-css).

Steps to take:

- create a "code" type note, anywhere in the tree
- set it to "CSS" language
- give it a label "appCss", by entering `#appCss` in the attribute section
- insert CSS code in the note, to adjust the HTML elements involved. 
   - For code formatting in regular notes:
```css
code {
    font-family: Consolas !important;
}
```
   - for code formatting in "code" notes:
```css
.CodeMirror {
    font-family: Consolas !important;
}
```
 - refresh the Trilium interface with Ctrl+Shift+R

Your code should now show in the desired font (Consolas in the example).

**Comment by zDEFz** [comment]
@wwwald thank you for the help. But allegedly, with bigger css files, it doesn't apply to all. 

I have put downloaded https://www.w3schools.com/w3css/4/w3.css and put it into a own app css. It doesn't apply at all.
What happens if I use it in a render note however, that once I am on that particular rendernote, that includes this css file as a rel, Trilium will apply the css style.

Theres no way to apply it globally, it seems. And that back and forth is frustrating to me. Can you help?

**Comment by wwwald** [comment]
Trilium doesn't just replace all of its own CSS styling if you have any `#appCss` note anywhere. That's why I added the `!important` overrides in the font-family specification - these are needed to override a number of other font-family instructions introduced elsewhere.

Do you want to use the w3.css file to style Trilium? Because it mostly contains `.w3-*` classes that don't apply anyway?

**Comment by zDEFz** [comment]
Hey @wwwald 
I basically want all HTML files to inherit from the `.w3-*` css class but having the tree not changing font and font size.
For that, I tried to set the `.w3-*`css class as appCss, which didn't help.
Then I tried another appCss from templates found here everywhere and override the font and font size for all, so that they are always the same.
But once I'm on the rendernote, it's different again.

If I use any css that changes fonts within a HTML file from a renderNote, ALL is affected and the css theme doesn't get priority. I want one feel for all. Do you understand?
The tree should keep the same look, but the place where the note is displayed e.g HTML should be individual...

**Comment by zadam** [comment]
I changed the code note font to the default bootstrap declaration which is also used in the ckeditor's code block feature.
