### ISSUE TITLE
BUG: Today Note makes a copy of all 2019 notes

### ISSUE THREAD

**Issue by ttlequals0** [zadam/trilium#1491]
Server Version: 0.45.6
Client Version: 0.45.6
--

Recently when i click the "Today" button it takes a few minutes, then when it finally creates the "Today" it has all of 2019 notes under it. I have not changed any of the templates or attributes it just started happening after 0.45.5 updated and is still happening in 0.45.6.

* `/Users/[user]/Library/Application Support/trilium-data/log` for Mac OS
[trilium-2020-12-17.log.zip](https://github.com/zadam/trilium/files/5711464/trilium-2020-12-17.log.zip)

**Comment by zadam** [comment]
Hi, this is probably caused by new feature of deep duplicate which is also applied to the day notes.

I think what's happening is that you have a day template relation which points to 2019. Do you see something like that:

![](https://user-images.githubusercontent.com/617641/102540690-af557580-40af-11eb-98e0-35aac116ea72.png)

"Today" will then try to take that template and duplicate it as a day note causing the behavior you describe.

Having 2019 as a template does not make much sense, I recommend using a different note as a template or you can remove the template relation altogether if you don't use this templating ...

**Comment by ttlequals0** [comment]
Thank you for pointing me in the right direction. I did have a circular reference, which now has been removed and things seem to be working.
