### ISSUE TITLE
[Bug?] Trilium is getting stuck

### ISSUE THREAD

**Issue by libantas** [zadam/trilium#1500]
Trilium is getting stuck constantly.

Sometimes the freeze lasts longer than 10 seconds. It gets stuck specially when searching in the search bar and also when I navigate into a folder with many notes (imported articles with the trilium web clipper). It also tends to be slow when importing files (sometimes closing automatically).

I would like to know if more people has this issue and if it is going to be solve in a near future.

I have tried in two different computers the database and it gives me the same problem. It started giving troubles when I started adding more notes. So I am afraid that if I continue adding notes I will have a useless database.

I hope it has a solution since I have not found anything similar to this wonderful software.

My database is only 3.1gb.

Desktop version: 0.45.6 / 0.45.7
[trilium-2020-12-24.log](https://github.com/zadam/trilium/files/5740340/trilium-2020-12-24.log)

**Comment by zDEFz** [comment]
my database size is 10gb, still no problems. 
Trilium is not yet stable, so expect the unexpected.

**Comment by zadam** [comment]
Hi, I analyzed your logs and freezes seem to be related to searches - they usually take around 20 seconds which is clearly too much.

Since based on the stats in the log you have only a couple of thousands of notes, I expect that the problem lies in the fulltext search of large notes. I tried to recreate the problem by importing large notes and was able to identify particular pre-processing step which took a very long time when the text note was very large. I now added a condition to execute this step when note is too large which should mitigate (if not eliminate) the problem.

@zDEFz make sure you're on the latest version. In 0.45.6 (IIRC) there has been a big improvement in "thousands of notes in the same parent" scenario.
