### ISSUE TITLE
Lost websocket connection to the backend

### ISSUE THREAD

**Issue by funnisquares** [zadam/trilium#1520]
I'm trying to sync trillium client 45.7 to a fresh 45.7 server install. However I cannot conclude the setup. The console on the client side shows
```Lost websocket connection to the backend. If you keep having this issue repeatedly, you might want to check your reverse proxy (nginx, apache) configuration and allow/unblock WebSocket.```
every second or so.

[Client Log](https://github.com/zadam/trilium/files/5784837/trilium-2021-01-07.log)
[Server Log](https://github.com/zadam/trilium/files/5784899/trilium.log)

**Comment by zadam** [comment]
Hi,

> `Lost websocket connection to the backend. If you keep having this issue repeatedly, you might want to check your reverse proxy (nginx, apache) configuration and allow/unblock WebSocket.`

As the message says, you should check your proxy server config since it's probably blocking the WebSocket connection.

However, WebSocket should not be strictly necessary to finish the setup, I think it's another problem:

> 22:28:59.876 sync failed: Request to PUT  http://X.X.X.X:8080//api/sync/update failed, error: Error: net::ERR\_CONNECTION\_RESET  
> stack: Error: Request to PUT http://X.X.X.X:8080//api/sync/update failed, error: Error: net::ERR\_CONNECTION\_RESET  
>    at generateError (/opt/trilium-bin/resources/app.asar/src/services/request.js:174:12)  
>    at ClientRequest.\<anonymous> (/opt/trilium-bin/resources/app.asar/src/services/request.js:49:47)  
>    at ClientRequest.emit (events.js:223:5)  
>    at emitErrorNT (internal/streams/destroy.js:92:8)  
>    at processTicksAndRejections (internal/process/task\_queues.js:81:21)

Looks like there's some network issue since the server instance is not reachable.

**Comment by funnisquares** [comment]
I do not have a WebSocket setup. So it might be a network issue, however I don't know what the issue actually is. The server is hosted on google cloud, so I imagine the likelihood of its connection being a problem is very low. And the client is in my local network, but I haven't had any network problems recently, and I'd be likely to notice if I did have those problems when I'm playing games, streaming video etc.

Also when pinging the actual server from a terminal to problems are reported. I've been having these issues for several days now, and still have not been able to complete the setup. I think that the problem might be related to some of the file sizes, I have included in my notes some pdfs of books I own, and although they are not huge files ( < 50 MB) they are significantly bigger than any note.

**Comment by zadam** [comment]
> I have included in my notes some pdfs of books I own, and although they are not huge files ( \< 50 MB) they are significantly bigger than any note.

This actually sounds probable, since the request which fails is not the first one in the sync protocol - there's a handshake first which apparently succeeded.

So I think what is happening is that some proxy server between client and server is rejecting the request because it crosses over some configured size limit.
