### ISSUE TITLE
[Bug] Web-Browser only -  Files don't open with default application but download instead

### ISSUE THREAD

**Issue by zDEFz** [zadam/trilium#1529]
Ver 0.45.7
MacOS, Chrome latest

[log.zip](https://github.com/zadam/trilium/files/5794644/log.zip)

https://user-images.githubusercontent.com/24463722/104160527-93fd3200-53f1-11eb-81c5-b35dff159e56.mov

Hosted on Vultr VPS.

**Comment by wwwald** [comment]
I think this is a browser-level configuration, rather than a Trilium one.

Example to configure Chrome to directly open .docx files: [https://superuser.com/questions/1206815/configure-google-chrome-to-open-docx-files-in-microsoft-word-instead-of-just-do](https://superuser.com/questions/1206815/configure-google-chrome-to-open-docx-files-in-microsoft-word-instead-of-just-do)

**Comment by zDEFz** [comment]
Interesting. Does this mean, Trilium-Notes, which uses Chromium is configured this way by default?

Anyways, it's working this way and I close this issue with that.

**Comment by wwwald** [comment]
Trilium desktop version runs on Chromium - but this one runs server-based, so it's rendered in your regular browser, right?
I think the browser determines the link handling behavior in this case.
