### ISSUE TITLE
[Bug] macos: "menu -> learn more" opens electronjs.org in webbrowser

### ISSUE THREAD

**Issue by luclu** [zadam/trilium#1542]
`Version: 0.45.8`
`macOS: 10.15.7`

Clicking "menu -> learn more" opens electronjs.org in webbrowser.

**Comment by zadam** [comment]
Can you post the screenshot? That menu should not be there at all ... Thanks.

**Comment by luclu** [comment]
![Bildschirmfoto 2021-01-19 um 22 28 28](https://user-images.githubusercontent.com/10135872/105095275-bfdd7f00-5aa5-11eb-912a-4c568f2e1390.png)

**Comment by zadam** [comment]
Hi, so I think this is caused by you having activated "native title bar". If that's active then the app also displays a menu. According to electron/electron#1415 this is a mac limitation:

> Having an application menu is an requirement for normal desktop applications on OS X, so I'm closing this since it is basically impossible.

You can also completely ignore the menu, it's not intended to be shown and contains only default/dummy values.
