### ISSUE TITLE
[Bug] Internal Link opens on single-click instead of double-click

### ISSUE THREAD

**Issue by QuentinLeCaignec** [zadam/trilium#1555]
Version 0.45.8, on Kubuntu using the .deb release

I previously had to double-click to open links (as indicated by the documentation as well), now a double click opens a link which means I cannot select a link to remove or edit it.

**Comment by zadam** [comment]
Hi, this was an intentional change so I don't consider it as a bug. 

Since the default linking is now "reference link" (link title always mirrors target note title), it's not possible to edit these links. However selecting and deleting them is still possible with mouse.

**Comment by Grymas** [comment]
@zadam I see, thanks for your answer.
All of my current links are not reference links but internal hyperlinks (I select a text and add a link to it, which does not mirror the note title).
I currently cannot select this link and edit/remove it like I could previously.
I've found that a CTRL+Left Click opens the "edit/remove link" menu that I previous access to, but doing so also opens the link in another tab which is not ideal.

What is the intended way to select and edit/remove a internal link ? Deleting the text is not a good solution because that would take way too long. I will personally never use the reference link since the point is to discretely link notes in a wiki-style and my note titles are always more detailed/complete for a quick search (so they would be way too long as reference links). I currently have hundreds of internal links that are not mirrored titles, and I regularly need to remove or edit one, so the previous way of selecting a link was very convenient.

**Comment by zadam** [comment]
![](https://user-images.githubusercontent.com/617641/105358982-27571400-5bf7-11eb-8ea6-faf9928586ff.gif)

You can normally select/delete the link and edit it. The only different thing as far as I can see is that you can't click into the middle of the link ...

**Comment by Grymas** [comment]
Oh I see the confusion.
I mean editing/deleting the link itself without touching the text. I often have to remove or edit a link without removing or changing the text itself

**Comment by Grymas** [comment]
To be clear, I mean this menu :
![image](https://user-images.githubusercontent.com/12102823/105370318-c4b84500-5c03-11eb-96db-017464b68d74.png)

I understand that the new system makes more sense and I'll try to get used to it, but a quick click to remove the link without affecting the text is very convenient to me, a shortcut to make this appear without opening the link in another tab (as CTRL+click currently does in edit mode) would be enough.

**Comment by zadam** [comment]
OK, I understand if you want to unlink the text, but editing the link was never an option. I never liked this (CKEditor native) link dialog for internal links since the `#root/...` was far from intuitive.

I could add a new action "unlink" to the context menu:

![](https://user-images.githubusercontent.com/617641/105376092-a8b7a200-5c09-11eb-88aa-00d3e8c057f4.png)

**Comment by Grymas** [comment]
Agreed, the link edit was never very useful since the `#root..` link is not intuitive.

An additional option on a right-click context menu to Unlink would be perfect :ok_hand: 

Thanks for this amazingly useful app btw (could literally not find anything else that everything I wanted SO perfectly) and your responsiveness :)

**Comment by zadam** [comment]
So adding this to context menu is not as easy, however, there's an "remove format" button which also removes link:

![](https://user-images.githubusercontent.com/617641/105402970-60f44300-5c28-11eb-8b23-50ba4d0ce889.gif)

Would that also work for you?

**Comment by Grymas** [comment]
You're right, this can work for now. It's not as convenient as two clicks, and would remove things like bold or italic. You also need to select at least the whole link for it to work, which can sometimes be less convenient if you have multiple words as one link.

It is nitpicking at this point though, I think a way to gracefully unlink would make sense but if it's difficult to implement I totally understand.
