### ISSUE TITLE
[Enhancement] Optionally hide/display a link preview's full title and attributes

### ISSUE THREAD

**Issue by QuentinLeCaignec** [zadam/trilium#1558]
Version 0.45.8, on Kubuntu

I've noticed since the UI change to note previews when hovering on internal link that now the full note title (including the full hierarchy) as well as attributes are shown in the preview.
This has the effect of taking a lot of the preview space for long titles (very nested hierarchy) and when there are many attributes, leaving less space for the actual note content.

If this is intentional and useful, an option could be added to hide/display a note's full hierarchy+name and hide/display a note's attributes when showing a preview by hovering over a link.

Personal example where an almost empty note that I have not really filled yet (just an image) has half the link preview taken by the full path and attributes : 
![image](https://user-images.githubusercontent.com/12102823/105377623-49f32800-5c0b-11eb-9430-5649a2dec9f4.png)

**Comment by zadam** [comment]
Hi, I understand the concern. Making things optional / configurable brings considerable maintenance / testing burden so instead I'd rather do something that works for everybody.

I made following changes:

*   note title is made dominant, note path as less important information is smaller. The line is cut off if too long.
*   note attributes are limited to 2 lines maximum, then they are cut off

Example:

![](https://user-images.githubusercontent.com/617641/105409621-fc89b180-5c30-11eb-97e8-a33eae014716.png)

**Comment by Grymas** [comment]
Great solution, thank you.

Since i'm curious about the intent, is there a specific need or use-case in showing the attributes in the preview?
Everyone has a different vision of what this tool is supposed to be used for I suppose, but since I see it as a wiki-style note taking app, I'm not sure if showing attributes in preview is all that useful.

To me, it fills part of the space with unnecessary information that defeats the purpose of a wiki preview (hover, read the first paragraph of the note as a quick way of understanding, decide to click or not), and attributes feel like the sort of element that's always supposed to be behind-the-scenes EXCEPT for promoted attributes.

So I guess this is a wider question, what is the information that should be shown on previews, are attributes useful information at a glance or do they just make it harder to quickly parse, and should we show all attributes or only promoted ones (like the current UI for a note where all attributes except promoted ones are hidden at the top by default).

**Comment by zadam** [comment]
Many people use attributes as "normal" labels/tags for grouping purposes or whatever. Promoted attributes is something extra which takes some time to set up and not everybody uses.

I understand that the "technical" attributes visible in your screenshot don't provide a lot of value in a tooltip. As you mention we modify the logic to be consistent with the normal attribute presentation - if there are promoted attributes defined, then display only those and not "non-promoted".

Another heuristic could be to not display attributes inherited from template/ancestors since those are more likely to by "technical". Since tooltip is not meant to display complete information, I think it's OK to choose to display only some of them ...

**Comment by Grymas** [comment]
It's a difficult question for sure considering how many different ways people can use attributes for grouping or organizing.
I'm not sure what other solutions could be found other than using the existing promoted/inherited setting and choosing what to display based on that, anything else would require some option either for attributes (similar to the promoted checkmark) that you want to display/hide, or a general option to display/hide attributes on previews in general, app-wide.
But all of that, as you mentioned, would require additional features/options that would then need to be maintained.
