### ISSUE TITLE
Tree permanently disappears after extended use

### ISSUE THREAD

**Issue by TetraTsunami** [zadam/trilium#1621]
(This is my first time submitting an issue, please go easy on me!)

Server: Linux Docker/v0.45.8
Client: MacOS Firefox/Chrome
About two weeks ago (not immediately after any major update), I noticed that the tree menu was non-functional at all times. I was unable to make it appear at all. Here's what I saw:
![Screen Recording 2021-02-08 at 12 07 44 AM-Animated Image (Large)](https://user-images.githubusercontent.com/78718829/107182421-52d15100-69a2-11eb-8937-4e13d175a33b.gif)
I mention "extended use" in the title because I created this Trilium instance's database over a year ago, and have updated it consistently with each new release. It's about 12 megabytes in size, but much of that may be images. Deleting document.db and creating a new one causes the tree to work as expected. I did try the recent safe mode flag, but it didn't change anything.

Here are the logs and anonymized database.
[Trilium Issue.zip](https://github.com/zadam/trilium/files/5941671/Trilium.Issue.zip)

Again, apologies for any formatting errors, and please let me know if there are any more resources I can provide to help. In the meantime, any techniques to migrate my existing notes and metadata to a new database would be highly appreciated.

**Comment by zadam** [comment]
Hi, thank you for this bug report, I was able to quickly localize the problem using the anonymized database. I committed the code so that Trilium can recover itself from this problem in the future. But for now as quick fix do this:

1.  Press `ALT+O`, this will open SQL console
2.  Paste `update options set value = '20' where name = 'leftPaneWidth';`  and click on "Execute query"
3.  Restart Trilium

Now you should be able to click on the expand button and tree should show up normally.
