### ISSUE TITLE
[REGRESSION] `@in != noteId` has no replacement 

### ISSUE THREAD

**Issue by nil0x42** [zadam/trilium#1644]
Hi !
While migrating some of my saved searches to new Search operators, i found a regression:

The syntax from [old search](https://github.com/zadam/trilium/wiki/Old-search) had this feature:
> `@in!=VuvLpfAPx2L9` will filter notes which don't have note `VuvLpfAPx2L9` as their ancestor.

The new syntax (if i understood) would be:
`note.ancestors.noteId != VuvLpfAPx2L9`

But this one matches any note that has at least one path which don't have `VuvLpfAPx2L9` as their ancestors.

Is it possible to still have this feature in newer versions ?

Thank you !

**Comment by zadam** [comment]
Hi, this doesn't work because search algorithm is satisfied with "any match" - any ancestor can be non-equal which makes this query useless. It's not possible to express that such condition needs to be applied on all ancestors.

However, you can use negation operator to achieve the same:

```
# not(note.ancestors.noteId = VuvLpfAPx2L9)
```

Here the algorithm will find all the ancestors and negation will take the "set complement".

**Comment by nil0x42** [comment]
Great ! I saw the `Search` wiki page has been updated with mention of this feature. So i can close this issue.
Thank you !
