### ISSUE TITLE
[Bug]When I modify the template, a lot of sub-notes with the same name will be generated under the notes that reference the template attributes

### ISSUE THREAD

**Issue by Tlonglan** [zadam/trilium#1714]
Hi ~ I met a very serious problem recently, as described in the title. 

The first time I created the template and referenced it, there was no problem. But when I modified the content of the template, it would generate a lot of sub-notes with the same name  as the notes using the template(more than 3000), which would make the app unable to run immediately (unable to perform the next operation, such as clicking). I waited for a while and then the app could run. I tried to delete those sub-files or delete the template without success

The version of app that I'm using is 0.45.10 and the log has been upload. Hope you can see what's wrong, thank you ~

[trilium-2021-03-06.log](https://github.com/zadam/trilium/files/6095182/trilium-2021-03-06.log)

**Comment by zadam** [comment]
Hi, thank you for reporting this issue.

Based on the logs I believe that the problem lies in the fact that the template was ancestor of the "instance" note - this led to sort of infinite cycle. I've made some code changes to detect this situation and disable note copying in such cases.

It would be very helpful if you could [generate an anonymized database](https://github.com/zadam/trilium/wiki/Troubleshooting#anonymized-database) and post it here or to [zadam.apps@gmail.com](mailto:zadam.apps@gmail.com) 

With that I might be able to help you delete those extra notes.

**Comment by Tlonglan** [comment]
Thank you for your reply.
Through your explanation, I understand the inheritance properties of the template function. So this problem will be fixed in the next version, right?
In addition, yesterday I tried to delete the entire test notes (the template and those instance notes are sub-notes of the test notes), and I have successfully deleted those notes.

**Comment by zadam** [comment]
Yes, I added a check to prevent this recursive/infinite copying of template notes.
