### ISSUE TITLE
As microservices

### ISSUE THREAD

**Issue by danieldaeschle** [zadam/trilium#173]
What about splitting frontend and backend into different projects as microservices?

it would be awesome to have an extra backend which has a REST API.
Anyone can use its own frontend which communitcates with the backend.

It is just an idea what i have in my mind.

**Comment by zadam** [comment]
Well, technically frontend and backend are two separate applications which communicate via REST API.

But that REST API is private so we can change it easily without regards for compatibility with some external API clients. Making it public at this point serves no purpose (since there's no client) and we would tie ourselves with backwars compatibility guarantees.

**Comment by danieldaeschle** [comment]
Yes, there is no client yet. But if you would provide an API i would write my own frontend.

You have a little bit more work, but you also have better code and better software :)

**Comment by zadam** [comment]
While I'm not totally discounting the possibility of having different clients in the future, I think it's not the right time to do it.

Opening API prematurely would most certainly lead to worse code rather than better because you lose the ability to refactor interfaces (so they stay bad) because of the need to stay backwards compatible.
