### ISSUE TITLE
[Feature request] MacOS client can not logout/swith user acct

### ISSUE THREAD

**Issue by rickdgit** [zadam/trilium#1744]
I use docker to install a trilium instance on my nas. 
Then setup the sync with the trilium client on MacOS.

Then I accidentlly removed the trilium instance on nas.
I created the new instance afterward.

At this time, the trilium mac os client not able to sync with new instance 
` 400 with response {"message":"Sync login credentials are incorrect. It looks like you're trying to sync two different initialized documents which is not possible."}`

This make sense to me.
However Im not able to clean/log out from the Trilium mac client.

I have to uninstall the client and clean the data.

I'd like to request a feature that Im able to log out from the client side so I can login with new acct.

Thanks!

**Comment by zadam** [comment]
Hi, so as I understand you lost data on NAS, but you still have them on your local Mac desktop.

So what you would want to do is to sync the desktop notes onto NAS. To do that you should install new instance of Trilium on NAS but not initialize it (since that will create new document, new notes etc.). I guess that's where the issue comes from.

So I think the best way to approach this is to again wipe the NAS instance (or just delete the `trilium-data` directory) so that it's completely blank and then you can set up the sync.

**Comment by rickdgit** [comment]
So far I've wiped NAS instance as well as the Mac Trilium client information.
