### ISSUE TITLE
Database size shrunk

### ISSUE THREAD

**Issue by Engr-AllanG** [zadam/trilium#1754]
Server install 0.46.4-beta on ubuntu

I noticed today my database size seems to have shrunk from around 70mb to 7mb. I did not dig into this very far, I thought I'd ask if there was a change to something in 0.46 or even 0.45 that would account for this.

I'm not sure exactly when it shrunk either, I have a cron backup job that runs every night, and occasionally I look at the emails. I noticed today that it was much smaller than usual.

**Comment by Engr-AllanG** [comment]
Could this be it (from release notes)?
"DB refactorings, deleted entities are now truly deleted (besides trail in entity_changes)"

**Comment by zadam** [comment]
> Could this be it (from release notes)?

Probably not, the note talked about deleting metadata entities (content was deleted before too) so the effect of this change was probably not big enough.

More likely it has shrunk so much because of `VACUUM` command issued in one of the migrations (AFAIK SQLite file will never shrink itself without vacuuming)

**Comment by Engr-AllanG** [comment]
Ok, I see. I'll take a look at what the VACUUM command does. Thanks!
