### ISSUE TITLE
Tree pane too wide

### ISSUE THREAD

**Issue by Vaelek** [zadam/trilium#176]
I have a 4k monitor and the auto sizing of the tree pane gets annoyingly wide with lots of wasted space. Would be nice to set either a maximum or just let the user resize it manually and don't do it automatically.

**Comment by zadam** [comment]
You're right. This wasn't implemented because it's kind of difficult in CSS grid which is used for layout.

I added these options to control the left pane width - it's not perfect but you can e.g. set fixed width or how it's supposed to grow with the overall window size:

![image](https://user-images.githubusercontent.com/617641/45150799-fa903680-b1cc-11e8-9bcc-dfbbec4b7c7e.png)

This is now implemented in master and will be in the next release.
