### ISSUE TITLE
[Bug] Strange behaviour for protected notes titles 

### ISSUE THREAD

**Issue by U-Bren** [zadam/trilium#1810]
Hello,
Protected notes titles have a strange behaviour in version 0.46.6 on win10 x64 2004.
After entering a protected session, theirs titles still display "[Protected]", even after a frontend reload.

The note content displays normally, and titles are editable, however, if the title is modified, it will still be displayed after leaving the protected session, even after a frontend reload.

I originally thought that it was a upgrade issue, having just upgraded from 0.45.5, but since a full restart resets the (displayed) note title to "[Protected]", with the same behavior as describe above, I do think that this is a bug in the latest release.

[Log](https://github.com/zadam/trilium/files/6236555/trilium-2021-03-31.log) (please ignore sync issues)

Thank you for your time as well as for this incredibly useful software.

**Comment by zadam** [comment]
Hi, thanks for reporting these issues.

I can reproduce the issue that the titles are readable even after leaving protected session. This is a regression in 0.46.X. I will prepare a fix.

Unfortunately I can't reproduce seeing "\[Protected\]" after entering protected session. Does this happen everytime or randomly? BTW, do you use sync or just a single Trilium instance?

**Comment by U-Bren** [comment]
Hi, thanks for your quick answer.

The "[protected]" issue happens everytime. What's confusing is that while the title does not change even after entering protected session, it does become editable, as usual.

I do use sync, however I did not yet upgrade my server and decided to stop it before upgrading the windows app as to avoid any issue. Blanking the server instance address and restarting the app did not solve the issue.

Also, using a backup I tried to pinpoint the version from which the issue occurs, and can confirm that this behavior does not appear in v0.45.10. However, v0.46.0-beta is affected.

Please let me know if there is anything else I can do to help solve this issue.

**Comment by zadam** [comment]
Hi, thanks for the details.

Based on your description it seems to me that "\[Protected\]" is actually stored in the encrypted title, so the app now works correctly, it's "just" the data which is wrong :-/

I think it might have been caused by some early 0.46.X beta bug which did not load the decrypted title but allowed editing it so with any change it saved the "\[Protected\]" literal string.

This could be verified by checking note revisions of the affected notes (from where you might also recover the original titles).

> The document.db title column contain different (encrypted) values for each protected note. I do not know however if there is any salting or similar going on with protected notes' titles.

Yes, data is encrypted with random Initialization Vector so even if the clear text is same, cipher text will differ.

**Comment by U-Bren** [comment]
Hi,
> Based on your description it seems to me that "[Protected]" is actually stored in the encrypted title, so the app now works correctly, it's "just" the data which is wrong :-/

I suspected that, though even when I modify a protected note's title in 0.46.6 it reset it to "[protected]" after a restart.
Is the bug that you described perhaps still present in 0.46.6?
Also, I have directly upgraded from 0.45.5 to 0.46.6, so any version in between never touched my db.

> This could be verified by checking note revisions of the affected notes (from where you might also recover the original titles).

Yes, the original titles are available in the notes revisions (if only for notes that were edited since their creation). Losing the titles are not really an issue for me (I don't have that many protected notes), it's more the fact that I cannot correct them which is a bit annoying 🙂.

> Yes, data is encrypted with random Initialization Vector so even if the clear text is same, cipher text will differ.

Since the titles are not updated to "[protected]" when leaving the protected session, could the titles also not be updated when entering it? Is there a way to perhaps get the title of a (protected) note from the console to confirm that this is not just a display issue ?

**Comment by zadam** [comment]
So only now I looked at the logs you provided and noticed the decryption error with the stacktrace and I think I know (at least partly) what's going on.

The root of the problem is that there's one (or perhaps more) protected note which has corrupted title ciphertext. When you're entering the protected session, all the protected titles are getting decrypted. This process fails with one note, but this will stop the whole decryption, thus all other protected notes with non-corrupted text will not be decrypted and keep displaying "\[protected\]". But they will be editable and your changes to the title are written (encrypted) to the database.

I will fix this so that failure to decrypt single note will not stop other note titles from getting decrypted.

Now, why is the note's title corrupt? That's difficult to say. It's quite possible it's been corrupted like that for a while but up until now unnoticed. That's where the upgrade comes into play - 0.45 used different mechanism to load/decrypt data and specifically it did not decrypt all the protected notes, but always only a subset currently needed (currently expanded tree). So one note's corrupted title did not necessarily affect other notes display.

**Comment by U-Bren** [comment]
> The root of the problem is that there's one (or perhaps more) protected note which has corrupted title ciphertext. When you're entering the protected session, all the protected titles are getting decrypted. This process fails with one note, but this will stop the whole decryption, thus all other protected notes with non-corrupted text will not be decrypted and keep displaying "[protected]". But they will be editable and your changes to the title are written (encrypted) to the database.

That's interesting. I have changed every (or at least I think so) protected note's title, and the issue unfortunately persist. However, I noticed that 1 specific protected note title is displaying correctly (minus the fact that it is readable after leaving a protected session ofc).
This note was perhaps by coincidence the first protected note in the hierarchy as displayed by the tree widget (?) in the left pane, however after reordering the tree it seems that no matter where this note is placed it still displays correctly.

In what order if any are the note processed by the decryption code? Or is there any way to know which specific note is corrupted? 

> I will fix this so that failure to decrypt single note will not stop other note titles from getting decrypted.

If the above is not possible that is fine, I can wait until this fix.

> Now, why is the note's title corrupt? That's difficult to say. It's quite possible it's been corrupted like that for a while but up until now unnoticed. 

Could that be linked to a password reset? I don't think that I forgot to delete any protected note, but that's the only event outside of cosmic rays that I can think of :)

In any case, thanks for your quick and helpful answers.

**Comment by zadam** [comment]
Hi, please try 0.46.7. 

> That's interesting. I have changed every (or at least I think so) protected note's title, and the issue unfortunately persist. However, I noticed that 1 specific protected note title is displaying correctly (minus the fact that it is readable after leaving a protected session ofc).

This depended on the (random) order of notes being decrypted. Notes which were decrypted before the corrupted one should be visible, the ones in the queue after corrupted remained all \[protected\].

> Could that be linked to a password reset? I don't think that I forgot to delete any protected note, but that's the only event outside of cosmic rays that I can think of :)

If by "password reset" you mean just changing password then that shouldn't corrupt protected notes.

But if you did something similar to what's described [here](https://github.com/zadam/trilium/wiki/Troubleshooting#forgotten-usernamepassword) then yeah, this might explain the corrupted note.

**Comment by U-Bren** [comment]
Hi,
After upgrading to 0.46.7 every issue mentioned here was solved.

>But if you did something similar to what's described here then yeah, this might explain the corrupted note.

I meant exactly that. It turns out that I indeed did forgot to delete a protected note that I made while testing this feature when I discovered trilium 🤦‍♂️.

Thank you again for your kind support as well as your detailed explanations.
