### ISSUE TITLE
Can't seem to get sync server working

### ISSUE THREAD

**Issue by wigneyliam** [zadam/trilium#183]
Hey I'm using the docker image and upon running I get a note saying "DB not initialized, please visit setup page to initialize Trilium."

If I then try to sync test from another computer I get an error saying "DB schema does not exist, can't sync.".

The problem is that I can't see anywhere on the setup page that tells me where to initialize trilium. I tried running export-schema.sh and dump.sh to see if they'd help but I know very little about sql or databases so I've got no idea.

Thanks for this awesome piece of software though!

**Comment by zadam** [comment]
Hello, so just get on the same page - I assume you followed instructions on https://github.com/zadam/trilium/wiki/Synchronization

You ran docker image, and "If I then try to sync test from another computer" I assume you went to your "desktop" instance Options -> Sync, changed sync host to point to your docker image host and clicked on "Test sync"? Unfortunately that's not the correct button (I know this is probably confusing) - this one is used to test sync after it has been already setup. Correct button to click to setup the sync is "Sync local document to the server instance".

I'm thinking of merging these two buttons together to make this clearer since their purpose is similar but they each work only in specific situations.

I'm happy somebody is testing synchronization, if you keep having problems I'm glad to help.

**Comment by jnsday** [comment]
if you do the order like wiki:
sudo docker run -t -i -p 8080:8080 -v ~/trilium-data:/root/trilium-data zadam/trilium:latest
you will get the error message, "DB not initialized, please visit setup page to initialize Trilium"
just do the next...
docker run -t -d -i -p 9019:8080 -v ~/trilium-data:/root/trilium-data zadam/trilium
