### ISSUE TITLE
Switching tabs now loses cursor/scroll position

### ISSUE THREAD

**Issue by ThomasWeber** [zadam/trilium#1836]
In the past, in a long note, you could switch tabs then return, and your cursor and scroll position would be right where you left them.

It seems this was broken somewhere I think between 0.45.7.0 and 0.46.6.0. Now if you make an edit on one tab, switch tabs and return, the cursor position is lost and the note will be scrolled to a random other point in the note (I haven't been able to tell a pattern, just a random other spot, though occasionally the top or bottom). I use tables pretty heavily, but I tested and it appears this happens with plain text as well. This can be very disorienting when working across multiple tabs.

Thanks!

**Comment by zadam** [comment]
Hi, thanks for reporting this. You're right, I can reproduce this behavior on 0.46.X as you write.

But I also tested the master (future 0.47) and the bug is not there - scrolling position is kept when switching between tabs. There was a refactoring of scrolling handling (for different reasons) in both 0.46 and 0.47 so this does not surprise me. Given it's relatively minor bug I will not probably try to backport the fix from master to 0.46. First beta of 0.47 is coming in a few days too ...

**Comment by ThomasWeber** [comment]
Sounds great, I agree, please don't spend the effort to backfix when it'll already be fixed in a future version. I can wait for that.
Thank you!
