### ISSUE TITLE
How do I turn on edit mode?Could you please set the shortcut key of editing mode?

### ISSUE THREAD

**Issue by MCX-gtf** [zadam/trilium#1858]
For bug reports, **PLEASE mention version of Trilium you're using** and also include **log files** from following location:

* `/home/[user]/.local/share/trilium-data/log` for Linux
* `C:\Users\[user]\AppData\Roaming\trilium-data\log` for Windows Vista and up
* `/Users/[user]/Library/Application Support/trilium-data/log` for Mac OS

**Comment by zadam** [comment]
Hi, normally notes are editable by default. Only very large notes are "auto read only" and you must enable edit mode manually but there isn't a way to do it with a keyboard shortcut.

**Comment by MCX-gtf** [comment]
But can you change the edit mode to a preference instead of placing it at the top of the article?

**Comment by zadam** [comment]
Not sure what you mean but the button to enter edit mode is fixed to the top.

This feature (read only) is actually not intended to be used very often so there isn't that much focus on its configurability ...

**Comment by MCX-gtf** [comment]
OK, thank you for your reply, but I would like to ask how to cancel the read-only mode?

**Comment by zadam** [comment]
For a particular note you can add a `autoReadOnlyDisabled` label which will prevent auto read only.

If you put this label on a root note and make it inheritable then it will apply to all notes.

But in general I would advise to break up your notes so that they are not long enough to trigger the auto read only. This feature is there mainly because the editing component (CKEditor) gets slow with longer notes ...

**Comment by MCX-gtf** [comment]
OK, thanks for your reply

**Comment by martinkoutecky** [comment]
@zadam I understand why read-only mode is not turned off by default. I realized what would be helpful for me is if the edit button also had a button next to it saying "Disable read-only for this note in the future?" which would add the `autoReadOnlyDisabled` label to the note (so that I don't have to remember it or dig for it...).

**Comment by unsungNovelty** [comment]
@zadam - Yeah this would've been a great thing to have. I have to manually click on the button every single time. Mostly have to scroll to the top cos it is after scrolling down a lot that I realise I have to edit the note. It would be great if there is a way I `autoReadOnlyDisabled` by default for all the notes. Or even better, a keyboard shortcut for `autoReadOnlyDisabled`.

Appreciate Trilium notes. Thanks a lot for your effort.

**Comment by martinkoutecky** [comment]
@unsungNovelty Actually disabling globally is easy as described above -- make `autoReadOnlyDisabled` an inherited attribute of a root node.

**Comment by unsungNovelty** [comment]
@martinkoutecky  Thanks a lot for the info. This actually solves my issue.

**Comment by squarepupil** [comment]
I forgot where the edit button was on a long note and could not find it for the life of me. Had to come to this issue thread to realize that it was at the top of the document, which is a unintuitive place to look for it when you're trying to add to the end of a long one. If it were part of the static UI, up next to or part of the "note actions" dropdown, I think that'd be a good place for it.

**Comment by zadam** [comment]
@squarepupil I agree, I moved the button next to "note actions", that way it will be always visible.
