### ISSUE TITLE
Feature request: Calendar (auto generate blank notes for the future)

### ISSUE THREAD

**Issue by sigaloid** [zadam/trilium#1859]
It would be nice if there was a script or feature to create blank day notes for the next month. I rarely add a note for a future event because the current-day keyboard shortcut does not work. 

No fancy GUI or calendar icon, just generating blank notes for the next X days. Thanks for this amazing software!

**Comment by zadam** [comment]
Hi, it's a valid request and something like this occurred to me already ... But did you know about that you can just click on the calendar widget for future dates and if they don't exist, they will be created?

![image](https://user-images.githubusercontent.com/617641/115140579-3e5fa380-a038-11eb-8a7a-aac08ae03bfd.png)

> I rarely add a note for a future event because the **current-day keyboard shortcut does not work.**

So I just tedted it, and it might be because of the conflict with another functionality. You might want to change the default `alt-t` in "Scripts\Today` to something else, then it should work.

**Comment by sigaloid** [comment]
>But did you know about that you can just click on the calendar widget for future dates and if they don't exist, they will be created?

No, I have never noticed the calendar widget before! :flushed: Thanks, closing!
