### ISSUE TITLE
Feature request: Mobile/Desktop toggle button

### ISSUE THREAD

**Issue by surajsharma** [zadam/trilium#1889]
I need to switch a lot between mobile and desktop views, currently this is only possible by logging out and logging back in on the mobile device. If there was a link to facilitate that, it would be unique and useful.

The current 'switch to mobile view' link works only one way if i'm not mistaken.

**Comment by andrejdam** [comment]
+1

**Comment by agentydragon** [comment]
I just came upon the same issue. I clicked in the mobile frontend to the "switch to desktop" button, because I wanted to use some feature that isn't in mobile, but now can't go back. I suspect clearing cookies might help, but I couldn't figure out how to clear cookies for just one website on Chrome for Android :(

**Comment by finzzz** [comment]
I'm using this app for workaround.
https://github.com/tobykurien/webapps

**Comment by zadam** [comment]
Added:

![image](https://user-images.githubusercontent.com/617641/139591855-b526a16d-6b84-4694-b304-b979b0642134.png)
