### ISSUE TITLE
The Windows version of this program cannot run on AMD-based CPUs

### ISSUE THREAD

**Issue by M1sIft** [zadam/trilium#1906]
The Windows version of this program cannot run on AMD-based CPUs

**Comment by zadam** [comment]
Hi, any details on this? Trilium should have no issue running on AMD x64 CPUs ...

**Comment by MCX-gtf** [comment]
The program clicked on my Lenovo R7 5800H AMD x64 CPU and didn't respond, I don't know why

**Comment by MCX-gtf** [comment]
I have tested it and found that version 0.46.9.0 works, but the latest version 0.47.2.0 doesn't

**Comment by zadam** [comment]
Could you run the application from the command line - i.e. open `cmd.exe`, navigate to the directory and run `trilium.exe` ... perhaps it will show some error there ...

**Comment by ChrisFab16** [comment]
Same problem. 
Example output from cmd prompt:

C:\Program Files\trilium-windows-x64>trilium.exe 
C:\Program Files\trilium-windows-x64>
DB not initialized, please visit setup page
DB size: 4 KB

**Comment by chee** [comment]
I have an AMD cpu. Ryzen 7 Pro 4750U.
I've just installed Windows to test this.

I downloaded `trilium-windows-x64-0.47.2.zip`, extracted it, double-clicked `trilium.exe`, synced with my server and edited a note.
I don't know what the bug is, but it is not happening on my AMD cpu.

**Comment by bwat47** [comment]
Ryzen 3700x here and trilium 0.47.2.0 works without issue

**Comment by ChrisFab16** [comment]
> 
> 
> Same problem.
> Example output from cmd prompt:
> 
> C:\Program Files\trilium-windows-x64>trilium.exe
> C:\Program Files\trilium-windows-x64>
> DB not initialized, please visit setup page
> DB size: 4 KB

I verified that the problem is still there after restart of the PC.
v0.46.9 release works fine

**Comment by zadam** [comment]
@ChrisFab16 thanks. No error, just doesn't startup. 0.47 release has upgraded electron version which is probably the most likely candidate for the source of the problem. For now keep using 0.46.9 and hopefully this will get fixed.

**Comment by bwat47** [comment]
I'm actually seeing the same issue on my laptop (but it works fine on my desktop).

I don't think it's related to AMD cpus, because the machine where it's not working has an intel tigerlake CPU (whereas the machine where it _does_ work has an AMD cpu).

On my laptop, I see the same behavior as OP, where 0.46.9 works without issue, but 0.47.3 will not launch (and no error message is given when launching it from cmd prompt).

There is an error in the windows event viewer, but it seems really vague:

![image](https://user-images.githubusercontent.com/1442520/118495963-b2ea3880-b6f1-11eb-943b-061fb93560ee.png)
