### ISSUE TITLE
Internal links in electron attempt to open in browser

### ISSUE THREAD

**Issue by adavier** [zadam/trilium#191]
Reproduce:
Ver 0.22.1
Electron Windows 10
Create link html link to another note. 
Click on link and click on link in popup
![image](https://user-images.githubusercontent.com/30839200/46371230-b5eaa480-c67f-11e8-860e-7f37621cd374.png)
Link opened in browser, and Unauthorized 401 is received

**Comment by zadam** [comment]
Hello, thank you for the report. This has been fixed in master and should be released soon.

Unfortunately UI here isn't very good as I believe this link editing dialog should not be opened for internal note links at all (internal links shouldn't be edited manually).

BTW, it's possible to open links in the editor also by double clicking them.

**Comment by zadam** [comment]
Fix released in 0.23.0
