### ISSUE TITLE
mac desktop can not sync

### ISSUE THREAD

**Issue by mymilkbottles** [zadam/trilium#1919]
run mac desktop can not sync.

version v0.47.2  
server use docker version 0.47.2

![image](https://user-images.githubusercontent.com/19325380/117302399-27c9a100-aeae-11eb-8d3b-257a0ca53d0d.png)

![image](https://user-images.githubusercontent.com/19325380/117302480-42037f00-aeae-11eb-9ddc-d43883f4e374.png)

![image](https://user-images.githubusercontent.com/19325380/117302584-62333e00-aeae-11eb-9130-4e178215d624.png)

**Sync server handshake has been successful, sync has been started.**

![image](https://user-images.githubusercontent.com/19325380/117302628-6d866980-aeae-11eb-810e-2ce365697a86.png)

**Comment by zadam** [comment]
Hi, I remember two possible causes:

1) sessions are not saved correctly on the server because of e.g. write permissions or insufficient space. But this should actually not happen with docker ...
2) there was some network proxy in between which was stripping / messing up with session headers. Unfortunately this is pretty difficult to debug ...

**Comment by mymilkbottles** [comment]
> Hi, I remember two possible causes:
> 
> 1. sessions are not saved correctly on the server because of e.g. write permissions or insufficient space. But this should actually not happen with docker ...
> 2. there was some network proxy in between which was stripping / messing up with session headers. Unfortunately this is pretty difficult to debug ...

I found network proxy maybe no problem, because I use Proxyman found first request(url: /api/sync/changed) is ok, but second request(url: /api/sync/changed) failed.

![image](https://user-images.githubusercontent.com/19325380/117389720-6186c000-af1f-11eb-9ca5-95d49022cf65.png)

![image](https://user-images.githubusercontent.com/19325380/117389866-a7438880-af1f-11eb-8c7b-3b291f4fb32a.png)

**Comment by mymilkbottles** [comment]
I guest this is bug. second request cookie header has no sid field, so server response http 401.


![image](https://user-images.githubusercontent.com/19325380/117396800-5044b000-af2d-11eb-8554-093d04ab9b9d.png)

![image](https://user-images.githubusercontent.com/19325380/117396914-8d10a700-af2d-11eb-8a98-cf543dd05f05.png)

**Comment by zadam** [comment]
Hi, good detective work. The problem is already in the first request:

![image](https://user-images.githubusercontent.com/617641/117493089-c91a2b00-af72-11eb-84e1-070ea4679f0c.png)

The request succeeds, but the `set-cookie` in the response has no `trilium.sid` which causes the next request to fail. Server responds with this cookie, it must be lost along the way, usually by some proxy server.
