### ISSUE TITLE
Consistent issues with themes

### ISSUE THREAD

**Issue by 6-AND-9** [zadam/trilium#1941]
Trilium version 0.46.7. OS: Linux, Ubuntu-based. Attached LOG file below.

[trilium-2021-05-13.log](https://github.com/zadam/trilium/files/6472338/trilium-2021-05-13.log)

So basically the issue is that I can't use themes almost at all. For example, I tried using Allure-night. I made a new CSS note, pasted the content, added the #appTheme tag, and restarted Trilium / reset the UI. Then I went to select the theme in Menu -> Options, but nothing changes. Tried CTRL + R again after selecting the theme, nothing changes. The standard white theme remains.

![image](https://user-images.githubusercontent.com/51234066/118123771-052b1100-b3f5-11eb-953f-91eaedcb5247.png)

The same or similar things happened with other themes i.e. Material-dark, Dark-plus etc. Sometimes some artefacts remain from other themes. For example, the theme / zoom factor / font size etc. selection drop-down boxes sometimes remain black even in a white theme, and they are difficult to work with. The relationship map sometimes is weirded out (check the screenshot below, on Allure-night theme):

![image](https://user-images.githubusercontent.com/51234066/118124163-808cc280-b3f5-11eb-946c-9b4593975d25.png)

What am I doing wrong here?

Regards,
- A

**Comment by ydam24** [comment]
Same issue,I add all fonts required in css file but still not working.
Any solution?

**Comment by zadam** [comment]
Hi. I don't regularly test 3rd party themes but I assume the problem is:

1) themes are not correctly written - most importantly all CSS declarations need to be prefixed with theme selector, e.g. `.theme-dark`
2) themes like Allure go way beyond the official "theme API" and depend on things like internal CSS classes, page structure / ordering etc. The advantage is that you can theme the app pretty heavily, the disadvantage is that it can break from release to release as the internal implementation (which is not part of the theme API contract) changes.
