### ISSUE TITLE
Internal link to a section of a note

### ISSUE THREAD

**Issue by renyuneyun** [zadam/trilium#1948]
It seems trilium is unable to link to a particular **section** of a note. Whether through the @ syntax or the dialog, I tried to type something like `another_note#section_a`, but all it allows is to create a note named `another_note#section_a`.

I'm aware notes can have `#` in their titles, so how about providing a separate field in the *create internal link* dialog for such purpose?

**Comment by zadam** [comment]
Hi, linking to note sections is not supported and there isn't an immediate plan to support this. Trilium works best when used with many smaller notes instead of smaller number of longer notes.

**Comment by ivosm** [comment]
I agree with @zadam  that it is better to have more shorter notes but having this tool would be helpful in some cases. 
As an example, try imagine the process where the short note grows piece by piece in the time and then you decide to cut a part of it. And as a result part of the links are bad, because of they target to the old note and not to the new one created from part of the old one. So an action taking few seconds has to be followed by checking all relations and links and rewriting part of them. In case of internal links, it could be done by an easy script.
On the other hand, I don't think, its necessary to change the DB structure and to make search and navigation more complex but use them only in a context of a currently opened note.

**Comment by zadam** [comment]
Closing in favor of #1021
