### ISSUE TITLE
How do I delete a cloned tree?

### ISSUE THREAD

**Issue by gerroon** [zadam/trilium#2004]
Hi

I created a cloned note tree for easy asccess. Now I do not need the clone how do I delete a  clone without deleting the actual note tree that sits inside under a top  note?

thanks

**Comment by Nriver** [comment]
As far as I can tell, cloned notes (with * after the name) are free to delete, the sub-notes will still under the original note or other clones after the clone is deleted.

But, as I always say, BACK UP before you think you may do something wrong.

**Comment by zadam** [comment]
Yes, note is deleted only once the last clone is deleted. Since 0.47 there's useful delete overview which will show you what will be done:

![image](https://user-images.githubusercontent.com/617641/121406653-b5d9f100-c95e-11eb-8259-4304c8db3b9b.png)

So if you see this, it's safe to delete since only the clone will be removed, all notes / content will stay.
