### ISSUE TITLE
VPN Stop sync

### ISSUE THREAD

**Issue by 9812ga98sd** [zadam/trilium#2055]
For bug reports, **PLEASE mention version of Trilium you're using** and also include **log files** from following location:

* `/home/[user]/.local/share/trilium-data/log` for Linux
* `C:\Users\[user]\AppData\Roaming\trilium-data\log` for Windows Vista and up
* `/Users/[user]/Library/Application Support/trilium-data/log` for Mac OS

Windows , Trilium 0.47.5

When enabling a VPN the local sync stops working to the server instance.

**Comment by zadam** [comment]
Hi, network problems with VPN are common (not just in Trilium but with other apps as well). Seeing client log would be helpful.

One of the common issues is that VPN intercepts all traffic and overrides certs with their own (MITM) which are then not recognized by trilium. In that case run `trilium-no-cert-check.bat` instead of `trilium.exe` which will disable cert checking.

**Comment by xmeadow** [comment]
Also make sure that the port you are using to sync is not blocked in the network you are connecting to.
