### ISSUE TITLE
[Bug] v0.47.6 can't run because the module 'better-sqlite3' cannot be found

### ISSUE THREAD

**Issue by linger98** [zadam/trilium#2117]
windows11 
Trilium 0.47.6

![image](https://user-images.githubusercontent.com/73106094/130338747-e1fcfce3-a0b6-44d3-b376-c7fb284a78d1.png)

**Comment by gerroon** [comment]
I have the same problem on Windows 10

**Comment by ArtisticZhao** [comment]
Same on Win10

**Comment by metaphorsource** [comment]
same on ubuntu20.04

**Comment by WantToLearnJapanese** [comment]
No issues related to the module 'better-sqlite3' on the server version with the provided Dockerfile.

**Comment by TheWiresharkGuy** [comment]
Same on Win10 (installed via scoop extra bucket)

**Comment by imfms** [comment]
same on win10

**Comment by zadam** [comment]
Sorry about that, something went wrong with the build process. Releasing 0.47.7 right now which should fix it.

**Comment by Waxwood** [comment]
I'm having the same problem with 0.47.6 in Manjaro. I usually start Trilium with this command in terminal because the installation package for Manjaro is seldom updated. I unzip the package trilium-linux-x64-0.47.6.tar.xz into my Trilium directory and run this command in terminal: TRILIUM_START_NOTE_ID=root TRILIUM_DATA_DIR=/home/ray1/.local/share/trilium-data /home/ray1/trilium/trilium-linux-x64/trilium

Today it yielded this error message:

$ TRILIUM_START_NOTE_ID=root TRILIUM_DATA_DIR=/home/ray1/.local/share/trilium-data /home/ray1/trilium/trilium-linux-x64/trilium
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'better-sqlite3'
Require stack:
- /home/ray1/trilium/trilium-linux-x64/resources/app.asar/src/services/sql.js
- /home/ray1/trilium/trilium-linux-x64/resources/app.asar/src/services/sql_init.js
- /home/ray1/trilium/trilium-linux-x64/resources/app.asar/electron.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:887:15)
    at Function.n._resolveFilename (electron/js2c/browser_init.js:257:1128)
    at Module._load (internal/modules/cjs/loader.js:732:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/ray1/trilium/trilium-linux-x64/resources/app.asar/src/services/sql.js:8:18)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)

(trilium:3298): Gtk-WARNING **: 15:59:16.511: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version

**Comment by ecodiv** [comment]
Would it be possible to have besides the source code of 0.47.7 the executables for the different platforms?

**Comment by zadam** [comment]
@ecodiv done.

**Comment by ecodiv** [comment]
Great!  Thanks!

**Comment by wwwald** [comment]
@linger98 Best to close this issue?
