### ISSUE TITLE
submit form in render note

### ISSUE THREAD

**Issue by Nriver** [zadam/trilium#2156]
I am trying to make a render note with a simple form with Trilium 0.47.5
```html
<!DOCTYPE html>
<html>
<body>

<h2>HTML Form</h2>

<form action="/eat">
  <label for="food">food</label><br>
  <input type="text" id="food" name="food" value="noodles"><br>
  <input type="submit" value="Submit">
</form> 

</body>
</html>
```

The submit button works with Trilium server in Chrome, but doesn't work in desktop client. What can I do to make the submit working?

**Comment by zadam** [comment]
Hmm, form submit inside Trilium would mean unloading of the application and redirecting to the action address. I think that there's some protection against doing that since that seems counterproductive.

If you just want to send some data somewhere than I would handle the submit event in JavaScript, e.g.:

```
$("form#id").on("submit", () => { ...
       .... read inputs and send them with AJAX
});
```

**Comment by Nriver** [comment]
Ok, I get it.
