### ISSUE TITLE
Feature-Request: Saving Images on Server

### ISSUE THREAD

**Issue by MassiveStorage** [zadam/trilium#234]
it would be great to have images saved on the server no matter if they are from the web, or from local harddrive.
At the moment, they are always referenced from the web instead of the server thats running trilium.
I find that better for a couple of reasons:
1. not all servers encrypt their traffic via ssl at the moment.
2. if the image gets deleted the information is also lost in the notebook

It would be good, to have the image on the trilium server, and just for referencing aspects include the link to the original image in the notebook in a popup-menu like it is made with the "side-image" "full-size image" options.

**Comment by zadam** [comment]
Hello, I assume you copy & pasted the image from the web browser. This is unfortunately beyond our control - we just paste whatever is in the clipboard. It's a known limitation that browsers don't copy the image into the clipboard, only the reference to it.

Otherwise Trilium can store images "server side" just fine as either image (with compression) or as a note attachment (no compression). Some details are here: https://github.com/zadam/trilium/wiki/Images

Workaround for you would be to first save the image from the web to filesystem and then save it to Trilium.

**Comment by tsinhi** [comment]
> This is unfortunately beyond our control - we just paste whatever is in the clipboard.
@zadam ,I don't think so, after we paste, it's possible to  analyze the html source code. If we find <img src=http://www.foo./1.jpg> label, we can download this img backgroud to  local storage finally, change the lable to <img src=1. jpg>.

**Comment by MassiveStorage** [comment]
@tsinhi a while ago when i had this software installed i found out, this actually only happens when you drag and drop from a browser window into a note. if you right click on the picture you want and click copy picture, trillium actually copies the whole image on it's local storage. Just not use drag and drop.

**Comment by tsinhi** [comment]
> if you right click on the picture you want and click copy picture, trillium actually copies the whole image on it's local storage. Just not use drag and drop.

@MassiveStorage I have a try,unfortunately，trillium also not load image to local storage.Are u sure that?you can check it by NoteSource.

**Comment by MassiveStorage** [comment]
@tsinhi Yes I am sure. As long as i did copied the picture to the clipboard and not the actual link to the picture it was hosted by my server. don't know if anything changed scince december. scince then i use bookstack because trilium was unreliable.
