### ISSUE TITLE
(Bug report) Custom css can not overwrite style.css

### ISSUE THREAD

**Issue by ymj0424** [zadam/trilium#2355]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/zadam/trilium/issues) for a bug report that matches the one I want to file, without success.

### Trilium Version

0.48.5

### What operating system are you using?

Other Linux

### What is your setup?

Server access only

### Operating System Version

CentOS 7.9

### Expected Behavior

According to the wiki [https://github.com/zadam/trilium/wiki/Themes](https://github.com/zadam/trilium/wiki/Themes), I created a code note with CSS type, and put the "appCss" label on it. 
Here's the content of my code note:
```
.ck-content code {
    margin: 0 0.3em;
    border-radius: 5px;
    font-size: 100%;
}
```
**The `border-radius` of inline code should be 5px.**

### Actual Behavior

The `border-radius` of inline code still used the setting in style.css which is 2px.
![image](https://user-images.githubusercontent.com/22889888/142587355-8731e355-9211-4c7a-8b47-f1df9e8f676e.png)

### Additional Information

The browser I used is Chrome 96.0.4664.45.

**Comment by zadam** [comment]
Hi, standard CSS precedence/specificity rules apply. Just create a more specific selector (often even prepending `body` works) or use `!important`.

**Comment by olsonpm** [comment]
Hi - I'm really enjoying this note application.  Mind expanding on the reason for keeping this as-is ?  To me it seems people will intuitively expect their custom theme to override the existing css.  For example if someone wants to override a certain rule the workflow would be

1. copy the existing selector
2. replace it with the value you want

but this workflow doesn't work because the default css is loaded after our custom one.

I'm willing to work on a PR should this feature be accepted

**Comment by zadam** [comment]
You shouldn't rely on the order of CSS being loaded. Just use more specific selector or `!important`.

**Comment by olsonpm** [comment]
> You shouldn't rely on the order of CSS being loaded.

I think there are plenty of cases where the order of CSS being loaded is deliberate e.g. normalize and reset css, but I respect your opinion
