### ISSUE TITLE
ENEX Format not recognized

### ISSUE THREAD

**Issue by meyer-roessl** [zadam/trilium#241]
When Importing ENEX files (right-click on node, import into node), the following error message ist displayed after selecting the ENEX file: 

Import error: unrecognized extension .enex, must be .tar or .opml

screenshot:
![grafik](https://user-images.githubusercontent.com/6620474/48984642-9b243180-f0fe-11e8-91b4-e8ccf822faad.png)

App version:  0.23.1
Build date:  2018-10-25T18:13:37+02:00
0c007566ad31a98ad585fa97435fc9306ec0a3c8

Or have I done something wrong?

**Comment by zadam** [comment]
Hello, ENEX import is available only in 0.24 which is currently in beta - https://github.com/zadam/trilium/releases You can try it, it's pretty stable.

I apologize for this confusion - the problem is that documentation doesn't use branching so the docs and the actual version is not in sync at the moment.

**Comment by meyer-roessl** [comment]
Hi, I can confirm it works in 0.24. :-) There are some html converting issues ( there is a 'lang="de" style="font-family:Calibri;font-size:11.0pt">' at the beginning of every note, seems somewhere is the '<' lost), however since I converted from OneNote -> Evernote -> ENEX, I first need to make sure it does not come from this previous convertions. Closing this issue.

**Comment by zadam** [comment]
I would really appreciate if you could send me a sample of the ENEX file which produced this conversion error so I can fix the issue. The problem with ENEX is that there isn't many samples around on the net so it's difficult to test it.

Since it's an XML file, you can open in a text editor and just copy paste some snippet which contains the "lang="de" style="font-family:Calibri;font-size:11.0pt">"

**Comment by meyer-roessl** [comment]
Hi,

 

I created some test pages. Since I am usind OneNote (and not Evernote), I also included the OneNote source files. I used Evernote to import OneNote and export to ENEX. Not sure whether the attachments will go though, if not please advise where I can put the testfiles.

 

Hope that helps.

 

Thanks,

 

- Reiner
