### ISSUE TITLE
Can trilium save each note as separate text/md files instead of being stored in a database?

### ISSUE THREAD

**Issue by Weej1** [zadam/trilium#244]
The best example of my question would be QownNotes which saves each note as a separate text file in a directory. I like the look of Trilium but as someone who frequently switches from Qownnotes created notes to other MD apps (like Typora) to export each files as a pdf I need the flexibility that a txt file provides.

**Comment by zadam** [comment]
Trilium can export & import markdown notes (or whole directory structure in tar archive), but that would be pretty tiring to keep exporting & importing while switching applications so I'm afraid what you'd like to do isn't really practical with Trilium.

The reason why Trilium uses database instead of file structure is that filesystem isn't powerful enough for features I want (mainly [cloning](https://github.com/zadam/trilium/wiki/Cloning-notes)).

**Comment by jdorel** [comment]
Sorry to necropost, but would it be possible to list the features that couldn't be implemented through a filesystem ?
Because for what you call `cloning`, it could be implemented through links (hardlink or symlink)
My usage would be the same as @Weej1, except for the face that I edit my notes through a text editor and navigate my notes through the filesystem, making the content readable even if Trilium is innaccessible and facilitating sync through external tools (such as syncthing).

Love what you've done with this tool

**Comment by zadam** [comment]
There's now FAQ entry going into details:

https://github.com/zadam/trilium/wiki/FAQ#why-database-instead-of-flat-files

> Because for what you call `cloning`, it could be implemented through links (hardlink or symlink)

Equivalent of "cloning" would be "directory hard link" but unfortunately nothing like that exists. Hardlinks just for files don't cut it.

**Comment by jdorel** [comment]
Sorry I missed that (I was searching for text file, not flat files :confused:). Thanks for the quick reply

**Comment by zadam** [comment]
@deajan it's possible to export note subtrees with [ETAPI](https://github.com/zadam/trilium/wiki/ETAPI) 

https://github.com/zadam/trilium/blob/master/src/etapi/etapi.openapi.yaml#L262

**Comment by sottey** [comment]
@meichthys it isn't super straightfoward, but it would be possible to have a script in Trilium which periodically gathers up and exports specific notes.

So I would see the solution as:
1) Periodically, The script exports certain notes to a zip file on computer A
2) Computer A has a filewatcher which sees when a new zip file is there
3) Computer A sends the file (FTP, rsync, etc.) to computer B (or not even a computer, possibly a nextcloud instance)
4) nextcloud soehow automates unzipping the file.

Like I said, setting it up might be a pain, but it is certainly possible.

**Comment by deajan** [comment]
@meichthys To be honest, I never got time for this.
To improve the ideas of @sottey , I'd write the following

A Python (or other language) script installed on the nextcloud server that is run via crontab (or apscheduler if run as deamon).
That script will connect to the ETAPI of the trilium server (using requests module).
It must then use `/notes/{noteId}/export` to export the root (or other note) as zip file.
The tricky part is finding {noteId} of the root note (can be done in GUI, but there must be an api way to do so).
From there, python has a zip module that can uncompress the zip into a nextcloud user's dir.
Once everything is in place, python will launch `php occ files-scan <user>` (using command_runner module) to force Nextcloud to detect the new files.

The culprit is that it's not a sync, but a one way copy. Every modification done in nextcloud will be lost on next sync window.
Doing two sides sync is way harder (trust me) and is probably not what you'd want.

The above work is a couple of hours / a day work in order to have a solid script.
Would love to do this, but that's not a high priority for me.
