### ISSUE TITLE
(Feature request) Auto-refresh on web access

### ISSUE THREAD

**Issue by hofaeair** [zadam/trilium#2442]
### Preflight Checklist

- [x] I have searched the [issue tracker](https://www.github.com/zadam/trilium/issues) for a feature request that matches the one I want to file, without success.

### Describe feature

The server version of the page cannot be refreshed automatically when the page is accessed. You have to refresh the page manually whether you add a new page or hide the sidebar.
Sometimes the fear of not having autosave and not being able to refresh instantly makes the server version very inconvenient to use. It can almost only be used as a backup tool.

**Comment by zadam** [comment]
Hi, this is most probably because your webserver/proxy is configured to block WebSocket which is used to refresh state of the application. Many users had this problem.

Normally there isn't a big difference between the web version and desktop version and you definitely shouldn't have to manually refresh the application.

**Comment by hofaeair** [comment]
By adding to the proxy：
```
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection "upgrade";
```
Already solved my problem.
Thank you for your help!
