### ISSUE TITLE
RFC: Usability issues

### ISSUE THREAD

**Issue by zadam** [zadam/trilium#2483]
Hi, in the next iteration(s) I would like to start addressing usability problems and I would like to ask you for help in identifying them:

* what do you find unnecessarily cumbersome / complicated?
* what do you consider confusing/unclear?
* what were your biggest problems when trying out Trilium for the first time?

On the other hand, this is not a place to ask for new features.

Some examples:

* some users report the confusion about having to create a user account for a purely desktop application and then never using the username (and potentially password either).
* the initial "Trilium Demo" content available after the installation:
  * some people are surprised there is some "garbage" instead of just empty application
  * it is surprising that deleting example content removes some functionality (today button, task manager)
* application has to be updated manually (which is both feature request but also a valid usability issue IMHO)

Thanks!

**Comment by sigaloid** [comment]
Occasionally I find searching to be confusing, as there are three different search fields: the jump menu, the quick search, and the full search page. I do understand the reasoning for each of them, though, and for the most part it doesn't really matter which you use if you're searching by title.

**Comment by jobidon** [comment]
I just installed Trilium for the first time earlier today. so I think I qualify as a newb :)
Here are some questions and impressions about the software so far. Hopefully that help in the context of this thread. Otherwise, please let me know if there's a group (telegram?) where I can get those resolved as well.

So far, I think trilium is a very powerful platform, but I find I'm still having a hard time figuring out how to do stuff. Sure, adding simple notes, creating hierarchies, changing icons and copying notes is pretty straightforward, but I wish the tutorial would walk me through the steps for more advanced concepts. I did find a few animated GIFs for some of those features, but certainly not all that I am trying to do. For instance:
- How to make a folder be a "journal" where I can create daily notes? I couldn't figure it out, so I have simply hijacked the one from the initial sample DB. I did noticed a few custom attributes, but it's not clear how I would create a new one. Also, if I manage to create a new one, should I re-run the 'today' script in the new hierarchy to get a new calendar star icon connected to the new journal root? Still not clear on that.
- I wanted to create a relationship graphs to represent my local LAN with PCs and routers, etc. I managed to create a 'connectsTo' relationship and added a bunch of nodes which I could then connect together. Then I realized that it would have been nice to create a template so I could specify IP address, credentials, etc for each node. I looked at the 'book template' and created my own, but the template wasn't applied to the existing nodes. So I deleted a few entries and recreated them and still the template fields didn't show up. A tut certainly would be useful to walk me through this
- For tasks, I'm not sure if I want to create task elements on a daily note, or create them under the task manager and assign a date to them. What are the pros and cons of either approaches?
- I am also trying to create recurring tasks (annual birthdays, periodic dentist appointments, etc) and haven't figured out how to tackle this. is there a resource on this somewhere?
- Is there a way to make tasks roll-over to the next day if they haven't been completed? I see that tasks created in the task manager can have a due date and they will show up on the appropriate day, but not sure if they will show up on my daily note tomorrow if I don't get around to them today.
- I would like to create a simple dashboard with an account balance I can retrieve using a 3rd party API. I understand I can get a script to be triggered daily or hourly to retrieve data, but I don't know where/how to create that, yet.
- I wanted to create a recipe list and for each recipe, have a template which would have 5 sections: metadata (# servings, cooking time, labels, rating, etc), a few images, a list of ingredients in a table, a list of steps (numbered), and a comments/note section. Can a template dictate the format of a node, or is it mostly for attributes? So again, a tutorial on templates would be very useful.
Again, let me know if this is the right place for this type of feedback, or if there's a group better suited for this and I can submit more of my progress if it's useful.
thanks!

**Comment by zadam** [comment]
@jobidon thanks for the feedback, I think it fits here, however answering it doesn't. It would be good to post here to [discussions](https://github.com/zadam/trilium/discussions) to get some answers. Since there are many questions in your post, it might make sense to split them into several separate discussions.

**Comment by angstr0m** [comment]
I installed Trilium yesterday for the first time while evaluating all kinds of note taking tools. Trilium is the best one imho.

I was very pleased with the usability and the feature set. Especially the note editor is really nice to use (from writing markdown to defining internal links).

I was also very pleasantly surprised with the advanced search function. However the lack of a find and replace function really took me by surprise: 
https://github.com/zadam/trilium/issues/1955

I understand that this is a non trivial feature request. The milestone of ckeditor5 mentioned in the issue (https://github.com/ckeditor/ckeditor5/milestone/47) is closed, so I assume ckeditor5 now supports find and replace (https://github.com/ckeditor/ckeditor5/tree/master/packages/ckeditor5-find-and-replace).

I would love to see find and replace implemented. Other than that I'm very happy with Trilium so far :).

**Comment by zadam** [comment]
There is actually find & replace in text editor, but it is a bit hidden: 
![image](https://user-images.githubusercontent.com/617641/147888880-99099811-cb61-4e4a-b043-a0a49082e24f.png)

Source editing in CKEditor 5 is very new and still experimental.

Since these are rather support/feature requests, consider continuing this conversation in a separate issue (if needed).

**Comment by Nriver** [comment]
I would suggest that the built-in demo "Trilium Demo" could be updated.

As I did in the Chinese translation release, I add some more contents and reorganize the demo notes into a more hierarchical way. And the note-tree structure is exactly what I am using everyday, so it would be more practical to get started with the demo.



root
├──note
    ├──most important
----temp folder
----note templates
----diary
----books
--knowledge base

![ksnip_20220105-171602](https://user-images.githubusercontent.com/6752679/148192541-3e30c9f6-ea10-4b02-8622-cdfb1c6c117a.png)

Oh, yes, add some icon for the notes, they make the note look much better.

Add some warning text like "do not mess around unless you know what you are doing" in special functional notes "today", "diary", etc. Add wiki links in the notes for more info if the user really want to change or play with it.

However, sometimes people do not want to read wiki, they prefer a working demo in at hand. Therefore, I also put some example/useful skills for beginners in the demo. Like how to trigger note link, usage of commonly used note tags, some simple search queries, etc.

I also put some demo scripts in the demo. Like this [message of the day (MOTD)](https://github.com/Nriver/trilium-translation/blob/main/demo-cn/%E7%A4%BA%E4%BE%8B%E7%AC%94%E8%AE%B0/Trilium%20%E6%89%A9%E5%B1%95/Trilium%20%E8%84%9A%E6%9C%AC%20script/startup%20%E5%90%AF%E5%8A%A8%E9%A1%B9/startup%20message%20%E5%90%AF%E5%8A%A8%E4%BF%A1%E6%81%AF.js), which is really simple, but shows what trilium can do with script codes easily.

For advanced useage like custom request handlers, some working examples in the built-in demo can make a big difference! At least for me, I did struggled a while to get the handlers working even with the wiki docs.

**Comment by btgould** [comment]
The one significant thing that I think is really difficult to use on Trilium is the single line input on TeX markup. I like to include lots of math in my notes, and often will want to put several lines inside a `\begin{align*} \end{align*}` environment (e.g. to show a full derivation of some equation). 
It would be nice if it would allow us to input multiple lines. Maybe you could press "Shift+Enter" to get another input line just so that the source TeX looks a little nicer. My current workaround is to write it initially on another TeX renderer, and then copy paste into Trilium so that I don't have to scroll back and forth on one monolithic line every time I decide I want to tweak how I wrote something. 

Also, this is bordering on a feature request, but the ability to reorder lines with a keyboard shortcut (many apps use "Alt+Up / Down") would make it a lot easier to type things like lists in stream of consciousness and then quickly organize them in a sensible manner when you're done. I think it's the one thing I would really like to add to the input system in general.

**Comment by Igorgro** [comment]
I found a bug that the button "insert paragraph before" of the first block is covered by the toolbar
![image](https://user-images.githubusercontent.com/22894169/148681148-bbcd7c85-540d-4bff-8c9a-5ff091311749.png)

**Comment by thfrei** [comment]
1) Search

> Occasionally I find searching to be confusing, as there are three different search fields: the jump menu, the quick search, and the full search page. I do understand the reasoning for each of them, though, and for the most part it doesn't really matter which you use if you're searching by title.

Me too, I struggle most with the search. Since I am coming from Onenote, there is one place to search, Ctrl+E. 

![2022-01-09 16_15_22-](https://user-images.githubusercontent.com/7283497/148688780-a710c1cf-3945-44d9-8723-4da6c7c0d00b.jpg)

Maybe one could have a combination of at least title and full-text for the jump-menu?
Trilium also seams to search not just by title, but by tags and attributes as well (which is confusing) in the jump:

![grafik](https://user-images.githubusercontent.com/7283497/148688818-f43030b5-2799-4772-923d-d7feee4c1327.png)

And when I then hit <Ctrl-Enter> to initiate full text search, I would expect that the search starts immediatly, which it does not, and then I am presented with an empty result and get confused.

2) When I started using trilium, I struggled with the long tree and creating "empty notes" for a hierarchical structure. Not sure how to work around this one. Onenote solves this, by creating "notebooks" on a higher level, and then the tree moves one pane to the right: 

![2022-01-09 16_35_54-Test ‎- OneNote for Windows 10](https://user-images.githubusercontent.com/7283497/148689303-c9fed998-89ee-4ce3-8311-2ed7d33cad47.jpg)

Workspaces seem to go into that direction, which I like very much.

@zadam Thank you for your time and keep up the great work!

**Comment by zadam** [comment]
@thfrei Hi, thanks for the feedback.

"Jump To" is supposed to be as fast as possible (can search while typing) so it can use only in-memory data model which also means it can't search through note content.

> And when I then hit to initiate full text search, I would expect that the search starts immediatly, which it does not,

Do you mean that you need to press enter on the "Quick search" and that it doesn't search as you type?

This is mostly for performance reasons since that search does look through content so it can be slow.

> When I started using trilium, I struggled with the long tree and creating "empty notes" for a hierarchical structure.

In essence, I would like to keep Trilium free-form and unopinionated, but I also understand the concern here. Workspace is an attempt for tackle this, as you recognized but I'm also open to other ideas.

**Comment by thfrei** [comment]
> Do you mean that you need to press enter on the "Quick search" and that it doesn't search as you type?

![grafik](https://user-images.githubusercontent.com/7283497/148729819-f43b0467-1130-49d1-978d-4daab51c05f1.png)

When I am in the jump menu, as seen in the screenshot above, it has two ways going forward:
- Jump by hitting enter, or clicking on the note title (which is not really indicated, this might be a UX issue - I would expect "Jump" button at bottom right, and full text maybe next to it)
- Go to full text search hitting Ctrl+Enter. This brings me to full text search, and I would expect the search to start immediatly, or rather show me the result, since it says, do full text search. 
  - Sidenote: I also see now that full text search brings you out of the hoisted space with no indication, while quick search gives you an indication that you leave your hoisted space.

PS: The clear button in the jump menu might also not really be necessary, imho. Nobody clicks clear or reset on forms? :-)
PPS: I actually never use quick search. I guess it comes from being used to IDEs like Webstorm or Visual Code where you have this "awesomebar" feature (VSCode Ctrl+p). The jump reminds me of this. Maybe we could look into this?

**Comment by thfrei** [comment]
> In essence, I would like to keep Trilium free-form and unopinionated, but I also understand the concern here. Workspace is an attempt for tackle this, as you recognized but I'm also open to other ideas.

My initial idea was, that maybe we can create another layer purely visual by using some css and notes attributes. So if the note has these attributes, it gets added to this column. 

A little bit more opinionated, we could show all workspaces by default in a separate column. This effectively would introduce a structure. And then user defined below.

![grafik](https://user-images.githubusercontent.com/7283497/148739049-2ea4809f-f35e-4eb1-a4ab-8b85c49718bf.png)

**Comment by U-Bren** [comment]
I think that having more actions apply to all selected notes might prove useful.
As an example, it is quite painful currently to change the note icon, add a label, or add a the same branch prefix to let's say 20 notes.

**Comment by rubaboo** [comment]
> What about splitting the "Trilium Demo" note into a Root-level "Meta" or "Extensions" note that would have all the important, don't-delete-this stuff and only keep the examples themself in the "Trilium Demo" note?

#352 and #1036 are asking the same.

**Comment by chncho** [comment]
Thank you for developing this software. There is some point in relation map note:
1. Hope it can link one exists note, not only among his child.
2. Hope the line can chose arrow direction, not only two arrows.
3. Hope the tag on the line can be left empty .
![2022-01-21_17-35](https://user-images.githubusercontent.com/6135686/150503992-25215731-6816-408e-b955-7580d42a8d6c.png)

**Comment by zadam** [comment]
1) You can link any note. Just drag it from the tree.
2) Sure, that's the default behavior. There are two arrows since in this particular map, there are actually 2 relations (e.g. Charles -> Diana and Diana -> Charles)
3) This visualizes relations and relations must have a name. So it can't be empty.

**Comment by chncho** [comment]
> 1. You can link any note. Just drag it from the tree.
> 2. Sure, that's the default behavior. There are two arrows since in this particular map, there are actually 2 relations (e.g. Charles -> Diana and Diana -> Charles)
> 3. This visualizes relations and relations must have a name. So it can't be empty.

Thanks.
1. As I have a lot of notes, find the target note is very difficult, so if there is a way to add it quickly, it is very usefull.

**Comment by chncho** [comment]
Can the search input box be bigger? Some times the input field is not enough. May be can change it to be a textarea.

![2022-01-24_09-42](https://user-images.githubusercontent.com/6135686/150709190-6b50e3ff-8adb-426c-8c91-f4a5b162cca2.png)

**Comment by cwilliams5** [comment]
Zadam I got a whole list of feedback I've been building. Some of these probably fall into "usability" issues you are after here. I don't know if you want individual issues or what, please let me know whats best for you. Also this is constructive feedback as requested, I obviously love Trilium. 

To start, here is a partial issue list of my feedback that is usability adjacent:

- Mermaid diagrams need Zoom and Pan. It's hard to make anything but a small diagram. The zoom, pan, and reset controls  (and the way the note remembers previous view) from relationship maps are probably a great fit here.
- when i tab off an attribute after using keyboard/type to select one it should auto fill. currently requires ENTER. if ive down arrowed to something and tabbed enter should not be necessary. see: location/tag in to do system
- CTRL + Click and Shift + Click in the note tree does not work as expected. I expect I can click a note, shift click a note elsewhere, and select all in between. I expect ctrl click to add selections 1 by 1. Shift works like control does in every other application ever made, and ctrl is an open in new tab feature (I see desirability but im trying to select things).
- Related to above, if multiple tree items are selected, I cannot drag and drop them together. If I right click menu -> move they move together, but i just want to drag and drop one and have all selected follow.
- Relationship maps and displayRelations. Okay I can set just the relations I want to display. But by doing so, any new relations made are automatically excluded. I want the opposite, I want hideRelations, so I can specify a few I want hidden, and yet any new ones are auto included. 
- Mobile client missing lots of features (I know this is known, but its still a thing).
- Sorting
          - Auto Sort. Sorting a subtree is a one time event. I want an option to keep it sorted, where all new subnotes are autosorted. Perhaps an attribute that can go on a note? #AutoSort:title,ascending
          - Sort Option: Subtrees first. _Sometimes_, I want to be able to sort like files in windows. By this I mean, if I sort a folders contents in Windows, it looks like this: Folders(A-Z) then Files(A-Z). There are some times in Trilium that I would want to sort an entire subtree in a similar way: NotesWithChildren(A-Z) then NotesWithoutChildren(A-Z). Of course I only want this sometimes, and sometimes I would want this to autosort too. #AutoSort:title,ascending,subtreefirst
- I miss being able to email onenote/evernote
          - Obviously the way those systems work is out of scope for Trilium
          - But perhaps there is another creative way, like a label in my gmail that is an imap folder, then Trilium can scrape the imap folder and mark things as read. gmail filter for myemail+trilium@gmail.com to move emails into the label 
          - then could show up in a dedicated inbound email note in app the way clips do
- Web Clipper Stuff
          - Firefox extension should be in extension store where it can auto update
          - Repo claims Save selected text option, not present. Would be very nice. Save link with note is close, but it should auto capture what I have highlighted maybe
          - Can clip a screenshot, but need option to capture whole page as screenshot like Onenote does
          - Capture page is really bad at a lot of sites, need a better algorithm for extracting page contents
- Task Manager needs work
          - I understand this is "scripts showcase" and not a fully developed feature.
          - However, personally I believe To Do is a very important part of an application like this.
          - I haven't spent a ton of time thinking on this, but overall the Task Manager is clunky.
          - There are cool parts, like my journal getting clones of tasks on due or completed dates
          - On the other hand, it frustrates. Creating tasks pulls me out of my place in the hierarchy. I want a more flexible hierarchy then just tag and location, and those can be pretty awkward to work with anyway. Maybe I want tasks to both live inside and outside notes? I don't know. I'll have to think more. Whatever the optimal system may be, this isn't it.

**Comment by cwilliams5** [comment]
>     Related to above, if multiple tree items are selected, I cannot drag and drop them together. If I right click menu -> move they move together, but i just want to drag and drop one and have all selected follow.

I'm going through and creating bugs/feature requests for those of the above that are specific enough to do so. Anyway, I went to make a FR for this part and....I can't recreate this. So either I was mistaken or doing who knows what, or zadam slipped a silent fix for this in the last release or two. Either way - this is no longer relevant.

**Comment by cwilliams5** [comment]
>     * Mobile client missing lots of features (I know this is known, but its still a thing).
> 
@zadam What is the scope of the mobile client? What feedback is requested? I'm creating issues/feature requests for the things above, and I'm not sure what feedback to give you on the mobile client. The functionality its missing is obvious and I'm sure its not adding value to report it. I want to add value for you. So I'm curious what the actual intended score/coverage of the mobile client is, and what level of feedback from it you would be interested in.

**Comment by zadam** [comment]
Mobile client is not expected to provide full feature set, only some vague "basic" functionality. User should be able to read/edit/delete notes, but not much else.

**Comment by antoniotejada** [comment]
I spent a couple of days using Trilium, but with enough depth to delve into the bowels of CKEditor5 and write a Trilium ToC widget plugin (see https://github.com/zadam/trilium/issues/533#issuecomment-1101628763).

First of all thanks for creating it and making it available @zadam! 

There are a few things I like a lot (see Pros below) and from the few I've tried is the closest to what I want, unfortunately the current showstoppers below make it hard for me to commit to it (Unotes and Joplin seem to be the runner ups).

Usability issues
----------------

### Pros:

*   Being able to add markdown codes that get automatically translated to WYSIWYG
*   Uses html under the covers, so dearly missing markdown features are available: colspan in tables, centered or side by side images, etc
*   Automatic revisions
*   Manual resizing of images
*   Spell-checking
*   Multi-language spell checking
*   Plugin with frontend and backend support, it's possible you could write generic node.js server code as a backend plugin and run them in the exiting node.js backend server.
*   shift+i debugging for development of plugins

### Showstoppers

*   Useless ctrl+f function
    *   When you ctrl+f and then ESC, the keyboard focus ends up in the note (you can scroll up and down) but other keys are ignored and the note is not editable, you have to click on the note to bring it back and be able to keep editing.
    *   When you ctrl+f , enter a search word and press return, all the occurrences are highlighted as expected, but pressing return again doesn't go to the next occurrence until you click on the next arrow. Sometimes, but not always, once you click the next arrow you can press return and it will go to the next occurrence.
    *   Repeatedly pressing ctrl+f brings more and more overlapped search boxes.
    *   After quitting the ctrl+f search box, sometimes it returns to a mode where return is the only key that gets inserted into the note, all the other keys are ignored, you need to focus away and back to fix it.
*   No shortcut for search/replace in the text editor
*   No search/replace in the code editor (this can be worked around by using the external editor).
*   If you swipe scroll with the trackpad and shortly after you press ctrl, looks like ctrl captures the tail of the swipe (even if it's no longer scrolling because it hit the end) which causes the app to zoom in/out.

### Bugs/Annoyances

*   “Editable mode” behavior extremely annoying, all notes should be editable by default no matter the size, had to find out how to disable it by setting a huge non-editable threshold.
*   ctrl+s linked to search, had to disable it too due to muscle memory.
*   hard to tell where the keyboard focus is, in the tree or in the note
*   No syntax-highlighting for code blocks in the text note editor
*   Open externally for html invokes the browser instead of letting you choose eg vscode
    *   Save to a non .html  extension (thtml?) so you can select how to open them. Note Microsoft Edge shows uknown extensions as text, so this could be a configuration option so it's saved with html if you want to open with browser or not.
*   HOME/END keys in a wrapped line in the code editor don't take you to the start of this wrap, they take you to the start/end of the whole line. This is contrary to the note editor and to eg vscode.
*   In the text editor, when writing a code block having to search for the code language instead of taking it from the string after the backtick

### Missing features

*   table of content
*   code editor
    *   80-column guide
    *   spell-checking
    *   intellisense
    *   Go to line

**Comment by meichthys** [comment]
On mobile I noticed that if the note is too large, you can't edit it at all in the mobile interface. On the desktop client you can click a button to make it editable, but that option is not available in the mobile view.

**Comment by yllekz** [comment]
Also encountering the issue where a note over a certain size is unable to be edited in mobile view. I think it's because in normal view, a "large" note is locked until you press the "edit" icon, but in mobile view, there is no "edit" icon to be found anywhere, and thus lies the problem. The workaround is to switch to the desktop view on the mobile device but it's not a good user experience because the UI is tiny on a phone.

**Comment by meichthys** [comment]
Some notes require the user to click the Pencil (Edit this Note) icon before editing. This is a slight usability issue, but it becomes even more frustrating when I forget (even though I use the app regularly) to click the pencil and am confused why I cannot edit. 

I see two potential fixes:
- Ideally we wouldn't need to click the button at all, but I'm assuming there's a performance/back-end reason that this is not already the default.
- Alternatively, the "Edit this Note" button, when required, should be very prominent or obvious. Perhaps a different color for the button and/or adding text next to the button to make it stand out more. Something else I've seen in other UIs is that the button will have a one time vibrate effect when the page is opened so it catches the user's eye.

**Comment by zadam** [comment]
@yllekz @meichthys master (future 0.58) has somewhat reworked UI and now contains the edit button.

I also added a shake effect (button also temporarily gets bigger) to make it more noticeable.

Feel free to keep discussing this issue here, but for new topics please open a separate issue. I'm going to close this one.
