### ISSUE TITLE
Ability to change a note's position in a branch through script API (feature request) 

### ISSUE THREAD

**Issue by jobidon** [zadam/trilium#2510]
### Describe feature

It is possible to set 'position' when creating a new note, but I couldn't find the function to change the position of a note in a branch once it has been created.

**Comment by zadam** [comment]
Suppose you have a note entity:

```javascript
const branch = note.getParentBranches()[0];

branch.notePosition = 111; // whatever
branch.save();
```

**Comment by jobidon** [comment]
that's simple enough! Thanks!
is there a way for the backend to instruct the frontend to refresh the tree?

**Comment by zadam** [comment]
Normally, when you call `.save()` the change will be propagated to the frontend automatically and no extra action is necessary.

But changing notePosition is special since changing it is done often in bulk and therefore update is triggered using extra instruction. But triggering this is not available in the script API.

I'm afraid that ATM there's no other way than to manually refresh the frontend (F5) to get the script-changed ordering.
