### ISSUE TITLE
(Bug report) Importing protected notes fails

### ISSUE THREAD

**Issue by sigaloid** [zadam/trilium#2531]
### Trilium Version

0.49.3

### What operating system are you using?

Other Linux

### What is your setup?

Local + server sync

### Operating System Version

Fedora

### Description

The notes just have a base64-encoded title, no actual encrypted content that can be decrypted. Is there a way to import or view these contents?

**Comment by zadam** [comment]
Hi, exporting protected notes is generally supported only while in protected session - then they are exported as unprotected.

Exporting protected notes without protected session does not make much sense since you would export the cipher text which can't be decrypted when imported to a different trilium document.

This is because the data is encrypted using a random key which is encrypted by a password-derived key. So to be able to encrypt the data you need access to the original document and know the password.

(There is still a possible use case that you export and import into the same document, but that does not seem that important)

**Comment by zadam** [comment]
Btw seeing the hash in the title is a bug which has been fixed - now the names are just "[protected]".

**Comment by sigaloid** [comment]
Ah, I thought it would be able to be decrypted if I enter the same password. Thanks! 

Would adding a prompt in the export page to enter a protected session be worth it? 

Also - the "export finished" modal displays before it's actually finished (the zip is still increasing in size a few seconds after export).

**Comment by zadam** [comment]
> Also - the "export finished" modal displays before it's actually finished (the zip is still increasing in size a few seconds after export).

This displays when ZIP is finished on the backend side, but fully downloading to the client can take more time.

**Comment by sigaloid** [comment]
Thanks! I've added a little bit to the wiki about exporting protected notes. Closing for now
