### ISSUE TITLE
(Bug report) 

### ISSUE THREAD

**Issue by Tortolonch** [zadam/trilium#2584]
### Trilium Version

0.49.5

### What operating system are you using?

Windows

### What is your setup?

Local (no sync)

### Operating System Version

Windows 10 Version 20H2, OS Build 19042.1466

### Description

Deleting images from a note adds them to a subtree. (Or rather, reveals their original subtree?)

**Comment by Mirwaisse** [comment]
I think this is is intended.

When you add an image in the content of a note, a new child note of type "Image" is created.

![image](https://user-images.githubusercontent.com/25323123/150607247-08bed8cb-039e-4020-a05e-96375a5174f6.png)

![image](https://user-images.githubusercontent.com/25323123/150607284-f739f7f8-fd06-4c00-9e6d-5de96d90251b.png)

This is note is hidden in the note tree by default, but you can show it by changing a setting:

![image](https://user-images.githubusercontent.com/25323123/150607297-4918d55e-8464-4380-a038-6a0e05235214.png)

Here is the source of the note. If you delete the image from your note, you can see that you only delete a reference to the child image note. 

![image](https://user-images.githubusercontent.com/25323123/150607458-0759c6b3-b6aa-49a5-8be8-ea31f16b5336.png)

So the actual image note is still intact, and since it is not included in any note, it now appears in the file tree.

I think this is intended because if deleting an image (the reference) from a note would mean also deleting the actual image note, then each time you cut and paste an image in your note, it would also delete and recreate an image note.

**Comment by zadam** [comment]
What @Mirwaisse wrote is correct. It's just a result of how images work in Trilium. In some cases it's not optimal, but it's not that difficult to delete the image note if needed.
