### ISSUE TITLE
(Feature request) Add the ability to attach binary (any) files to notes

### ISSUE THREAD

**Issue by dreamofi** [zadam/trilium#2592]
### Describe feature

It would be great if Trilium allow attaching files in a note. For example, I want to store some pdf and excels file in the note (just for storing instead of rendering, like Microsoft Word allow adding files to the docx file).

**Comment by zadam** [comment]
This is supported:

![image](https://user-images.githubusercontent.com/617641/151047667-d1117065-52c0-4853-a06a-5de834e7e4af.png)

The binary files will be stored as child notes underneath the current note.

Drag & drop should work too.

**Comment by dreamofi** [comment]
Thank you!
I've tried it just now and it works wonderfully. I'll close this ticket :)

**Comment by cwilliams5** [comment]
Hey Zadam,

These would inflate the db pretty big right? Is there performance reasons or anything to stay away from doing that or is OK to just go nuts with attachments.

**Comment by zadam** [comment]
Performance should be generally fine, SQLite can easily handle tens of gigabytes. There might be problems with very big files since Trilium needs to load them into memory, files under 100 MBs should be fine though.

With the growing DB size one problem I can think of could be [automatic backup](github.com/zadam/trilium/wiki/Backup) which creates a copy of the DB before application starts and this can take some time (depends on disk speed). Backup can be turned off.
