### ISSUE TITLE
(Feature request) Option to disable tray icon

### ISSUE THREAD

**Issue by pssandhu** [zadam/trilium#2612]
### Describe feature

It would be useful if there was an option to disable the tray icon.

### Additional Information

Use cases:
- Users that don't want to use this feature
- Systems that don't allow disabling individual tray icons

**Comment by renyuneyun** [comment]
Strongly support this FR. MacOS is a particular example where this feature is much needed.

When I'm using KDE Plasma (on Linux), this is fine because Plasma allows to hide tray icons. Plus, the tray size is customizable to some extent (and I can move the tray around).
However, on MacOS, the tray region is quite limited. Apple also does not provide a way to hide/fold the icons. In my case, the tray easily overflows with 8 application indicators (plus 2-3 system indicators), and the further ones are simply invisible. Being able to remove some of them is really necessary.

And personally, I never used the tray icon. I understand some people may need this, but why can't it be customizable?

**Comment by zadam** [comment]
Added into the "Other" options tab:

<img width="806" alt="image" src="https://user-images.githubusercontent.com/617641/202799628-405a416e-f7ba-4932-8818-bbdd3ce91b52.png">
