### ISSUE TITLE
handling the three right hand panes

### ISSUE THREAD

**Issue by rzw** [zadam/trilium#262]
This is somewhat related to the adjustments you made to adjust the tree pane.

Depending on the size of the window Trilium is running in, panes can be completely invisible. I was a bit confused, I didn't see the icons for subpages in the opening page of the demo. After deleting lines in the note they started appearing. Though unlikely because you generally wouldn't have that many attributes visible in the UI, it is possible to just (partially) see those labels/attributes - no notes, no subpage icons.

Scroll bars on all three right hand panes and a minimum height should be provided in some later revision.

While I jot down my fairly fresh ideas gaining experience with Trilium, I feel uncomfortable without putting my recognition of your exceptional work on this program up front. You have put to work some very nice concepts which makes the program superior to others - as always of course depending on the field of use. And because it depends I will continue to use Wikidpad along with Trilium. But I'm having more and more fun playing around with Trilium.

**Comment by zadam** [comment]
Hello, it took me a while but I think I understand what you mean.

The fact that those subpage boxes are invisible when there's enough text content is actually intentional. I consider text (or other note content) more important than this view since subpages are of course available also in the tree pane. The intended use case for these boxes is when you have kind of "folder" note which doesn't really have its own content so we can at least display the subpages.

As for the promoted attributes and note content - I experimented a little bit and I agree that both should have some minimum height. I will take a look at this.

Just to understand your use case - are you using very small windows or you have e.g. a lot of promoted attributes?

Also thanks for your kind words :-)

**Comment by rzw** [comment]
@Just to understand your use:
Now that I know, it's no big deal. As I said I was surprised about that first demo page and looked for a checkbox in the configurations (show/hide subpages). But the promoted attributes should have a scroll bar and maximum percentage height. As you say, the notes come first.
