### ISSUE TITLE
enhancement: task-list with checkboxes

### ISSUE THREAD

**Issue by s1nceri7y** [zadam/trilium#264]
something like that
![image](https://user-images.githubusercontent.com/23638148/50542236-b5ec3900-0bc9-11e9-89c0-7bcd529e9fad.png)

https://blog.github.com/2014-04-28-task-lists-in-all-markdown-documents/

**Comment by zadam** [comment]
Hello, checkboxes would be a welcome feature, but this would have to be implemented in the CKEditor (editing component). I created an [issue](https://github.com/ckeditor/ckeditor5/issues/1434) there to see what they think about this.

**Comment by WhiteLeash** [comment]
+1 for this - would see :D

**Comment by jkurei** [comment]
I'm also dearly missing task lists in my notes since I moved to Trilium. I'm using markdown's checkboxes in the mean time but it isn't very nice. I thought It might be possible to extend CKEditor with custom types, specially since it uses HTML as source for the document.

I'm also looking at doing tasklists with a script and a Render Note, it shouldn't be too hard, but wouldn't allow checks inside any note.
