### ISSUE TITLE
filter for "todoDate" or "doneDate": only match (no gt or lt)

### ISSUE THREAD

**Issue by rzw** [zadam/trilium#265]
I use an additional number field "sortDate" to be able to filter a range of dates. I have to populate this manually.

Shouldn't > or < work with any type?

**Comment by zadam** [comment]
Hello, this is a bit complicated, but ... label values are untyped - everything is just a string - even numbers, dates etc. This is intentional because types are not important for most use cases but they would require more work on the user part (user needs to define them etc.) 

So since we do not have information about the type, we use heuristic instead - if the parameter is parseable as float, we consider this comparison to be numeric, if not then it's string based. The problem was that the date "2018-12-30" still parses as "2018" float in JS so it didn't work properly. I fixed this with more precise check so the date does not parse as float and string comparison is used which then produces expected results.
