### ISSUE TITLE
Would the project be open to design contribution?

### ISSUE THREAD

**Issue by rojcyk** [zadam/trilium#269]
I would be willing to help design this product, to make it visually more consistent and generally polished.

**Comment by zadam** [comment]
Hello, that would be certainly welcome. This is definitely one of the weaknesses right now ...

**Comment by AleksandarFaraj** [comment]
What tools would you use @Rojcyk? I'll put my +1 for "Adobe XD" since it is easy to use and free.

**Comment by rojcyk** [comment]
@AleksandarFaraj I would prefer Figma. It is available via the browser for everyone, no apps are needed, and is also free.

@zadam I'll see what I can do! :)

**Comment by rojcyk** [comment]
@zadam Do you have a planned roadmap somewhere public?

**Comment by zadam** [comment]
Do you mean like long term or what will be the features in the next release? I typically release new feature release once in few weeks (typically 2-3 weeks). For the next one I plan to work on some of the larger items from the feedback in issues.

**Comment by gaui** [comment]
It would be awesome to have a new design, set up a Design System and implement the frontend in React + SSR. This jQuery + Bootstrap stuff is so hard to maintain.

**Comment by zadam** [comment]
React and SSR are mostly out of the question.

**Comment by gaui** [comment]
@zadam why?

**Comment by gaui** [comment]
You're SSR'ing currently with Express+EJS right?

**Comment by zadam** [comment]
I guess the main ones are it would mean a big frontend rewrite and that it doesn't actually solve any problems I have. 

I also have some doubts if React is a good fit for this particular project (you can view Trilium's frontend as a glue between several libraries which are not necessarily react friendly). There are some parts which I think would benefit from something like React/Vue etc. but it's pretty clear minority.

**Comment by yozlet** [comment]
@zadam Which problems are those?

I ask because the use of existing frameworks (for components, state management, storage, testing etc.) could solve a number of higher-order problems, especially around making the code easier to understand and maintain. In this case, it could make it much easier for @rojcyk to integrate his work without breaking app logic. Most importantly, it _wouldn't_ require rewriting the whole frontend before it starts to pay dividends. Nobody wants to wait for a long experimental rewrite before work on the app can continue.

But for that to be valuable, it has to meet your needs for the project. There are a bunch of newcomers who want to contribute (including myself), but ultimately their work has to fit with where you want the project to go. And this may not be the right place/thread to talk about that, but it could save a bunch of time and effort.

**Comment by robitar** [comment]
I also felt the UI/X could do with a bit of a polish, I'm really liking the philsophy and design around the data model and the thoughtfulness/utility/pragmatism (I was just about to start building something similar when I happened accross it!)

Thanks to the wonderful ability to add easily add custom styles (and the well structured easy to grok html) I was able to add some polish in a day or two. It's still a bit rough/wip, but some people mind find it useful:

![capturea](https://user-images.githubusercontent.com/685542/51274908-53b47600-19c8-11e9-9f31-77c1cb965d52.JPG)

![captureb](https://user-images.githubusercontent.com/685542/51274918-59aa5700-19c8-11e9-8f14-5e4cc85c53a8.JPG)

![capturec](https://user-images.githubusercontent.com/685542/51274925-5d3dde00-19c8-11e9-90a0-759feedc3e09.JPG)

**Comment by edenpc** [comment]
Wow, that's very impressive!

**Comment by zadam** [comment]
This was more of a general discussion thread so closing now. Please open new issue for new questions etc.
