### ISSUE TITLE
(Bug report) Broken relation appears when I delete a note (or image)

### ISSUE THREAD

**Issue by gdbb** [zadam/trilium#2701]
### Trilium Version

0.50.2

### What operating system are you using?

macOS

### What is your setup?

Local + server sync

### Operating System Version

macOS 12.2.1

### Description

Hi, zadam,

I reproduce this bug(maybe feature?) on both macOS and server edition.

When I copy the contents of an old note, including some images, into a new note, (ctrl+a, ctrl+v), everything is OK, but "Following relation will be broken and deleted" appears when I want to delete the old note. 

I know the reason is, that the image in the new note is a reference to the old image, but I still wonder whether there is a good way to copy (move) many images into a new note and delete the old note smoothly. 

Btw, What I do to avoid this is to manually copy every single image from the old note into the new one, and entirely delete the old note.

![截屏2022-03-02 15 09 36](https://user-images.githubusercontent.com/7486825/156312370-c68145cf-ab4d-4425-8ee2-15cea226fcfd.png)

![截屏2022-03-02 15 06 51](https://user-images.githubusercontent.com/7486825/156312314-e4ddfe6f-2ac7-423d-8c11-1aaf2e50f029.png)

**Comment by XXXJetfireXXX** [comment]
I don't think it is actually a bug. When you place an image in your note, it actually makes a link to the image file that is stored within the note's subtree. 
![image](https://user-images.githubusercontent.com/43646178/156361956-dd1827d5-7a33-40ac-b4ae-4139fdb5cc74.png)
You can see them by removing the checkmark from this option:
![image](https://user-images.githubusercontent.com/43646178/156362091-c6ee7d12-9d76-4914-b668-c847e22e2113.png)
![image](https://user-images.githubusercontent.com/43646178/156362137-e86727bb-bbdf-45d1-b338-5f3e174368bc.png)
That's why, by deleting an old note, you're deleting the source files of your images. If you want to keep them, you can toggle the option I mentioned above and just move them to a new note (or somewhere else).

**Comment by zadam** [comment]
Yes, @XXXJetfireXXX provides a good explanation.

Images are technically "note of type image" and are present in the note tree. They are then referenced (displayed) in text notes. This has some nice properties, but is also somewhat confusing for people, that's why images which are included into their parent are normally hidden from the tree. But in cases like you describe the abstraction breaks down and you must understand what's actually happening.

I admit this is not a good user experience but I'm not sure how to solve this ... :-/

**Comment by gdbb** [comment]
@XXXJetfireXXX @zadam 

Thanks for your explanation! I can get the point that why it is designed like this.
So now my solution is,

First, copy all contents of edit panel in the old note into the new one (now the images in new note are just references);
second, manually select all images(sub-notes) of the old note and copy all of them into the new note (sub-note). This operation confirms that the images are no longer a link or reference.
Third, delete all the old note and images.
