### ISSUE TITLE
(Feature request) Shared notes with: robots → noindex

### ISSUE THREAD

**Issue by TorstenC** [zadam/trilium#2713]
### Describe feature

Robots.txt is text file that contains the instructions for various robots (mainly search engine robots).
I want to define how to crawl and index my shared notes.

Can we add a feature to add a robots.txt file in shared notes root directory?

### Additional Information

`~shareRobotsTxt` can be easily implemented like `~shareJs` and `~shareCss` relations.

**Comment by sigaloid** [comment]
Since you already pretty much have to use a reverse proxy in order to provide access to the shared notes (otherwise it's plain HTTP), I'm fairly certain you can simply define robots.txt as a file in the reverse proxy configuration. For example, the Caddy webserver has the [respond directive](https://caddyserver.com/docs/caddyfile/directives/respond).

**Comment by zadam** [comment]
Hi, sorry for late response. I think it should be possible to do it like this:

* create a shared note of type code (plain text), set the intended content for robots.txt
* add a `#shareAlias="robots.txt"`
* add a `#shareHiddenFromTree` so that it doesn't display in the navigation

But perhaps a direct support for `shareRobotsTxt` like you mention would make sense as well.

**Comment by zadam** [comment]
You're right, that doesn't work as intended.

What do you think about this proposal?

* `robots.txt` stays constant with shared notes by default indexable: https://github.com/zadam/trilium/blob/master/src/public/robots.txt
* there will be a new label called `#shareForbidIndexing` (or some better name) using which you can mark notes which should not be indexed - these will then be marked with `X-Robots-Tag` header and meta tag (where applicable). By making the label inheritable, you can apply this on subtrees or even all shared notes.

**Comment by zadam** [comment]
Implemented a while ago.

**Comment by TorstenC** [comment]
Thank you, also for updating the wiki page in ["Other options"](https://github.com/zadam/trilium/wiki/Sharing#other-options). 🙂 

I added the `#shareDisallowRobotIndexing(inheritable)` label directly to my "Shared Notes" root.
