### ISSUE TITLE
Multi-level encryption?

### ISSUE THREAD

**Issue by tuxlifan** [zadam/trilium#280]
First, thank you for this wonderful knowledge base!

Do you see a possibility to have multiple levels of encryption in the future?

Use case A:
* A.1 Have subtree(s) with private but not secret information as "protected" to guard them at rest and unlock them with a very long timeout for regular use.
* A.2 At the same time e.g. the Journal subtree would warrant an extra password to be required for unlocking when reading/editing it.
* A.3 An additional password should be required for notes that contain credentials, etc. so one can show someone a (hoisted) part of the Journal without accidentally showing secrets by accident when jumping, fat-fingering some keyboard shortcut, etc.

Probably worth a different ticket but maybe connected:
It would be *very* good to provide a way to protect any (text) note without having to provide the password. i.e. one might want to note something secret down in the presence of someone who knows the secret but should not be able to get the password although they are omnipresent and very observant at that time (yeah, it's a bit of a stretch but please read it as "encrypting stuff safely should be very easy and very fast (UI-wise)") This would certainly require some kind of private/public key scheme, AFAICT.
As a bolt-on solution, maybe store the private key in a special (protected) note and the public key in the root note attributes (or a path to where it is); then on the press of a button encrypt the contents of the current (text) note (using e.g. OpenPGP.js?) and replace it, setting an additional attribute for tracking.
Later, after entering a protected session, all notes with the tracking attribute could then be decrypted, rewritten and protected "as usual"?
If there were a general encrypt/decrypt button for text notes' contents this might also work for Use case A if the private key(s) is/are additionally password protected and one would chose to which public key to encrypt when first pressed for that note.

And last but not least the elephant-in-the-room question with my apologies if I missed the information somewhere:
Are you a cryptographer or has a cryptographer looked at your encryption scheme and implementation? What are the benefits compared to using something like OpenPGP.js?

Thanks,

**Comment by zadam** [comment]
> A.1 Have subtree(s) with private but not secret information as "protected" to guard them at rest and unlock them with a very long timeout for regular use.

So I understand that the data would be encrypted by some password-derived key, but it would be kept in memory for e.g. whole runtime of the app - so you would be asked for password only once right after app startup.

> A.3 An additional password should be required for notes that contain credentials, etc. so one can show someone a (hoisted) part of the Journal without accidentally showing secrets by accident when jumping, fat-fingering some keyboard shortcut, etc.

This is pretty interesting idea. Although there are some questions - like if you gain access to the most-secret session, do you automatically get access to the lower security ones as well? Or are they totally separate (non-hierarchical)?

I can actually imagine myself using it because I also have certain levels of privacy. It could leverage tree hierarchy - you could define (e.g. using attributes) that this subtree uses a separate session from the global one - you could define also a specific timeout. Having this would actually enable the A.1 - you would have a global session for the whole tree with very long expiration and root note would be set as protected (child notes automatically inherit the protected switch).

This would have some non-trivial implementation costs - I can see some issues and there would be some unseen as well. And there's a question of how niche this would be - I doubt many people would use it ...

> It would be very good to provide a way to protect any (text) note without having to provide the password. i.e. one might want to note something secret down in the presence of someone who knows the secret but should not be able to get the password although they are omnipresent and very observant at that time (yeah, it's a bit of a stretch but please read it as "encrypting stuff safely should be very easy and very fast (UI-wise)") This would certainly require some kind of private/public key scheme, AFAICT.

I understand the appeal of having a quick way to store the secret without having to type the password. There are some questions on the UI though - you can protect (encrypt) the content using public key, but what happens to the plain text in the UI? Does it disappear from UI immediatelly after clicking on "protect" or do we give the user some time? Since the user isn't in "protected session" so they should not be able to see any protected content, not even the one just created.

> And last but not least the elephant-in-the-room question with my apologies if I missed the information somewhere:
> Are you a cryptographer or has a cryptographer looked at your encryption scheme and implementation? What are the benefits compared to using something like OpenPGP.js?

I'm not a cryptographer and the encryption scheme has not been reviewed by one. Not sure if you've seen this, but basic overview is here: https://github.com/zadam/trilium/wiki/Protected-notes

I understand that even though I'm using well known and tested cryptographic primitives (like AES, scrypt), it's still possible to use them in a wrong way. But I'm not sure if openpgp would protect me from this, because I would still need to do several separate steps - e.g. key stretching / derivation needs to happen at the point of entering the protected session and actual decryption of the data needs to happen at the later point using already stretched out key. This all can't be encapsulated in a single call to openpgp

**Comment by tuxlifan** [comment]
(sorry if the formatting comes out wrong, the Preview seems to be broken for me :()

Just replying to a part; will have to think some more about and take more time to properly reply to the rest.

> > It would be very good to provide a way to protect any (text) note without having to provide the password. i.e. one might want to note something secret down in the presence of someone who knows the secret but should not be able to get the password although they are omnipresent and very observant at that time (yeah, it's a bit of a stretch but please read it as "encrypting stuff safely should be very easy and very fast (UI-wise)") This would certainly require some kind of private/public key scheme, AFAICT.
> I understand the appeal of having a quick way to store the secret without having to type the password. There are some questions on the UI though - you can protect (encrypt) the content using public key, but what happens to the plain text in the UI? Does it disappear from UI immediatelly after clicking on "protect" or do we give the user some time? Since the user isn't in "protected session" so they should not be able to see any protected content, not even the one just created.

I was thinking that the content would be replaced right away by the (ascii-armored/base-encoded/...) cyphertext.

A timer of a few seconds during which a Ctrl-z would restore the plaintext could be helpful in case of a mis-click but might open attack channels.

A header explaining what happened might be prudent, though, i.e.
```
### The content of this note has now been encrypted at your request.
### The cyphertext below will be converted to a regular protected note the next time
### you enter a protected session.
### At that time you will also be able to unprotect the note again and make the content
### as accessible as it was before.
```

Cheers,

**Comment by zadam** [comment]
I think back when I closed this github didn't yet differentiate between different kinds of "closed" states.

IIRC I closed this because I don't plan to implement such a thing.
