### ISSUE TITLE
(Feature request) Select template when creating page

### ISSUE THREAD

**Issue by zadam** [zadam/trilium#2813]
### Describe feature

The flow for creating a new page (either via right click on the tree menu, via linking to it with Ctrl+L or via creating a relation to it) could maybe be improved by adding a control to easily select a template for the new page.

**Comment by seconddayout** [comment]
How is the used? Docs?

**Comment by Nriver** [comment]
> How is the used? Docs?

Just right click the note tree, there is a sub context menu in insert note button.

**Comment by seconddayout** [comment]
> Just right click the note tree, there is a sub context menu in insert note button.

![Screen Shot 2022-07-13 at 09 16 39](https://user-images.githubusercontent.com/48814916/178803893-1e39a7d8-c3c8-44d2-8090-eeefaca1153c.png)

Seems I'm blind or misconseptualizing what I ought to be seeing because I'm expecting and option along the lines of `Select From Templates` and am seeing no such option in the contextual menu.

App version: `0.53.2`

**Comment by zadam** [comment]
@seconddayout you're looking at the correct place, but your templates are missing the `#template` label, which marks them to be shown there.

See details here: https://github.com/zadam/trilium/wiki/Template

**Comment by seconddayout** [comment]
How 'bout that: it works. Huzzah. How simple things seems once ya know 'em. Thanks, @zadam.

**Comment by agentydragon** [comment]
Thanks a lot for this feature!
Could we also have a variant of the Ctrl+P / Ctrl+Alt+P keyboard shortcuts that ask for a template?
