### ISSUE TITLE
(Bug report) Mermaid Pie Diagram width matches screen size - doesn't adjust to diagram size.

### ISSUE THREAD

**Issue by laundmo** [zadam/trilium#2984]
### Trilium Version

0.53.2

### What operating system are you using?

Windows

### What is your setup?

Local + server sync

### Operating System Version

Windows 10 19043

### Description

When creating a Mermaid Pie-Chart the width of the rendered SVG is set to approximately the width of the monitor. This leads to having to scroll sideways when trying to view the Pie chart.

This is what it looks like with Trilium as a smaller-than-fullscreen window.
![image](https://user-images.githubusercontent.com/24855949/178738871-19650ca3-4c5d-47f7-91f8-ce93b75e2d8d.png)

Here i have scrolled to the left and highlighted the SVGs dimensions
![image](https://user-images.githubusercontent.com/24855949/178738124-69ff3418-8d55-4162-8d98-508e12237bd7.png)

**Comment by zadam** [comment]
Hi, not sure why this is happening, it looks like there's just so many whitespace in the pie diagram that it forces the scrollbar. I worked around it like this:

![image](https://user-images.githubusercontent.com/617641/179085376-57efa655-5ff0-4f89-8470-41a0ca2d923e.png)

It's too small, again probably because of too much white space in the rendered SVG, but I guess still an improvement.

**Comment by laundmo** [comment]
Thank you for trying, i think this is a upstream bug even though none of the upstream bug reports in mermaid are about width or the pie diagram (always just height)
