### ISSUE TITLE
insecure default ivLength for AES

### ISSUE THREAD

**Issue by BubbLess** [zadam/trilium#3017]
Hi, I found that the ivLength is set to 13 in the data_encryption service, then it will be padded with zero bytes to 16.
https://github.com/zadam/trilium/blob/80887fd3c13baecbdb0619a9f462c5a6fbdb5439/src/services/data_encryption.js#L20-L42
This causes the last 3 bytes of IV to be fixed, and will leak the information about the last 3 bytes of the first cipher block. I really don't understand the reason of setting the ivLength to 13, I think just set it to 16 will be better.
And I noticed that while encrypting password, the ivLength is correctly set to 16.
https://github.com/zadam/trilium/blob/37eb16b2f30f528a2fedd9ef4cc6e6ff084469b4/src/services/password_encryption.js#L21

**Comment by zadam** [comment]
Hi, good question. IIRC there was a bug in a very old version of Trilium which stored only first 13 bytes of IV. That was soon discovered, however it's not possibly to just decrypt and reencrypt existing protected notes during database migration (since it's encrypted using user's password which has to be entered by the user). So I just made 13-byte IV standard.

You mention that this is insecure, but AFAIK it's not. Main requirement for IV is that it is unique. 13 bytes provides 104 bits of entropy. The risk of reusing an IV is essentially a birthday problem. Trilium is designed to handle 100 000 notes, let's calculate with a million. Birthday problem of 2^104 "days" and 1 million children gives probability of collision 1/10^20, which for me still provides very good security.

**Comment by BubbLess** [comment]
Yes, the basic requirement for IV is to be unique, but for CBC mode, the IV also needs to be random to provide semantic security. You can check the [properties of IV](https://en.wikipedia.org/wiki/Initialization_vector#Properties).
The problem here is that the last 3 bytes of IV are fixed zero bytes, therefore the encryption of the last 3 bytes of the first message block is actually in ECB mode. Then the adversary can get the relation between two message blocks M1, M2 with their cipher blocks C1, C2:$$C1_{last3} \bigoplus C2_{last3} = M1_{last3} \bigoplus M2_{last3}$$ 
If the adversary knows M1, then he also get M2, for the last 3 bytes of their first block. Of cource this may not be a big problem, I'm just curious about the reason for using 13 bytes IV. 
I think add a version to the encrypt data will make it more flexible to upgrade, like [turtl](https://turtlapp.com/docs/security/encryption-specifics/#symmetric-serialization-format) do in their design.

Here are some links you can refer to:
[what-problem-happen-if-we-always-use-iv-zero-in-cbc-mode](https://crypto.stackexchange.com/questions/30567/what-problem-happen-if-we-always-use-iv-zero-in-cbc-mode)
[aes-cbc-pkcs5padding-encryption-with-fixed-iv-or-without-one](https://stackoverflow.com/questions/66499175/aes-cbc-pkcs5padding-encryption-with-fixed-iv-or-without-one)

**Comment by BubbLess** [comment]
OK, this may not be a big problem, I'm just curious about the reason for using 13 bytes IV.  I think add a version to the encrypt data will make it more flexible for migrating, like [turtl](https://turtlapp.com/docs/security/encryption-specifics/#symmetric-serialization-format) do in their design.

**Comment by zadam** [comment]
These encrypted records don't have format versioning, but it's easy to distinguish them - records with old IVs have always size % 16 = 13, new records with 16 byte IVs will have size % 16 = 0, so it's easy to distinguish.
