### ISSUE TITLE
(Bug report) Sync server handshake failed - 400 Bad Request

### ISSUE THREAD

**Issue by adamerose** [zadam/trilium#3018]
### Trilium Version

0.53.2

### What operating system are you using?

Windows

### What is your setup?

Local + server sync

### Operating System Version

Windows 10

### Description

- I installed the Docker container on my Ubuntu server and ran it
- I installed the desktop client on my Windows PC
- I am able to access the web client and write notes when I navigate to http://SERVER_IP_ADDRESS:8080 from my desktop PC
- When I provide the desktop client the same URL in Options -> Sync, I get the error below
```
Sync server handshake failed, error: Request to POST http://SERVER_IP_ADDRESS:8080/api/login/sync failed, error: 400 Bad Request
```

**Comment by sigaloid** [comment]
Is there any reverse proxy between the server and your computer? Apache, nginx, etc?

**Comment by adamerose** [comment]
> Is there any reverse proxy between the server and your computer? Apache, nginx, etc?

No, this is a new VPS with no web servers installed. I think if it was a reverse proxy issue I wouldn't be able to access the web client, right?

**Comment by sigaloid** [comment]
I've seen reverse proxy issues where syncing doesn't work but browser access does, because the sync protocol uses different methods than browser access (ex. sync uses larger payloads and there may be a low max size for the reverse proxy to handle). 

But since there's not: have you tried restarting the server? Is there existing data on the server, or the client, or both, or neither?

If you have a server with data and want to add a fresh desktop to sync with, you should probably delete everything from the desktop directory then restart the sync process. That way you can enter it directly on the intro page rather than once you've created a database on the desktop.

**Comment by adamerose** [comment]
> If you have a server with data and want to add a fresh desktop to sync with, you should probably delete everything from the desktop directory then restart the sync process. That way you can enter it directly on the intro page rather than once you've created a database on the desktop.

Okay that worked for me, thanks :)
