### ISSUE TITLE
clicking search button will generate an invalid backlink

### ISSUE THREAD

**Issue by evanhon0110** [zadam/trilium#3072]
### Trilium Version

0.54.2

### What operating system are you using?

Windows

### What is your setup?

Local (no sync)

### Operating System Version

windows 10 version 21H2

### Description

When I click the search button on the left column, I do nothing. The root note will still create a backlink to point to this empty search

**Comment by zadam** [comment]
Hi, is there some error in the console (open with CTRL-SHIFT-I)?

**Comment by evanhon0110** [comment]
sorry, there is no any error. I upload a gif image to show the problem.

**Comment by sigaloid** [comment]
This is because when you click search, it will create a saved search note that is backlinked to the note you were on when you clicked search. It sounds like backlinks requested from the route "/api/note-map/:noteId/backlinks" and backlinks-count should exclude notes with the label of "excludeFromNoteMap".

@zadam, a minor change filtering for that label would fix it - it just filters the API to only say there is any backlinks if the backlinked note doesn't have the label of "excludeFromNoteMap". The other three API routes under `api/note-map`, `getTreeMap` and `getLinkMap`, also filter for the existence of excludeFromNoteMap. 

I've submitted a PR that solves this issue.

**Comment by evanhon0110** [comment]
Thanks for your reply.
