### ISSUE TITLE
Introduce global menu

### ISSUE THREAD

**Issue by zadam** [zadam/trilium#311]
in the place of current log out button. Should contain:

* Sign out
* Open dev tools
* Show menu
... maybe other things

**Comment by zadam** [comment]
There is one in the server installation. None in desktop since it doesn't make sense there ...

**Comment by AleksandarFaraj** [comment]
Sorry if my previous reply seemed slightly rude, but to explain my case.

I tried out the tool locally (electron client) to evaluate it, and I loved it, kudos. The problem was that I did use quite a bogus username and password and after which, I installed a server version on DigitalOcean. I found it was quite un-intuitive not to have the option to clear the old session to start a fresh one on my server. My solution was that I just deleted the data folder to start over.

**Comment by yozlet** [comment]
Are you talking about [native Electron menus](https://electronjs.org/docs/api/menu)? For commands that make sense in the desktop version, that would be a great place to put them. It would also take care of keyboard shortcuts (with accelerators).

**Comment by zadam** [comment]
Nope, I don't want to use native Electron menus - partly because they are (obviously) not available in the web version. I plan to use bootstrap dropdown, similar to e.g. what's in "Note actions".

**Comment by zadam** [comment]
fixed in master
