### ISSUE TITLE
GDrive/Dropbox Sync

### ISSUE THREAD

**Issue by Berkmann18** [zadam/trilium#317]
I've seen this package in the trending tab and couldn't find any info on whether this tool could sync notes with Google Drive and/or Dropbox (or any cross-platform cloud services for that matter).
Is it something it can do (or will do)?

**Comment by zadam** [comment]
Right now it can't sync with 3rd party and there's little chance it ever will. The reason is that Trilium's feature set requires use of database instead of just flat files. And database storage is essentially unsyncable using generic solutions like Dropbox.

Having said that I heard from users who set up the sync with Dropbox/GDrive and it worked as long as they made sure they used the app always just on one of the machines. But this is pretty hard to do in practice so I don't consider it a real solution.

**Comment by Berkmann18** [comment]
Okay, thanks for the information.

**Comment by frigvid** [comment]
Just a little note, should it ever become of any relevance.

The easiest way to work around the issues caused by generic synchronization solutions like Microsoft OneDrive, Dropbox, Google Drive and the like, is to use a 'lock file'. Essentially just an arbitrary file that is used by the software to check which machine is currently syncing to or from the sync location and blocking access until afterwards. This is how [Joplin worked around the issue](https://joplinapp.org/spec/sync_lock/), for example.
