### ISSUE TITLE
Please cancel the default note name

### ISSUE THREAD

**Issue by lbgws2** [zadam/trilium#318]
When i create the notes,there will be a default named--new note
Maybe for beauty or something,i guess
But for me, this is very inconvenient, Every time I have to delete it, then type my note name
after all, an Ambiguous note name mean nothing,and unuseful for the search

**Comment by zadam** [comment]
This is mostly about UI - currently if title doesn't have any value you can't even see that there's an input box. Also tree items look bad without a name.

I will probably keep the default title, but I might add a possibility to make this configurable.

**Comment by mjsisley** [comment]
Maybe adding a bit more information to the default title would be useful for search ability (I agree a complete removal wouldn't make sense due to UI and tree structure)?

Couple ideas:
* untitled note - [Datetime stamp]
* [First ??? characters of the note OR first title in note]

**Comment by zadam** [comment]
The second option is interesting but also not easy - it would mean we would have to change the title after the note has been created (after user entered some content).

What I'm thinking now though is to address original complaint is that after note is created, I currently put a focus on the title, in addition I can select the text in it - that way if you want to start typing new title, you don't need to delete it since it's in selection and what you type will automatically overwrite it. If you want to just go to the text (sometimes I don't bother thinking of the title immediatelly) you can just press enter to go to the text ...

**Comment by lbgws2** [comment]
Another option is to use the user's title if the user enters a title when creating a new note,If the title box has no text and loses focus, the default title is used

**Comment by zadam** [comment]
I think the desired effect (not having to delete the title explicitly) is now achieved so closing.
