### ISSUE TITLE
Multiple values per attribute

### ISSUE THREAD

**Issue by mahdi1234** [zadam/trilium#33]
I sometimes have multiple values for attribute e.g. Supplier can be Supplier_A and Supplier_B for certain nodes.

Might work to have "+" button to add additional value or allow duplicated attributes, not sure what you think about this in general?

**Comment by zadam** [comment]
Yeah, I think I'll allow multiple attributes with same name per note (essentially multi-value).

Some things then become not immediatelly obvious. Like if note has attributes @price=5 @price=10, then should filter @price<10 match the note. What about search @price!=10 ... What about search @price=5 AND @price=10

In most attributes setting multiple values would be actually mistake, but then it would be up to users to keep their  data consistent. I guess I could change current duplicate attribute validation error to information so that user can easily see that attribute is duplicated.

**Comment by mahdi1234** [comment]
I could think of alternative using wildcard search having e.g. attribs Supplier_1 and Supplier_2 and do something like @Supplier*=Supplier_A ... not sure this is better than duplicates per node.
