### ISSUE TITLE
Quotation marks

### ISSUE THREAD

**Issue by GuillemFemenias** [zadam/trilium#3319]
Hi, when I write in a note type: "Text" it changes the " to ” even between ` ` (code) is there any way that the text highlighted as "code" with ` ` is treated as plain text? I don't want to do the full note as plaintext in situations where it has small commands preceded and followed by text or links. For me, it would make sense that the " that are between ` ` (considered code) weren't changed to ”. Thank you. (I am probably missing something, so please let me know!)

**Comment by zadam** [comment]
Hi, in the inline code, this auto-conversion can be reverted immediately after it happens with ctrl-z. Otherwise you can also use triple backticks which does not trigger this auto-conversion at all:

![image](https://user-images.githubusercontent.com/617641/202288068-b5ab89a6-cc25-46e0-97f3-b0ba4c490494.png)

**Comment by GuillemFemenias** [comment]
Ok, thank you, that's exactly what I needed!
