### ISSUE TITLE
Enhancement: Let me add a todo date to a simple note, making it automatically a task

### ISSUE THREAD

**Issue by arnwas** [zadam/trilium#339]
I often make a simple note, and find then later necessary to give it a deadline. It seems i have to reopen it from scratch as a task?

**Comment by zadam** [comment]
I assume you're using the "task manager" from the demo? It's not really meant to be a full working solution, just a showcase of what you can build in Trilium ...

**Comment by arnwas** [comment]
Does it mean that trilium is rather a framework than an application?

**Comment by jkurei** [comment]
It would be very interesting to have a better way to share our solutions to these common problems, even if Trilium doesn't include an out-of-the-box solution. May be a list of to user-contributed plugins and tutorials in the README page would be a start. 

This use case could be solved (or mostly solved) with a simple script, but it's hard to discover how to do this. I'm a fairly experienced web developer and it took me a while to figure out how to do certain things... How could we more easily share our solutions?

**Comment by zadam** [comment]
My current approach is that the .tar export archive is an exchange medium for these custom solutions / scripts / plugins. So the author develops it, exports to .tar archive and shares on the web.

It would be of course nice to have e.g. wiki page which would contain list of such plugins (or link to them). Something like plugin repository. Ideally there would be some review done since the .tar archives can potentially contain harmful code (which can be triggered automatically after import).
