### ISSUE TITLE
(Bug report) Hide the expansion arrow when all subnotes are archived

### ISSUE THREAD

**Issue by WPum** [zadam/trilium#3421]
### Trilium Version

0.57.2

### What operating system are you using?

Windows

### What is your setup?

Server access only

### Operating System Version

Windows 10 version 2004 with Firefox 107.0

### Description

When all subnotes are archived and "Hide archived notes" is turned on, an arrow is still displayed to the left of the parent note, which is confusing because there's no subnote to display.

"Hide archived notes" is turned off:

![image](https://user-images.githubusercontent.com/27683756/207659557-b5abbb9a-616c-4fca-8bdc-b528faf94c68.png)

"Hide archived notes" is turned on:

![image](https://user-images.githubusercontent.com/27683756/207659699-a7d3c02b-e5f7-43dc-9b4c-00f8067c3628.png)

**Comment by zadam** [comment]
Hi, this is ignored because of performance. The (frontend) application does not load the whole note tree, only the needed notes. To be able to detect how the parent note should be displayed, we would have to load also the children notes (to find out if they are archived). Since there are usually more children than parents in a tree structure, this would multiply the amount of data needed to be loaded across network.

There might be some clever caching tricks to do this without big performance penalty, but probably at the cost of complexity. For me this does not seem worth it for this (IMHO) minor annoyance.

**Comment by XXXJetfireXXX** [comment]
If your note only contains archived subnotes, you can mark it as archived as well so it disappears completely when hiding archived notes.
