### ISSUE TITLE
(Feature request) Clone a note without its subnotes

### ISSUE THREAD

**Issue by WPum** [zadam/trilium#3472]
### Describe feature

The cloning feature of Trilium can be seen as a "hard directory link", which means the parent note and all of its subnotes will be cloned into a new place. The feature I would like to have is a "hard file link" - the parent note will be cloned, but not its subnotes.

A typical use case of this feature is providing some general information about a specific topic. For example, someone is learning a programming language, say C++, and solving algorithm problems at the same time. He/She wants to take notes related to both the language features of C++ and the solutions of algo problems using C++. In his/her note hierarchy, "language features" and "algorithm problems" are parent notes of C++ (so he/she can take notes of other languages as well). The note hierarchy will look like this:

```
language features
|- C++
   |- pointers
   |- ...
|- Java
|- ...
algorithm problems
|- C++
   |- Two Sum
   |- ...
|- C#
|- ...
```

Here, a parent note "C++" has different subnote arrangements. If he/she creates two separate notes with the same title "C++", he/she will have difficulty in managing general information about C++, like IDE & configs & doc links. A better choice would be to have only the parent note "C++" cloned, so modifications in one note (whose content is related to general information about C++) will be synced to another immediately.

**Comment by zadam** [comment]
Hi, this would require changes in the core data structures (note/branch model) of Trilium and would probably have far-reaching consequences. I consider the base data model as "finished" and don't plan to make changes/additions unless there are very good reasons for that.

This proposal also goes a bit against Trilium's philosophy, where the whole subtree is in some sense part of the subtree root note. One of the basic operations is "break down the note if it's getting too long" and this hard file link is not really compatible with it (since these clones would essentially lose those broken-down parts).

**Comment by WPum** [comment]
Sure, indeed it is hard to implement.
