### ISSUE TITLE
Copy and Paste doesnt preserve line breaks

### ISSUE THREAD

**Issue by dabeeeenster** [zadam/trilium#349]
Not sure if this was meant to be fixed in #51 but if I copy multiple lines of bash script in Chrome on Mac (using the web client) and then paste them into Terminal, the line breaks are not honoured.

**Comment by bwat47** [comment]
I notice some inconsistencies depending on the application I'm pasting into as well:

Line breaks preserved when pasting from Trilium:
Microsoft Word (both desktop and web)
Microsoft Outlook (desktop) but only when you use 'Source Formatting' or 'Text Only' paste mode. With 'Merge' it removes the line breaks)
Github comment/most other online forms
Microsoft Onenote (Web)
Microsoft Notepad

Line breaks NOT preserved when pasting from Trilium
Microsoft Outlook (office 365 web version)
Microsoft Onenote (UWP)

**Comment by bwat47** [comment]
Also, if I paste going the other direction (e.g. Office 365 Web > Trilium), I see the issue described in #51 where extra spaces are shown in Trilium

**Comment by zadam** [comment]
Hello, these issues come from CKEditor which is used as an editing component. I know they worked recently on a copy & paste interop with office products, but it's possible it's not perfect yet.

**Comment by teresaejunior** [comment]
As much as I like CKEditor, it's decision to stick with paragraphs instead of line breaks I found incredibly annoying, and it brings too many inconsistencies.

* If I copy paragraphs with `<p>` from Trilium, they are pasted as double lines (`\n\n`) in the text editor/terminal.
* If I copy text with `<br>` from Trilium, line breaks are simply discarded when pasting into the text editor/terminal.
* If I copy text from a text editor/terminal, line breaks are pasted as `<br>`, which is the opposite behaviour.
* I imported my CherryTree notes and all line breaks became `<br>`, but when editing them, I get `<p>`.
* Text with `<br>` can't be converted to numbered or bulleted lists.

Now, one solution would be always converting line breaks to `<p>`, regardless of the input. This will cause a new series of problems. If you paste someone's address, for example: instead of having one item in each line, you get separate paragraphs. The same problem when writing someone's address (instead of pasting). You have to use *Shift+Enter* for each line break, otherwise you get:

> Mr A. Payne 
>
> ARAMARK Ltd. 
>
> 30 Commercial Road 
>
> Fratton 
>
> PORTSMOUTH 
>
> Hampshire 
>
> PO1 1AA 
>
> UNITED KINGDOM

None of these would be a problem if, like CherryTree, `<p>` was totally dropped in favor of `<br>`. I personally don't see the purpose of using paragraphs in a note taking application.

Maybe an idea would be discarding CKEditor5 in favour of some Markdown WYSIWYG editor? Trilium formatting is very similar to Markdown's anyway... Also, CKEditor4 seems to work with `<br>` - it is supported until 2023, whereas CKEditor5 is until 2026.

Sorry for the rant, I think I'm sticking with CherryTree until I see a better solution :sob:. I liked both NoteCase Pro and Standard Notes, but they are a bit on the expensive side, besides having my notes uploaded to proprietary servers.

**Comment by CrashLaker** [comment]
Having the same issue. 
I'm trying to copy content from trilium to elsewhere but it isn't breaking the lines. 

Is there a turnaround to this?

**Comment by zadam** [comment]
There's an issue with conversion to plain text AFAIK. Workaround is to copy paste it to e.g. word / wordpad or similar which will preserve the formatting.

**Comment by CrashLaker** [comment]
Thank you @zadam for now i'm just using code like template since that was the initial intention..

but it would be good if it could preserve the formatting when copying lists, etc..

**Comment by CrashLaker** [comment]
new release
https://github.com/zadam/trilium/commit/6e4c30571c9ce1e52da9c5ea40300277b9ead7bc
v0.38.2

* `built in text editor (CKEditor) now supports Code Blocks`

solved this. thank you!

**Comment by CrashLaker** [comment]
Hi guys.

Not to nag too much It would be awesome If there could be a button to copy the content inside the code block for long texts.

loving the updates!
thank you!

**Comment by zadam** [comment]
@CrashLaker do you mean a button which would copy the code block content into clipboard?

**Comment by CrashLaker** [comment]
@zadam Yeah that exactly. This way it would be easier to copy the whole <block code> content which turns out to be a "pain" for long texts.

Just like what they have in mkdocs.
![image](https://user-images.githubusercontent.com/4432491/71447752-59a2f300-2711-11ea-8548-44d2c77ce2c1.png)

**Comment by Heniker** [comment]
If you just want to preserve line breaks while copying, you can do it quite easily:
```javascript
document.addEventListener('copy', () => {
	const text = window.getSelection().toString()
	if (navigator.clipboard) {
		navigator.clipboard.writeText(text)
  }
})
```
However, there are 2 downsides:
1. It doesn't work in older browsers.
2. It doesn't preserve HTML formatting.

**Comment by zadam** [comment]
There's a new keyboard action "CopyWithoutFormatting" with default keybindings "CTRL+ALT+C"
