### ISSUE TITLE
SVG Support & MathJax

### ISSUE THREAD

**Issue by Abourass** [zadam/trilium#351]
I have been absolutely adoring my time with Trillium, however, when making notes on the math behind coupling (software eng), I found out that Trillium doesn't support SVG! If you've ever been a wiki page that has mathematical functions, they are svg generated using the MathJax Library. If it's possible to integrate SVG support (and maybe one day the ability to generate SVG for mathematical functions), I would be eternally grateful.

**Comment by Abourass** [comment]
Alright, so I just realized that since they are black in font, and I was using the dark theme, they did paste in correctly, so SVG do work, I apologize. I set figures to have their background color be white (by setting them to black since dark mode inverts). Going to keep this open for MathJax support though.

**Comment by zadam** [comment]
Some kind of math support is definitely high up on priority list, but the problem is right now there's no good way to implement it (at least without a lot of time commitment). 

The way I'd like to have this done is to be able to insert math content into a standard text note via something like equation editor where you'd put latex or something - something like this actually: https://ckeditor.com/cke4/addon/mathjax There's no such addon for CKEditor 5 yet and it's not something I can afford doing myself so I'm kind of waiting until somebody will do it ...

**Comment by Abourass** [comment]
I *was* using ckeditor here at my job for rich-text in our main application until I switched to Summernote (mostly due to not using most of CK's features and it having a large footprint), however, I think I could probably do that in my spare time. I'll take a look at what it would take to create said add on.

**Comment by Abourass** [comment]
Totally understandable. From what I can tell, summernote doesn't seem like it would take to poking around with it's internals too well. We just use it for people writing reports (kinda resume style) so basic is fine. CKeditor 5 was really nice though. I just got off work, so I will start work on the CK addon right now. 
As a quick aside, any thoughts on QuillJS? https://quilljs.com/

**Comment by zadam** [comment]
I consider QuillJS and similar ProseMirror to be quality projects based on similar ideas as CKEditor 5 and actually implementing them sooner. The reason I chose CKEditor is because there's a company dedicated to that product with good track record and there's better chance of a rich ecosystem while the other two seem to be significantly smaller.

**Comment by hannesfrank** [comment]
There is https://github.com/isaul32/ckeditor5-math which supports both KaTeX and MathJax as typesetting engines.

**Comment by zadam** [comment]
@hannesfrank wow, that looks very good!

I will take a closer look.

**Comment by jdw1023** [comment]
Any updates about the math support? I am not familiar with node.js and javascript, but I managed to add math support using https://github.com/isaul32/ckeditor5-math & katex and it seems to work. 
![image](https://user-images.githubusercontent.com/43763092/85098247-10b38f00-b1c8-11ea-9d48-13194ed5fed1.png)
https://github.com/jdw1023/trilium/commit/eb50f137cfa7956bfb6b7aeae7c25043b079526a
https://github.com/jdw1023/ckeditor5-balloon-block-editor-math/commit/090c54bd8624818705686ec568bfc878490c2805

**Comment by zadam** [comment]
Hi, I'm keeping an eye on this plugin - it seems really promising. The only (smallish) concern is that it's an unofficial plugin and it's a question for the future how it will be maintained.

But otherwise yeah, I do plan to integrate it ...

**Comment by amglez** [comment]
Hi there
I am a new user to trilium. I was interested in maths notes. I found a work around with 
https://jsbin.com/fegeferile/edit?html,output
You can just put the html in a code note and reder note mix, and then include it in any note.
As you can see I am no hacker so I was wondering if this could be made from the server side (https://www.mathjax.org/#gettingstarted) so I would not have to work so much :-)
About add-ons for ckeditor there is wiris, mathtype, that produces mathml and latex (I think) but it works on a rather expensive subscription system, I think.
I hope this is not too stupid o vanal for as I said, I know nothing about programming.

**Comment by zadam** [comment]
math support has been added a while ago.
