### ISSUE TITLE
Feature Request: #note-title should use placeholder instead of value

### ISSUE THREAD

**Issue by Abourass** [zadam/trilium#353]
Where it says new note, if it was a placeholder, then when we create a new note we would not have too delete the 'New Note' title before typing our own.

**Comment by zadam** [comment]
The issue is that I still want the note to have some name by default, because it's difficult to work with notes without names from the UI perspective.

But I actually made a change in 0.28.0-beta which makes this a bit more usable - when a new note is created it's name is set to "new note" but it's also put in selection so if you want to change the name you just start typing and it's automatically overwritten (in this way it works similarly to placeholder). If you don't care about the title right now you can press enter or just click on the text and note still has the name.

**Comment by Abourass** [comment]
That's a perfect solution. Closing this FR. Thank you for the awesome software.
