### ISSUE TITLE
Consistency issue check should send "refresh tree" to client if an issue is found and fixed

### ISSUE THREAD

**Issue by zadam** [zadam/trilium#370]

**Comment by pcause** [comment]
think is saw this on 28.2.  Got a blank screen after start up.  Got this in the logs:

08:02:44.783 INFO  DB ready.
08:02:44.828 INFO  DB size: 88481 KB
08:02:57.487 INFO  GET /
08:02:57.505 INFO  Generated sourceId=3A0mvyWmgEVy
08:02:58.761 INFO  Nothing to push
08:02:59.336 INFO  Pulled 1 changes from /api/sync/changed?lastSyncId=3841 in 559ms
08:02:59.448 INFO  GET /api/app-info
08:02:59.454 INFO  GET /api/tree
08:02:59.456 INFO  GET /api/script/startup
08:02:59.501 INFO  GET /api/options
08:02:59.542 INFO  POST /api/tree/load
08:02:59.551 INFO  ERROR: JS Error: Can't find note "CsUZJmkEwSm8"
08:02:59.825 INFO  Finished pull
08:02:59.849 INFO  Nothing to push
08:03:00.624 INFO  Content hash computation took 68ms
08:03:00.624 INFO  Content hash checks PASSED
08:03:00.648 INFO  Branch pL58i31rEzu6 has been deleted since associated note CsUZJmkEwSm8 is deleted.
08:03:00.662 INFO  Branch 8WymNEwS0JAn has been deleted since associated note CsUZJmkEwSm8 is deleted.
08:03:00.835 INFO  All consistency checks passed (took 213ms)
08:03:01.517 INFO  GET /api/tree

exited and restarted and now i see the tree.

**Comment by zadam** [comment]
fix released in 0.29
