### ISSUE TITLE
It cant handle code formatting at all during import

### ISSUE THREAD

**Issue by gerroon** [zadam/trilium#379]
Hi

I am using it on Linux (desktop) so I imported some .md files and I am sadfully seeing that the code formatting is just plain bad. Please see the attached image for how it looks in Trilium and the formatted  text below  for how it is actually in the .md file (direct copy)

![screenshot_2019-01-23_22-55-46](https://user-images.githubusercontent.com/8519469/51655471-bc858a80-1f94-11e9-823c-0e98f2e66a06.png)

```
    
    import logging
    from logging.config import dictConfig
    
    logging_config = dict(
        version = 1,
        formatters = {
            'f': {'format':
                  '%(asctime)s %(name)-12s %(levelname)-8s %(message)s'}
            },
        handlers = {
            'h': {'class': 'logging.StreamHandler',
                  'formatter': 'f',
                  'level': logging.DEBUG}
            },
        root = {
            'handlers': ['h'],
            'level': logging.DEBUG,
            },
    )
    
    dictConfig(logging_config)
    
    logger = logging.getLogger()
    logger.debug('often makes a very good meal of %s', 'visiting tourists')

```

Also the block quote looks bad with those striped lines even if I fix the code and paste stuff manually. 

Please see if this looks pleasing to you.
![screenshot_2019-01-23_23-02-32](https://user-images.githubusercontent.com/8519469/51655614-551c0a80-1f95-11e9-875a-b25def654894.png)

**Comment by zadam** [comment]
Unfortunately the reason for this is that CKEditor 5 [does not support multi line code blocks yet](https://github.com/ckeditor/ckeditor5/issues/436).

Of course this is far from ideal, but in the mean tie I use (code notes](https://github.com/zadam/trilium/wiki/Code-notes) instead of text, but it's not possible to do this automatically during import.

**Comment by gerroon** [comment]
Thanks for the follow up, I need to do this during import I am trying to convert my Joplin notes to Trillium :(

**Comment by pboos** [comment]
This is the one problem we have that is holding us back from switching :(.
Will try to find a workaround to fix this somehow for now until CKEditor 5 will fix it even nicer.

**Comment by pboos** [comment]
I wrote a python script that updates all `<pre><code>` to `<blockquote><p>`. And as well inside them to replace new lines with `<br/>`. But two problems are there:

1. Selecting the content of that blockquote and then copying the content and pasting it somewhere else does not work. Because copying does not copy the line breaks!! so if i have shell commands in there, it won't work. And I use it a lot for that.
2. It loses the formatting (leading spaces)

Another possible solution would be to 
1. write a script to replace everything in sqlite with the following style:
```<p><code>{</code><br><code>&nbsp; &nbsp;"json": "asdf"</code><br><code>}</code></p>```
2. add a css that renders this nicer than current style (have seen code that does it better, but might break inline code blocks)

But that doesn't look too nice either. And exporting it to markdown doesn't look nice either (for both versions above :( )

Would be really great if this could get fixed in a correct way.  But I guess we have to wait for ckeditor to get this done. Because without being able to import our old stuff (from markdown), it will be a lot of work to exctract all code parts into own notes.

**Comment by pboos** [comment]
Seems like CKEditor5 might soon support code blocks properly :)
https://twitter.com/ckeditor/status/1138803157700624385

**Comment by zadam** [comment]
Yes, I saw the tweet as well. I'll integrate it as soon as it is available.

**Comment by gerroon** [comment]
Is there  any kind of progress or update with this? Will ti ever handle imports? I just did bunch of NOTE.py.md (that has "```python" linesat the top), and all the notes are imported as txt with terrible formatting.

thanks

**Comment by zadam** [comment]
CKEditor should release code blocks support in the coming week(s), Trilium support will follow shortly.

**Comment by zadam** [comment]
0.38 added support for code blocks.
