### ISSUE TITLE
Shared notes sublinks not possible

### ISSUE THREAD

**Issue by r1c05h37** [zadam/trilium#3821]
### Trilium Version

0.59.3

### What operating system are you using?

Windows

### What is your setup?

Local + server sync

### Operating System Version

Windows 11 ver. 22H2

### Description

I have a shared subtree, that has more than one layer ( `Main note / some topic / subtopic` ),
And I wanted to share "subtopic" note as " `https://[domain]/shared/some_topic/subtopic` ". 
Although desktop version allowed the link to include slash (  `#shareAlias="some_topic/subtopic"`  ),
When I go to " `https://[domain]/shared/some_topic/subtopic` " the page returns this:

> `{"message":"Router not found for request /share/ens_wiki/main_planets"}`

**Comment by zadam** [comment]
Hello, I added a note to the wiki that this is not supported.

The reason is that Trilium is meant to work with relative paths - it does not rely on the fact it's published in a document root. If we allow subpaths, then it would also have to modify all paths to point to the application root, e.g. `../../../../styles/...css`.

**Comment by r1c05h37** [comment]
Thanks for the information!

I'll use one-layer links then
