### ISSUE TITLE
[Question] Markdown source editor

### ISSUE THREAD

**Issue by dsu-inf** [zadam/trilium#389]
I don't know if it's possible to edit my note directly in markdown. I am familiar with the markdown syntax and I want to have full control. An markdown editor with preview or something similar. 

For example, look at below note:
![image](https://user-images.githubusercontent.com/45175580/51844137-30b98880-231d-11e9-964f-a0310e78d482.png)

If I export the note in markdown I obtain above text:
```
*   test1

a short description

*   test2

See below my code snippet.

`List<Integer> list = new ArrayList();`

`list.add(1);`

`list.add(2);`
```

and I know for example to remove extra chars after each `*` and to use backtick quotes (**`**) to indicate a span of code I prefer to use the block variant (not on each line).

**Comment by zadam** [comment]
Trilium uses a WYSIWYG editor and doesn't use markdown internally (HTML is used as a storage format). Markdown export/import is meant mostly for interop with other apps.

**Comment by zadam** [comment]
Idea of generic pluggable system is certainly possible but it has its costs - implementation, increased complexity, more UI. And my opinion is that the benefit coming out of this is close to zero - you never need to have plain text as opposed to WYSIWYG and the benefits of Markdown with regards to note taking seem to me very small.

HTML is used as a storage format because it is well specced (especially compared to Markdown ;) ), widely supported and very nicely extensible.

**Comment by dsu-inf** [comment]
Thanks! I have another opinion but this is not important and I don't want to go forward with my arguments to convince you :)
