### ISSUE TITLE
Converting note types result in mambo jambo

### ISSUE THREAD

**Issue by gerroon** [zadam/trilium#396]
I can see changing note type can be a complicated issue but at least from text to md or md to text should be possible without pain

Try this

- New text file (.txt)
- type some text 
- change the type to markdown

You now have mambo jambo in the note. Md is a text format, it should not create bunch of html text in there. It should just convert the content to txt, should not try anything more complicated thing.

**Comment by zadam** [comment]
The fact that there is no conversion between note types is intentional. Markdown is not supported as a text format and doesn't have any special treatment. I really don't want to create an illusion that Trilium supports both wysiwyg and markdown for text.

What you're referring to is a code note of MIME type Markdown. This provides syntax highlighting for markdown (just like for any other code note) and that's it.

**Comment by gerroon** [comment]
Sure, but from the user point of view that is a failed situation, and if the user knows rabbit pee about this stuff, it will all look confusing. Just saying, from the user's perspective.
