### ISSUE TITLE
Option to show noteTitle when protected

### ISSUE THREAD

**Issue by jaroet** [zadam/trilium#397]
It would be nice when the noteTitle of protected notes are visible and included in search results ect.
Most of the time the noteTitle will not be what makes a note worth protecting. And when you are searching for a certain value it would be nice to see it included.
This presumes good desciptive noteTitles offcourse ... An option to enable this would be great.

**Comment by jaroet** [comment]
It would be nice when the noteTitle of protected notes are visible and included in search results ect. 
Most of the time the noteTitle will not be what makes a note worth protecting. And when you are searching for a certain value it would be nice to see it included. 
This presumes good desciptive noteTitles offcourse ... An option to enable this would be nice.

**Comment by zadam** [comment]
Most times I consider note title to be sensitive as well since it gives the information on what's inside the note's content.

But in certain cases I agree you want the title to be visible. For this I use [branch prefix](https://github.com/zadam/trilium/wiki/Tree-concepts#Prefix) which is somewhat similar to note title and is not encrypted (but it also serves another purpose).
