### ISSUE TITLE
Sync notes from other sources

### ISSUE THREAD

**Issue by passionate2023** [zadam/trilium#4000]
### Describe feature

Sync options needed from other sources

1) Sync Notes from https://syncthing.net/ 
2) Google Drive
3) Dropbox

Thanks

**Comment by zadam** [comment]
Sorry, not going to happen. Some rationale is in FAQ: https://github.com/zadam/trilium/wiki/FAQ#can-i-use-dropbox--google-drive--onedrive-to-sync-data-across-multiple-computers

**Comment by passionate2023** [comment]
> I'm not really sure what you mean. Do you mean to backup and/or import notes to/from these sources?

Yes

**Comment by passionate2023** [comment]
@zadam support the sync in the context, is to import text files whichever been placed in the server. a new addition which doesn't exist. I think that is acceptable and doable. The sync which i am talking about file sync between trilium and sync server. so that file will be automatically updated when there is a change in the date/time after pull

**Comment by Nriver** [comment]
The situation you described is suitable for file-based note taking software like VNote, Obsidian, etc. However, Trilium is based on database, it is not possible to sync correctly with 3rd party file-based synchronization softwares.

**Comment by passionate2023** [comment]
I understand it is Database based...However we trilium can have it's own defined format so that the notes will get saved into the db or synced from server. assume the same content has to be updated for 1000 users.

**Comment by zadam** [comment]
It's possible to think of some complicated schemes to make this sort of work. But it's not worth it IMO, and therefore I don't have any such plans.

**Comment by mm21** [comment]
I'm building a third party tool that will accommodate this - you'll be able to sync a folder of notes with metadata (noteId/title/type/mime/attributes) in yaml format. The note content could come from text/binary files or markdown files converted to/from HTML.

In fact the use case I have in mind is reusing and sharing note trees with many people. I'd like to support sharing note trees (reusable templates, extensions, ...) using PyPI, so you could e.g. install an extension just by running a few commands.

**Comment by passionate2023** [comment]
@mm21 That's great and really love to use that...When it will be available or any planned month?

**Comment by mm21** [comment]
It's part of a Python package which I've divided into 3 components, each of which will each build on the previous ones:

Core: High level interface to work with notes/attributes/branches. Provides a way to define notes by subclassing the Note class. Attributes and parents/children can be accessed intuitively. This is about 95% complete coding wise, but I still need to write docs, so I'm hoping this part will be fully done by the end of June. This would be pretty useful if you're a developer and want to write your own custom automation. You can define a hierarchy of notes in Python and sync it to Trilium with just a few lines of code.

Extension: Uses core component to define a way to easily create and share Trilium extensions. An extension is just a Python file with classes which subclass Widget, Template, WorkspaceTemplate, etc. I've found things like attributes and note tree structures can be described very concisely in Python, so it should be really nice to maintain extensions this way. The structure of the extension is automatically generated, with child notes for "Widgets", "Templates", etc. For note content like js/css, you just maintain those files alongside the .py or in whatever folder you prefer.

Sync: Can install Python-defined note trees (one-way sync or "push") and sync (in both directions) arbitrary note trees from various formats. Plugin mechanism used to implement custom formats including markdown conversion to HTML notes, and even more advanced things like processing photos to generate thumbnails. You can also use this to define your own custom folder structures which are parsed into notes. For example, say you have a folder called "Trips" and each folder under it describes a trip, with folders like "Days" and "Photos". Then you can write a custom plugin to convert each .md file under the "Days" folder to a note with a specific template or attributes. Takes a .yaml config file specifying which extensions you want to be installed, which folders you want synced using which plugins, and the destination notes for each.

It will probably be several months at least after the Core component is done before the sync tool is readily available. I think I'd be doing pretty well to get it done by the end of the year. But I'm building it because I need it for my own system - I really think having a local folder of notes that you can maintain in git and sync with Trilium, and maintaining extensions using Python packages, is the ideal way to go.
