### ISSUE TITLE
(Bug report) Whenever I edit the note, the TOC plugin on the right-panel flashes.

### ISSUE THREAD

**Issue by dvai** [zadam/trilium#4094]
### Trilium Version

0.60.3

### What operating system are you using?

Other Linux

### What is your setup?

Local + server sync

### Operating System Version

Web

### Description

When the current number of note headings is less than the number of note headings I set in the settings, and I have added a custom right-panel widget, the table of contents plugin flashes whenever I edit the note. This issue occurs on both the desktop and web versions, and is particularly noticeable on the web version.
![RPReplay_Final1689344395](https://github.com/zadam/trilium/assets/33273040/a98ddfd6-3e98-4c6e-b477-866921ea40a3)

**Comment by SiriusXT** [comment]
From the picture, you have customized the widget that added the right panel. Under normal circumstances, the background toc widget will detect directory changes every time it is edited, and the right panel will only be displayed when the number is greater than the predetermined value, but your custom widget makes the right panel always displayed, which causes each toc When refreshing, the user will be aware of it, but under normal circumstances, the user cannot perceive it because the right panel is hidden. But don't worry, this problem may be fixed in the new version that will be released soon, see: [ https://github.com/zadam/trilium/blob/master/src/public/app/widgets/toc.js](url) Section 87- 90 lines.

**Comment by dvai** [comment]
@SiriusXT I am looking forward to the next version. Thank you for your response！
