### ISSUE TITLE
Ability to create Weekly Notes?

### ISSUE THREAD

**Issue by iwoloschin** [zadam/trilium#416]
Is there a way to rework the "Daily Journal" functionality into something like a "Weekly Journal" or "Monthly Journal" function?  I've been using the daily journal feature for about a month and a half, and while it works well I've found for my use case I'd rather a coarser note granularity, probably at the weekly level, but I could also see a use case where someone might want notes created on a monthly basis.

**Comment by zadam** [comment]
I just exposed existing methods to get "month note" and "year note" to the backend API. Then it would be easy enough to change "Today" scripted button to call `api.getMonthNote()` instead of current `api.getDateNote()`.

"Weekly note" is tricker although I understand it might be a good copromise between too fine grained day and too coarse month. How do you propose these notes should be named? Just e.g. "2019-27" for 27th week of the year?

**Comment by iwoloschin** [comment]
Awesome!

I think your proposal, "Week of the Year", is probably fine.  It might also be nice to support a "First Day of the Week" naming scheme, though it kind of doesn't matter so long as it's chronologically sorted.

**Comment by zadam** [comment]
I added a basic API which will create a note for the first day of the week. It's now pretty clear there might be several desirable configurations:

* configurable start of the week (monday/sunday) - implemented
* name the note by first day of the week or number of the week in a year - missing
* include the name of the day (i.e. "monday") into the note's name - missing
* create week notes directly under year note instead of month notes - missing

**Comment by yanickxia** [comment]
@zadam  Obsidian has weeky note plugin, create weekly note pattern such like '2023-W06'，today trilium has getWeekNote. maybe should add more [Date pattern](https://github.com/zadam/trilium/wiki/Day-notes)
