### ISSUE TITLE
(Bug report) ~shareCss inheritance doesn't work

### ISSUE THREAD

**Issue by deajan** [zadam/trilium#4282]
### Trilium Version

0.61.7-beta

### What operating system are you using?

Windows

### What is your setup?

Local + server sync

### Operating System Version

Windows 10 22H2 x64

### Description

Using a specific stylesheet via `~shareCss` relation works when I declare it in the OwnedAttributes of the note I intend to share.
But if I declare that relation in a parent note and add inheritance, the inherited attribute will show up properly, but the CSS won't be applied nor loaded (navigator console doesn't show any error / missing stuff).

Inherited CSS from 
![image](https://github.com/zadam/trilium/assets/4681318/5a55830f-9672-4766-8400-975dce4535a2)

Of course, I've shared the css note and set it's type as CSS.

**Comment by deajan** [comment]
Still happens on 0.61.8-beta. Sorry to bother, but could be my "killer feature" when sharing my work ;)

**Comment by rauenzi** [comment]
I tested this on 0.61.8-beta with no issues. Can you share some more details on your configuration? How does the attribute look when applied directly?

**Comment by deajan** [comment]
Hmmm, I'd love this to be an "error 40"...

I've created a note at root of trilium like;
![image](https://github.com/zadam/trilium/assets/4681318/b34d5a32-a2b4-4ba2-aab1-b38a4dce2aaa)
Once shared, the root note looks like this:
![image](https://github.com/zadam/trilium/assets/4681318/393c55df-8486-418f-8a47-2da32fa5e7fc)

When I create a subnote of the root note, the `~shareCSS` attribute gets inherited:
![image](https://github.com/zadam/trilium/assets/4681318/64efa447-3c5b-4daf-a740-42bd4f0a5729)
But the share looks like plain share without any CSS:
![image](https://github.com/zadam/trilium/assets/4681318/7016938f-3962-47b7-8ec3-49e6812e5253)

**Comment by deajan** [comment]
I wonder if I have other problems with my database which could explain this, because it doesn't happen on all my notes.
Some inherit css (the same css file) properly.

There are some notes I can't share.
I'll get a 404 not found once shared, or even a problem with sync (#4297).

I guess I have a "bigger" problem with my database (or note content ?), which consistency check / fixes don't find.
I must yet see if exporting, emptying the server, importing my notes in a fresh trilium database could resolve my issue.

**Comment by rauenzi** [comment]
Yeah that might be worth a try if you're experiencing sync or corruption issues of some kind. I was not able to reproduce this following these steps

**Comment by deajan** [comment]
@zadam please see #4297 for the anonymized DB ;)

Btw, it all began while sharing a note called "MariaDB 10.x+"
Can the `.x+` be somehow interpreted perhaps ?

**Comment by zadam** [comment]
Thanks. It appears that this doesn't work because the `shareCss` relation is defined on the root node.

For security, share subtree is sandboxed - only entities from within the shared subtree are processed by the share functionality, which in effect means that inheritable attributes defined on the root note are not inherited to the shared notes. If you want to have attributes inherited for all shared notes, you need to put them on the **shared root** level.

**Comment by deajan** [comment]
@zadam I confirm.
My diag was erroneous because sync stopped working (my other bug #4297 ) so basically I added inheritance but it never synced to server, so never got to see the css.
Thank you for clarifying this. Might be worth adding your above explanation in the wiki sharing page.

**Comment by deajan** [comment]
@zadam Back to this bug, I updated to 0.61.10-beta, and was able to dig more into my issue.

I've narrowed down the issue to the following:

Create a subfolder in root and add the `~shareCSS=mycssfile.css` relation.
```
<root>
  |____FIRSTLEVEL (has sharedCSS(inheritable)=mycssfile.css)
            |____SECONDLEVEL (has inherited sharedCSS property)
```

If I share the FIRSTLEVEL dir, both FIRSTLEVEL and SECONDLEVEL html pages will have CSS properly applied.
If I share the SECONDLEVEL dir, no CSS is applied on it's html page.

**Comment by zadam** [comment]
Yes, this is intentional.

When designing this share functionality, a lot of thinking went into making sure that (potentially) private data doesn't get shared publicly by mistake. 

This is done by "share subsystem" reading only data within the "Shared Notes" subtree.

> If I share the SECONDLEVEL dir, no CSS is applied on it's html page.

Here the `sharedCSS(inheritable)=mycssfile.css` is defined on a non-shared note - i.e. this attribute doesn't exist within "Shared Notes" subtree and thus "share subsystem" doesn't know it exists. Sharing breaks inheritance in the sense of inheriting attributes from outside of shared notes to shared notes (inheritance still works within shared notes).

An example I'm trying to defend against is that people for whatever reason define inheritable attributes on the root level, so that it's available everywhere. But without such break in inheritance, these attributes would be published, likely without the user intending to do so.

I still believe this shouldn't prevent you from using `~shareCss` with inheritance - you can put it e.g. on "Shared Notes" so that all shared notes inherit from it. Or you can put it always on the note you share, so that it's inherited by all children.

**Comment by zadam** [comment]
The second aspect is that the CSS note has to be published as well. Otherwise it's again not present in the "share subsystem" at all.

**Comment by deajan** [comment]
Okay, that makes sense. Again, this could go into the wiki, since it's not clear ;)
Thanks for your time.
