### ISSUE TITLE
Trilium cost 3x memory than OneNote (Feature request) 

### ISSUE THREAD

**Issue by realysy** [zadam/trilium#4283]
### Describe feature

I have thousands of notes in OneNote (2016), and it only cost 120M memory, while there are only 4 notes along with "Trilium Demo" notes in Trilium (0.58.7), and it cost 370M memory. (For both of them, I just open the software and haven't do any edit).

Why Trilium cost so many memory, and is it possible to reduce it?

![图片](https://github.com/zadam/trilium/assets/55436543/dde4e342-2301-4387-8ff0-06f1b21f3d4d)

**Comment by rauenzi** [comment]
I would imagine a majority of the overhead for the memory is due to Trilium being based on [Electron.js](https://electronjs.org/) which essentially runs a slightly-pared-down web browser + Node.js to display the application. That type of overhead is not something Trilium can generally fix, however Electron does make more and more performance improvements like that with each version. And each release, Trilium tends to use a newer and newer version of Electron.

For example, I see you said you are on Trilium 0.58.7, but I am on Trilium 0.60.4 and have at least a couple thousand notes in my trees yet my memory usage is lower than yours:

![image](https://github.com/zadam/trilium/assets/6865942/678b55ed-3754-41d9-9bda-e174dd225794)

And to take it a step further, I checked the actual heap usage of the Trilium app on top of the Electron framework, and even when I opened 10+ `<iframe>` notes at the same time, the heap usage stayed under 30MiB.

![image](https://github.com/zadam/trilium/assets/6865942/10d1f04b-45b3-40c2-8ac9-d6b58bf6b3ab)

So Trilium itself really doesn't have a whole lot of room to slim down. If we compare this to another well-known Electron app like Discord....

![image](https://github.com/zadam/trilium/assets/6865942/7c7c9f1b-6215-4d51-9cf4-d164f16c50ff)
![image](https://github.com/zadam/trilium/assets/6865942/bac3f6f4-187d-4756-b5ba-04bd585d409a)

...then Trilium is easily a landslide winner. So I think Trilium is doing about as well as it can in that regard.

But to your main point, Electron (and thus Trilium) will _never_ have the same kind of minimal memory usage that native apps like OneNote 2016 do, but the tradeoff is being able to write the app once and have it work consistently on all operating systems as well as on the web.

**Comment by realysy** [comment]
Thank you, I'll update.

**Comment by zadam** [comment]
@rauenzi described this well, there isn't much which can be done, so closing ...
