### ISSUE TITLE
(Bug report) Lost data

### ISSUE THREAD

**Issue by codyhatch** [zadam/trilium#4376]
### Trilium Version

0.58.8

### What operating system are you using?

macOS

### What is your setup?

Local + server sync

### Operating System Version

macOS Venturea 13.4.1

### Description

Wed (1st Nov) around 5pm I created a note (id `tS4QvG6jgSI5`) and added some initial content. Then between 6pm and 7:30pm I added a bunch of additional content. On Thu around 3:30pm this additional content was still there.

On Thu (2nd Nov) around 7pm I created another note (id `T0PeIsS1QUhc`), and over the next 30m added a bunch of additional content.

On Friday (3rd Nov) around 11am I discovered that the first note had reverted back to the state it had before 6pm (ie, missing almost all content), and the second note was completely empty.

I checked and I have a `backup-daily.db` created at 11:59pm Thu night, but when I tried to restore it I found both notes were still missing data, suggesting the problem occured sometime during Thu.

I'd love to recover the missing data, but I have a feeling that's likely impossible - but I'm even more interested in ensuring this doesn't happen again; if there's a risk of notes just losing all content I'll have to switch to another tool.

I'm guessing this *may* be related to syncing. I'm using trilium.cc as a sync server, and also have Trilium running on a Windows desktop, although I only used the macOS instance to create, edit, or view notes during this period.

I've attached the for Wed, Thu, and Fri, although as above, I suspect the issue happened on Thu.

I'd welcome input on what went wrong and how I can be confident it won't happen again.

### Error logs

[trilium-2023-11-01.log](https://github.com/zadam/trilium/files/13245755/trilium-2023-11-01.log)
[trilium-2023-11-02.log](https://github.com/zadam/trilium/files/13245756/trilium-2023-11-02.log)
[trilium-2023-11-03.log](https://github.com/zadam/trilium/files/13245757/trilium-2023-11-03.log)

**Comment by abdukir** [comment]
Similar thing happened to me before, but it was because of my client running on my computer had its clock behind the real time. It was my old computer and its CMOS battery was dead, so sometimes it would lose its clock. I was able to recreate the same problem by making my computer's clock earlier than the server's clock. I don't remember the version I was in, and I don't know if there was a fix for it. But since then that happened, I'm using it from the browser directly.

**Comment by zadam** [comment]
@codyhatch I'm sorry for the loss of the data.

This very much sounds like the bug described in #3584, #3829. This bug affected 0.58, versions 0.59 and up should work fine and there hasn't been any such report since.

@abdukir what you're describing is likely a different issue. If the clock between client and server are too different (> 5 minutes), the sync attempts will be rejected. But this shouldn't lead to data loss - the new updates are still stored on the original side of the sync, they just can't get across to the other side.

**Comment by abdukir** [comment]
@zadam thank you for the explanation. My loss wasn't that important but i'll keep in mind what you said. Thanks again ☺️

**Comment by codyhatch** [comment]
Thanks @zadam that does seem like the bug I encountered. Thanks for the clear explanation; that's reassuring.
