### ISSUE TITLE
(Feature request) Code signing on Windows

### ISSUE THREAD

**Issue by eliandoran** [zadam/trilium#4411]
### Describe feature

Attempting to run Trilium Notes for the first time or right after an update prompts the user with this screen from Microsoft Defender SmartScreen:

The user has to press “More info” and then “Run anyway”.

![image](https://github.com/zadam/trilium/assets/21236836/a02b3b26-c6c8-4e0e-b1f1-6acaf85d36a2)

The solution to this seems to sign the application with a digital certificate that is recognized by Microsoft.

**Comment by eliandoran** [comment]
I've took some notes about this subject a while ago. Maybe they could come in useful:

[Code signing.zip](https://github.com/zadam/trilium/files/13284990/Code.signing.zip)

**Comment by eliandoran** [comment]
@rauenzi , I would appreciate it if you could look at potential code signing solutions (please also check the attached .zip file).

I guess the first step is to find a potential platform. I'll cover the costs of the certificate, however @zadam will need to be the one to fill in the details when obtaining the certificate since it's his project after all.

**Comment by rauenzi** [comment]
I looked through what you had in that zip and it aligns with my experience as well. Though I will say another option that exists is [Comodo](https://comodosslstore.com/code-signing) which is a reseller of [Sectigo](https://www.sectigo.com/ssl-certificates-tls/code-signing). That's who I went through for signing our executables for [BetterDiscord](https://betterdiscord.app), but it still has the limitations you noted in one of your notes, in order to completely remove the screen without a trust building up, you have to have a registered business entity with an EV certificate. It's a bit of a pain especially if you don't already have something incorporated.

Another thing to consider to improve end-user trust is having it available in the Microsoft Store on Windows. That could help if a non-EV certificate (or no certificate) is used.

**Comment by deajan** [comment]
I can assist with my company's EV certificate if needed.

**Comment by eliandoran** [comment]
@deajan 's proposal seems interesting. @zadam would you be willing to use a company's extended verification certificate or would you prefer to obtain a non-EV certificate for a physical person (you)?

**Comment by sottey** [comment]
I don't have a stake in this, and I am not saying this isn't a great idea, but I would think that having a third party company's cert vouching forTrilium is potentially problematic. Both for Trilium and for the company.

**Comment by eliandoran** [comment]
Yeah, I think it would be simpler for everyone if we just had a certificate for @zadam . 
@rauenzi , an open-source certificate like the one from Certum wouldn't work?
I think it's much cheaper than a normal certificate, at just [49 EUR](https://shop.certum.eu/open-source-code-signing-on-simplysign.html).

**Comment by deajan** [comment]
> I don't have a stake in this, and I am not saying this isn't a great idea, but I would think that having a third party company's cert vouching forTrilium is potentially problematic. Both for Trilium and for the company.

Why is that ? I use my EV certificate for open source software too. I also use trilium which I vouch for. It is just less pricey to reuse an existing certificate, given that both parties distribute open source anyway.
As long as none of us decides to pack viruses in our executables (which is basically what the EV certificates is supposed to prevent), we're good.

For me, the bigger problem is that EV certificates are physical USB tokens, which means I cannot just give my token to @zadam. I can only sign executables for him which he would have to send me.

The other solution is to setup a funding pool in which we donate for zadam to buy a code signing certificate himeslf.
I bought mine at signmycode.com, which costs roughly 900€ for 3 years, which is a good price IMHO (see https://signmycode.com/sectigo-ev-code-signing).

So I still offer to use my certificate, which has 2,5 years left, so that alost 700€ value which could be used to sponsor @zadam instead of having to buy a certificate ;)

**Comment by rauenzi** [comment]
> Although looking at my notes I see that it mentions that it doesn't remove the "Unknown publisher" message which is not very desirable.

Yeah that's the downside of the open-source. Otherwise it's great, it builds trust easier than an unsigned executable but it still requires the smartscreen

> I don't have a stake in this, and I am not saying this isn't a great idea, but I would think that having a third party company's cert vouching forTrilium is potentially problematic. Both for Trilium and for the company.

I totally understand the concern, but it's actually a fairly common practice for open source projects looking to get their executables signed. Obviously legal association comes into play but that can often be easily mitigated with statements showing no direct affiliation other than supporting open source. That said, I'm not endorsing this specific case here nor am I condemning it.

> The other solution is to setup a funding pool in which we donate for zadam to buy a code signing certificate himeslf.

But unless something has changed, this still requires a business entity correct? Or have they updated that with the requirement of hardware keys? My EV certificate required a business entity but does not require a hardware key (until next renewal).

**Comment by eliandoran** [comment]
@rauenzi , if I understood correctly we can opt for a standard / non-EV certificate.
That one does not remove the Smart Screen immediately, but it does allow us to gain trust which in time will remove the Smart Screen.
The problem we actually have right now is that the Smart Screen trust is not carried over to any updates since it's not signed.
I don't think it's a problem to gain the trust of Smart Screen, provided we don't lose that trust.

**Comment by rauenzi** [comment]
Yes you're completely correct, Elian. It would not require a business entity, would still have some upside in removing the unknown published and unsafe screens, _but_ every newly released binary (update) would need to build its own trust.

**Comment by deajan** [comment]
> Yes you're completely correct, Elian. It would not require a business entity, would still have some upside in removing the unknown published and unsafe screens, _but_ every newly released binary (update) would need to build its own trust.

Since trilium releases are quite frequent, the trust built gets lost quickly, on every release.
I have no idea how much executions it takes for Microsoft to think an executable is trustworthy, but I think the trilium userbase is big enough for enthousiasts to build that trust on every release.
I myself bought the EV certificate only to cope with antivirus programs who think that anything done in python must be a hacker tool :(

> But unless something has changed, this still requires a business entity correct? Or have they updated that with the requirement of hardware keys? My EV certificate required a business entity but does not require a hardware key (until next renewal).

You're correct, EV requires a registered business (had fun with the DUNS number for my EU business). Since june or july 2023, only hardware tokens are accepted for EV certificates.

**Comment by zadam** [comment]
To be frank, this is the part of software/Trilium development which I dislike the most. There are several platforms, each having peculiar requirements and jumping through the hoops. I already resigned from publishing Trilium Sender on Google Play and Trilium Web Clipper on Chrome Web Store because I was getting new requirements (forms to fill, SDK level to upgrade...) monthly.

My ideal fantasy would be that *somebody else* would do the signing and publishing of releases, meaning they would own the whole process, accounts, certificates. @sottey was kind enough to offer to do this for Mac. I think it's not completely unheard of that an open source projects basically provides source releases only and some third party provides binary builds.

**Comment by rauenzi** [comment]
> To be frank, this is the part of software/Trilium development which I dislike the most. 

I definitely agree whole-heartedly. I feel the same way with my own projects. It takes the fun out of actually making the app.

> I think it's not completely unheard of that an open source projects basically provides source releases only and some third party provides binary builds.

It's definitely not unheard of, just takes some setup, trust, and commitment. I unfortunately don't have the time to also do this for Trilium on top of doing this for my own projects. Hopefully someone else is willing to take up that task. In the end, I think code signing is less important for end users than having a proper windows installer like in #4418. I know many users are already accustomed to clicking run anyway for software they intentionally downloaded.

**Comment by sottey** [comment]
Re: me doing this for the Mac, I have not forgotten, life has just gotten in the way. I hope to have this submitted for review this week.

**Comment by deajan** [comment]
> To be frank, this is the part of software/Trilium development which I dislike the most. There are several platforms, each having peculiar requirements and jumping through the hoops. I already resigned from publishing Trilium Sender on Google Play and Trilium Web Clipper on Chrome Web Store because I was getting new requirements (forms to fill, SDK level to upgrade...) monthly.
> 
> My ideal fantasy would be that _somebody else_ would do the signing and publishing of releases, meaning they would own the whole process, accounts, certificates. @sottey was kind enough to offer to do this for Mac. I think it's not completely unheard of that an open source projects basically provides source releases only and some third party provides binary builds.

I can sign and publish the windows ports if needed

**Comment by eliandoran** [comment]
@deajan ,

Sounds good.

I have already started working on the Windows installer and I'll handle code signing as well (albeit in a different PR).

Let me know what the next steps are.

**Comment by deajan** [comment]
@eliandoran As I said earlier, the EV certificate is a physical key.
So the only thing I can propose is to send me the exe files so I can sign them manually. I'd always try my best to sign them the same day.
I'm using [windows_tools.signtool](https://github.com/netinvent/windows_tools) to sign the executables, which I wrote myself a while ago.
The library works with *any* certifcate as long as you have the Windows SDK installed, so you can use it with a different certificate if you have one.

**Comment by eliandoran** [comment]
Closing in favor of https://github.com/TriliumNext/Notes/issues/22.
