### ISSUE TITLE
(Feature request) Add Typst support

### ISSUE THREAD

**Issue by mateocabanal** [zadam/trilium#4460]
### Describe feature

Support rendering the [Typst](typst.app) language in Trillium.

**Comment by zadam** [comment]
This is a matter of CodeMirror support.

**Comment by ovo-Tim** [comment]
I trying to make Typst baked in Trilium's editor, since there currently seems to be no way to do so via extension. Will the community accept it if I open a PR?

**Comment by jbae-89** [comment]
> I trying to make Typst baked in Trilium's editor, since there currently seems to be no way to do so via extension. Will the community accept it if I open a PR?

You could always fork and make the changes, I for one would be interested in using a version with Typst support. 

I feel like it would probably get pulled back into the main project eventually as people learn how much better Typst is than LaTeX.

**Comment by tygorda** [comment]
I think this is a great idea. I've already gotten used to using Typst in Obsidian  (via Obsidian's [Typst Mate plugin](https://github.com/azyarashi/obsidian-typst-mate), and it's frustrating to have to go back to LaTeX formatting for embedded math in Trillium.

@ovo-Tim were you picturing allowing for Typst input instead of LaTeX in the popup that appears when typing `$$` in Trillium, or something else? Also, do you already have a repo we can help with?
