### ISSUE TITLE
Create a docker beta tag

### ISSUE THREAD

**Issue by mrrsm** [zadam/trilium#476]
Currently latest always points to the newest release regardless of if it is beta or stable.
Can the docker images be setup to have the beta tagged versions be pullable via a beta tag in docker?  In turn this would mean the latest tag would point to the latest "stable" release.

This would make it easier to manage upgrading the docker server as I don't have to verify I am going to upgrade to a stable release and not potentially break sync.

**Comment by zadam** [comment]
That's a good point. I'm thinking if the :latest tag should be kept at all since you typically don't want automatic upgrade even between stable minor version - e.g. 0.29 stable to 0.30 stable.

Another option would be to have minor version specific latest tags - so e.g. there would be 0.30-latest and 0.31-latest so upgrade between minor versions would have to be a conscious switch.

**Comment by mrrsm** [comment]
Do you plan on using [Semantic Versioning](https://semver.org/)?  If you are following that philosophy then minor versions should be a safe upgrade.

Ideally I would like to stay as up to date as possible when stable builds come out.  Having a latest tag that points to the latest stable build would be a nice to have for that.  Having specific minor version release tags could be nice but I don't see myself using them as I prefer to be updated to the latest version as development is very rapid at the moment.

**Comment by zadam** [comment]
Strict semantic versioning isn't a good fit for end user GUI applications in my opinion so I don't plan to adopt it.

What is your upgrade workflow? Is it (semi) automatic? For me it seems to me that upgrading to new minor version should be a conscious decision since it can break the sync as all instances should be upgraded at the same time.

**Comment by mrrsm** [comment]
My current upgrade workflow is mostly automatic. I get an alert when the latest tag is ready to update.  I have to manually tell it to run.  When I tell it to run I usually take that time to get the newest desktop release as well so everything stays in sync.  The latest tag just works well in the system I am using because it is still a manual update process that alerts when there are updates to pull.

**Comment by ovizii** [comment]
I'm not sure if this was already implemented but using `zadam/trilium:0.35-latest` I ended up with `0.35.0-beta` 

I didn't expect to end up with a "beta" when asking for the latest version of 0.35 - is this expected behavior? 

What tag should I use if I want the latest but no beta?

**Comment by zadam** [comment]
Hello, sorry for late response.

Yes, this is expected - there's no stable version of 0.35 yet so that's why you cannot get one. If you need a stable version you can use tag `zadam/trilium:0.34-latest`.

Alternatively there's also `zadam/trilium:latest` which is always "latest stable version" (now pointing to 0.34.3.

**Comment by ovizii** [comment]
ah, I see, thanks for clarifying :-)
