### ISSUE TITLE
[Feature Suggestion] Add class or id via attribute

### ISSUE THREAD

**Issue by paulmassen** [zadam/trilium#482]
Hi and thanks for Trilium !

I'm just playing with trilium since this morning and am trying to customize it to fit my needs.
However it looks like in order to style an element, I have to inject a class via javascript.

I thougt it could be easier and more user-friendly to add it via attribute.

Or is it already possible?

Alternatively, a mini-tutorial in the doc which would describe more the process to add it with javascript would be very helpful.
Thanks again,
Paul

**Comment by zadam** [comment]
Hello, on which specific elements do you miss ids/classes? 

But in general it's a big tricky to rely on specific classes/ids and specific HTML structure since that can change between releases. Instead I'm trying to define some basic theming structure with CSS variables which is abstract enough that it shouldn't break in the future - see https://github.com/zadam/trilium/wiki/Themes Of course this can't cover more advanced theming needs, but it can server at least as a base.

**Comment by paulmassen** [comment]
Hi and thanks for your answer. 
Let's say I want to style some elements on a specific tree.
Currently, there is two solutions: 
1: use some tricky css pseudo selector such a nth-child etc.
2: inject a class in the DOM via javascript

in your todo demo, it seems like you use the solution 2, as I can see in your css the .todo class which does not exist in the current html structure, I guess this class is added via javascript.

```
span.fancytree-node.todo .fancytree-title {
  color: red!important;
}
```
however, the documentation does not explain in detail how to add this .todo class as fas as I can see.

Therefore I thought it would have been useful to be able to add a class via attributes in order to enable some easier styling.

**Comment by zadam** [comment]
I see, I misunderstood.

You can add these custom classes by creating label (type of attribute) `cssClass` - in case of these todo items the value is `todo` as you mentioned which is then put into css class of that node in the tree.

**Comment by paulmassen** [comment]
That's exactly what I needed and I don't know how I missed this in the attribute list. Thanks! I'm closing this.
