### ISSUE TITLE
[feature request] last modified date for items in exported tar file

### ISSUE THREAD

**Issue by pcause** [zadam/trilium#487]
It would be helpful if you could set each file's date in the tar file as the date of the last modification.  This allows us to extract the file and then sync to other services with only the changed files being synced.

**Comment by zadam** [comment]
Well, imported notes are considered as totally new ones - they get assigned new IDs etc so there's no connection to the old ones and they will always have to be synced completely. One of the reasons for this is that you might want to import same tar archive multiple times into different places.

And since imported notes are considered as new notes, they get current dateCreated and dateModified.

**Comment by pcause** [comment]
Sorry if I wasn't clear, I am talking about exported notes.  If I change a note in trilium and export I'd like to see the time in the archive be the time when I changed it.  I can then extract all the files to a temp location and rsync or use other tech to place only the changed notes on other systems where I don't have trilium.

**Comment by zadam** [comment]
Oh, I see. That would be possible, yes.
