### ISSUE TITLE
How to apply force CSS the style applied to a note to child-overview-item and note-title?

### ISSUE THREAD

**Issue by ma-sadeghi** [zadam/trilium#524]
Basically, my notes are in two different languages, one left-to-right and the other one right-to-left. I want each of the to appear in a different font. The way I currently do this is to define a CSS note like the one below

```
.farsi {
    font-family : B Yekan, Tahoma, Arial, Times;
    font-size : 1.2em;
}
```

which effectively applies a certain font to notes with `class=farsi`. I manually apply `class=farsi` as attribute to the notes I want and so far it works. The only issue is that I also want `child-overview-item` and `note-title` fields to also inherit `class=farsi` so they also appear in the desired font.

I'd appreciate if you could let me know whether there's a workaround or even a better way to achieve this.

Thanks!
Amin

**Comment by zadam** [comment]
Hello, generally you're using correct approach, but what you want to do is just not implemented at the moment, because the `cssClass` attribute is applied only at the note tree.

However for 0.32 I'm working on a refactoring (required for tabs implementation) and `cssClass` should be applied also for whole right side - container of note title, content, attributes etc. Beta of 0.32 will come out quite soon.
