### ISSUE TITLE
Create a new note with ctrl L if none exist

### ISSUE THREAD

**Issue by quesada** [zadam/trilium#526]
For my workflow of creating lots of note links, Create a new note with ctrl L if none exist would work wonders. This is how zim works, and I think it's a great UX decision.

**Comment by zadam** [comment]
I can see how this might be useful, but where would note be created in the tree hierarchy?

**Comment by wesrer** [comment]
I personally think the new note should be a sibling, but I can also see an argument for children, so I think the best approach might be to make this a configurable setting?

**Comment by quesada** [comment]
Any updates on this idea? it's the one thing that is preventing me to move from zim (and typing latency, which is horrible on any electron app, I guess)

**Comment by quesada** [comment]
I'm happy with the note being a sibling, FWIW

**Comment by zadam** [comment]
I'm not opposed to the idea, but I also don't have any fixed plans yet. It's not obvious to me how to implement this - one variant of this feature is that you're able to link to note which doesn't exist yet, presumably based on (future) note's name. But Trilium note name is not a unique identifier, that's why links are against noteId (but that does not exist for not existing notes).

Another variant would be allowing to create a link and the respective note at the same time. This would be easier in terms of not having to link against non-existing notes, but I think it doesn't exactly cover all the use cases.

**Comment by mbafford** [comment]
@zadam @quesada as of `0.45.7` this seems to be implemented. When I use ctrl+L `addLinkToText` it offers me the option to `create child note and link text`.

<img width="271" alt="2021_01_08_11_12_49" src="https://user-images.githubusercontent.com/713813/104037270-79814980-51a2-11eb-9464-5a49f1384416.png">

Should this be marked as resolved?

**Comment by zadam** [comment]
Yes, this is implemented so closing ...
