### ISSUE TITLE
Table of contents

### ISSUE THREAD

**Issue by barsanuphe** [zadam/trilium#533]
It would be nice if there was an option to toggle a table of contents for a given text node. It would allow efficient navigation in long, well structured notes. 

(recent user, sorry if such a thing already exists and I missed it)

**Comment by zadam** [comment]
Hello, personally I prefer to have smaller notes which are structured in the note tree as opposed to long documents structured by headings. But of course this might not be always applicable.

Table of contents is currently not supported. It's actually more of a feature in the editing component and adding this is [tracked on CKEditor's project](https://github.com/ckeditor/ckeditor5/issues/966). Once they add support for ToC, I'll definitely consider adding it to Trilium.

**Comment by barsanuphe** [comment]
Thanks for the quick response, I'll track the CKEditor feature request then!

**Comment by jaroet** [comment]
Hello,
I also prefer using multiple smaller notes in a subtree. When a note (say the main note in a subtree) has no content the underlying notes are currently shown in a grid view, using 0.37.2.

Although nice I find that un-easy to navigate. As you read the underlying notes already (name and content) I guess it would be relatively easy to generate a Table of Content of underlying notes (only names) with correct indentation showing the level in the subtree. 

This makes navigating/overviewing a subtree relatively easy instead of using the tree. Might be a small enahancement. It will keep the tree for high level navigation with detail navigation for the current subtree in the note itself. If the depth of subtree level could be configured (1 level, 2 or even 3 level) that would be great. 

And if it could be added manually even better. So a short descriptive note about this subtree followed by a Table of Content.

**Comment by leeyaunlong** [comment]
> Hello, personally I prefer to have smaller notes which are structured in the note tree as opposed to long documents structured by headings. But of course this might not be always applicable.
> 
> Table of contents is currently not supported. It's actually more of a feature in the editing component and adding this is [tracked on CKEditor's project](https://github.com/ckeditor/ckeditor5/issues/966). Once they add support for ToC, I'll definitely consider adding it to Trilium.

it seems theckeditor finished this function: https://github.com/ckeditor/ckeditor5/issues/1942

**Comment by zadam** [comment]
It was closed as duplicate, the real issue is this: ckeditor/ckeditor5#966

**Comment by Pascalio** [comment]
Hello! Sorry to bump this issue.
I'm not sure if the original request was meant so, but rather than having a table of content at the beginning of the document it would be neat to have a ToC view in a side pane - or a pop-up... ToC at the beginning of the document is good to quickly jump somewhere when you open it, but no good for navigation back and forth in it.
Besides, I see the idea of having small notes in a subtree, this is great too; but it's no good when you need to edit many sections kind of simultaneously, taking a line from under that section to under this one, transforming lines under different sections according to each other, copying a line quickly from one section to another... All of this is easier with long documents with headings rather than with a subtree of notes, since the overview doesn't allow edition in subnotes, which is needed for the above...
Alternatively, maybe editing the subnotes from the overview, without leaving this overview, maybe this could be an alternative solution...?

**Comment by perfectra1n** [comment]
This would be an absolutely killer feature for notes that go on longer than originally intended. Again, love the work you do zadam, thanks for making the wonderful application.

**Comment by archonic** [comment]
I believe this can be closed as a duplicate. Feel free to upvote the original request here: https://github.com/ckeditor/ckeditor5/issues/966

**Comment by antoniotejada** [comment]
FWIW I wrote a simple but fully featured ToC widget plugin
- The ToC is live and automatically updated as new headers are added to the note.
- Clicking on the ToC navigates the note.

![image](https://user-images.githubusercontent.com/6446344/163854892-3d678c76-294e-4e7b-a947-b672f8519fe3.png)

https://gist.github.com/antoniotejada/54940b85d456ed3f0e6c99f915b435fe

**Comment by sigaloid** [comment]
That widget is awesome! You should post it to the discussions: https://github.com/zadam/trilium/discussions/new?category=show-and-tell

**Comment by antoniotejada** [comment]
> That widget is awesome! You should post it to the discussions: https://github.com/zadam/trilium/discussions/new?category=show-and-tell

Thanks and done! https://github.com/zadam/trilium/discussions/2799

**Comment by archonic** [comment]
Good stuff @antoniotejada! I'll give it a spin.

**Comment by finzzz** [comment]
@antoniotejada Thank you!! 
One thing I would like to add suggestion is that,
When I only have H3 and H6 in the note, 
```
### TITLE
###### SUB1
###### SUB2
```
it renders into
```
Table of Contents
1. TITLE
                            1. SUB1
                            2. SUB2
```
Is it possible to make it automatically adjust the tab and also configure numbering, like so:
```
Table of Contents
- TITLE
  - SUB1
  - SUB2
```

**Comment by antoniotejada** [comment]
@finzzz 

> One thing I would like to add suggestion is that, When I only have H3 and H6 in the note,
> Is it possible to make it automatically adjusts the tab and also configure numbering, like so:

Not really inclined to do that, and sounds messy, it's not just checking the next entry, you would need to check the whole table to see that the level is really missing in all entries of the table.

Out of curiosity, why do you skip levels like that?

**Comment by finzzz** [comment]
@antoniotejada 
It's my habit to skip 2/3 levels of heading when I'm not sure if I would add new main heading in the future.
For example, if I would take this kind of note about postgresql:
```
#### Installation
#### Administration
```
Then along the way adding new header to it
```
### Common
#### Installation
#### Administration
### Specific Ops
#### A
### Errors
#### B
```
If I don't do that, I would have to edit the entire note from
```
## Installation
## Administration
```
to
```
## Common
### Installation
### Administration
## Specific Ops
### A
## Errors
### B
```

**Comment by zadam** [comment]
Added in 0.53.X
