### ISSUE TITLE
ctrl + alt + p always opens note in new tab

### ISSUE THREAD

**Issue by bwat47** [zadam/trilium#556]
Steps to Re-create (in version 0.32)
1. select any note
2. Then, use ctrl + alt + p shortcut to create a new day note

Expected: Should switch existing tab to the new note (this is how other shortcuts to create notes, e.g. ctrl + o and ctrl + p behave)

Actual: It opens the day note in a new tab next to the selected note

**Comment by zadam** [comment]
This is actually intentional - ctrl-alt-p is special in the sense that it's a global shortcut - e.g. you can work in some other window in another app and you can use ctrl-alt-p to quickly jump to Trilium and create new note. But that kind of hides the context of what you were doing before in Trilium (the previously activate page). In this sense I'm trying to make ctrl-alt-p "safe".

ctrl+o and ctrl+p are different in the sense that they work only locally - so when you use them you must be already in the Trilium window so you're aware of what note you're switching from. I was considering also "new tab" variants of these, but didn't add them for now.

I understand that the new behavior may seem inconsistent when used inside the Trilium window though. But it didn't occur to me that it could be seen as a problem ...

The ultimate goal is to have these shortcuts more easily configurable.

**Comment by bwat47** [comment]
Interesting, I actually did not realize that this was a global shortcut! Knowing that it's global, the behavior does make sense to me

Initially, I didn't realize it was global, so I was always invoking it from within the trilium window, and in that case the behavior seemed inconsistent
