### ISSUE TITLE
Can no longer drag/drop multiple notes at once (v 0.32)

### ISSUE THREAD

**Issue by bwat47** [zadam/trilium#565]
It used to be that you could use ctrl + click to multi-select notes, and (still holding ctrl) you could drag and drop them to move multiple notes at once (see: #400)

Since v 0.32, I see that ctrl + click no longer multi-selects (instead it opens notes in new tabs)

I can still multi-select with Shift + click, however, holding shift while moving notes still results in just one of the selected notes being moved.

I've also tried holding ctrl while moving notes (after multi-selecting with shift + click), but in v 0.32 this also results in just one of the selected notes being moved

**Comment by bwat47** [comment]
as a workaround, I do see that ctrl +x to cut the notes and ctrl + v to paste them works

**Comment by zadam** [comment]
Hello, thank you for reporting this issue.

It's true that the CTRL modifier has been changed to SHIFT because CTRL is now used for tab operations. However, as you noticed, it doesn't actually work as intended.

I've been pretty unhappy with the way drag & drop, selection etc. works and intended to fix that - I finally did that today after seeing your bug report. There's bunch of small changes in behavior - you might notice that it won't necessary to hold CTRL (or SHIFT) to drag multiple items now.

Changes are too large for a patch release in 0.32 so it will be available in 0.33 beta (coming soon). In the meantime you can use CTRL-X, CTRL-V workaround you found.
