### ISSUE TITLE
[Feature Request] bi-directional internal links

### ISSUE THREAD

**Issue by pcause** [zadam/trilium#566]
I use the internal links capability to link an item to a location or tag item in the todo branch.  I'd like to have an easy way to create a link in that target back to the original item.  Perhaps if I create an internal link you store the note name and id and then there would be a menu item to "link back" that would paste the note name and use the id to create the link back.  I can see this being useful for other cases.

**Comment by zadam** [comment]
It's not exactly what you want, but I find this back linking pretty easy in practice. Let's say you have pages A and B:

* you're on page A, press CTRL-L, type B and create a link
* double click (or open in new tab) on link to B, now you're on B
* press CTRL-L, now because the autocomplete by default lists recent notes, page A is on the first place, you just select and confirm and you have link back

**Comment by pcause** [comment]
Actually, I had another tought, after looking at the link map.  What if I used a relationship map for todos.  There would be 3 kinds of templates: todo, location and tag. a todo item has links to/from the locations and tags.  hierarchies of todos can be created and we could have a projects and sub-projects in todos.

might play with the script for this a bit.
