### ISSUE TITLE
deleting protected notes

### ISSUE THREAD

**Issue by legion1978** [zadam/trilium#579]
hello
i should not be able to interact (delete, add notes, subnotes) with a protected note or subnote without entering the password.

**Comment by zadam** [comment]
Hello, protected notes provide only confidentiality (and partially integrity) guarantees. You can still delete them, move them elsewhere etc. This is done because a) such extra protection would bring some extra complexities b) it's inherently UI-only protection since nothing prevents you from opening the SQLite document in e.g. SQLiteBrowser (outside of Trilium) and e.g. delete the notes there.

**Comment by legion1978** [comment]
understood
