### ISSUE TITLE
Images in HTML export broken

### ISSUE THREAD

**Issue by Karol-G** [zadam/trilium#586]
Hi,

I like to insert images into Trillium by using Snipping Tool via copy & paste. (A default windows application)
However when exporting my nodes as HTML, all of the images are corrupted and none are shown.
It seems Snipping Tool names every image simply "image", which confuses Trillium.
This is how a directory with images looks like that has been exportet as HTML:
![grafik](https://user-images.githubusercontent.com/3471895/60792359-dba05f00-a165-11e9-8004-b8d1356a2392.png)

App version: 0.30.5

**Comment by zadam** [comment]
Hello, in what way are the images corrupted? I mean most of them have incorrect extension (like .png_5) which should be fixed, but if you rename them, then you should still be able to open them, right?

The underlying problem is that when you use snipping tool, there's no file so there's no filename - trilium then uses "image" name as the default, but then this naming is not ideal when you create multiple such screenshots in one note.

I'll do some more testing of this use case since current state does not seem ideal ...

**Comment by Karol-G** [comment]
Renaming would not solve this problem. Every image would then be named "image.png", which is not possible due to duplicate names and second the filename in the HTML source seems to be wrong too. In the source  it says the image would be located in 

> api/images/pjbhcVG7OYrh/Unbenannt.png

However this location does not exists and the image is actually located in a different directory.
In addition it is called "Unbekannt" which is german for "unknown". I have no idea why the image is suddenly called "Unbenannt.png" in the source when it is called "image" in the directory.

It is probably best if you try to reproduce the bug yourself^^

**Comment by zadam** [comment]
tar export provides correct links to images since a few versions ago.
