### ISSUE TITLE
How do I replace the password in the desktop app?

### ISSUE THREAD

**Issue by gerroon** [zadam/trilium#595]
Hi

I changed my sync/login password in the web app. However the desktop apps still syncs with the old passwords? And I cant find a way to replace the old password in the desktop app. 

Is this also a security issue?

**Comment by zadam** [comment]
Hello, it's enough to change the password on one side (in the webapp) and the change is automatically propagated to the desktop via sync. That's because password is actually not authorizing the sync, but only access to the app itself (in the webapp) and access to the protected notes.

On the other hand sync between two instances is authorized by the virtue of being actually the same document, just on two different places. When a new document is created in the initial setup, there's an internal cryptographic token generated (called "documentSecret") which is unique for the document. When you then setup your sync between server and desktop, you need to enter credentials - this is for initial sync handshake only which will distribute the documentSecret to both sides of the sync. This handshake is then valid "for life" and password change does not affect it.

**Comment by gerroon** [comment]
Hi

That makes sense. That makes my life easier for sure however  I hope that there are no security issues in the way that is setup.
