### ISSUE TITLE
Consider implementing something like bookmarks

### ISSUE THREAD

**Issue by zadam** [zadam/trilium#596]
Originally I was resisting this feature since I thought you can just clone your notes wherever and also using jump-to dialog is fast enough. But the tree can be jumping around and scrolling to where you want to be can take time.

* intended for very limited number of items (up to 10)
* show up in collapsible sidebar (left of right)
* can be a note or script
* controlled through label
  * not clear how the bookmark list should be updated after note is bookmarked
  * not clear how the ordering should work - maybe just value of the label

**Comment by ThomasWeber** [comment]
Another thing that would help this issie, I was thinking it would be nice if Trilium remembered the cursor position in your notes, and if you leave that note and return, it could return you right to back to that position, instead of resetting you to the top of the page. I've seen this functionality in other notetaking apps like OneNote and it is pretty handy.

**Comment by zadam** [comment]
Yes, I have thought about that a few times, but there are bunch of unclear things - e.g. should it behave like a browser which remembers the position only when using history (back/forwards).

In general the issue is I believe partially mitigated by having tabs - so if you need to work with multiple notes you can just open them in tabs instead of switching back and forth.

**Comment by zadam** [comment]
implemented in 0.48
