### ISSUE TITLE
[BUG] Can't get sync server to authorize desktop

### ISSUE THREAD

**Issue by Belphemur** [zadam/trilium#597]
# Version
Using v0.34.0-Beta on both desktop and server.

# Steps
1. Have data existing on Server
1. Setup new Trilium on Desktop with a sync on the server.
1.  Use the right credentials to set up desktop trilium
1. Can't authorize 
 ```
10:02:58.396 INFO  sync failed: Request to GET https://trilium.domain.com/api/sync/changed?lastSyncId=0 failed, error: 401 Error: Request to GET https://trilium.domain.com/api/sync/changed?lastSyncId=0 failed, error: 401 
    at generateError (C:\Users\Antoine\Documents\trilium-windows-x64\resources\app.asar\src\services\request.js:115:12)
    at ClientRequest.<anonymous> (C:\Users\Antoine\Documents\trilium-windows-x64\resources\app.asar\src\services\request.js:61:28)
    at ClientRequest.emit (events.js:200:13)
    at URLRequest.<anonymous> (C:\Users\Antoine\Documents\trilium-windows-x64\resources\electron.asar\browser\api\net.js:221:18)
    at URLRequest.emit (events.js:200:13) 
```
# Server log
`Jul 25 10:02:56 dolma trilium[24949]: Serving sync seed.`
# More Info
Username contains a uppercase character. Like : Belphemur.

# Solution Tried
1. Change password to remove special chars
    * Didn't change the problem
1. Restart server
    * No change
1. Go with browser on URL
    * When connected, URL does return all the syncs needed.

**Comment by zadam** [comment]
That's a bit of a mystery.

I assume that sync worked before for you. What version did you use before? 

There hasn't been any changes in sync for some time. Also it's really strange that's it's failing with 401 at that place since this happens after the sync client successfully authenticates to the server. 

So I'm wondering if it might be caused by some external thing. Is there maybe some proxy/firewall between you and the sync server?

**Comment by Belphemur** [comment]
Actually it's the first time I tried the sync.

I'm having a nginx reverse-proxy in front, but until now I never had any issue with it ...

**Comment by cmuench** [comment]
I have a similar setup with a Traefik Reverse Proxy and also got 401.
I was not able to connect from my Mac to the Linux Server.
After changing the password the connect worked.
Before: 50 char long password with special characters. Now a 30 char long password containing letters and digits.

**Comment by Belphemur** [comment]
I admit I have a pretty secure password.

It's weird that the password would get truncated ?

**Comment by safesparrow** [comment]
I'm having exactly the same problem, although changing password to a rather short (and unsafe one without special chars or numbers) doesn't make it go away.

- Web version is fine
- When doing 'Test sync' the popup says 'Sync server handshake has been successful, sync has been started.', but the server's logs say `PUT /api/sync/update rejected with 401 Not authorized `
- I was able to do the initial sync, but have changed the setup since then

My current setup is:
- desktop is connecting to `https://{hostname}:8443`
- Cloudflare serves as DNS server, and provides SSL certificate for the domain
- The domain resolves to my server using A record
- Server's Nginx uses Origin CA key provided by Cloudflare to secure the connection between Cloudflare and server
- Requests on the server's 8443 are routed through to a local port 8085
- 8085 is then mapped to the port of Trilium docker container running

I *think* that the initial sync worked at the time when I was connecting directly using IP address of the server and not using HTTPS at all

**Comment by zadam** [comment]
Thanks for the detailed description. Based on what I see this has nothing to do with password since that was accepted and sync initiated.

Sync is a process composed of several steps, first 2 are:

1. sync client is authenticating to the server, if successful then authenticated session is created on the server (password is not used here anymore, authentication is done using an internal document secret)
2. if successful, client starts pushing and pulling changes

From the logs, the sync fails on the second step which means that the first step (sync auth) happened correctly. 401 Not authenticated means that client does not have authenticated session (which it should have from step 1 though).

This tells me that there is some issue in session handling - either the session cookie is not coming through from the client to the server (possibly some proxy is stripping it) or perhaps the sessions are not being stored correctly? (should be in `/trilium-sessions` in OS temp directory)

I had some reports that sync did not work with reverse proxy or similar setups and started working when trilium was exposed directly (e.g. #748)

**Comment by safesparrow** [comment]
I can confirm that Nginx alone is not the problem.
Doing IP Address over HTTP -> Nginx -> localhost port -> Trilium container :8080 works just fine.
So it's either Cloudflare or the fact of using Nginx with SSL

**Comment by zadam** [comment]
For what it's worth I'm using nginx + SSL (let's encrypt) myself without trouble.

**Comment by affectiosus** [comment]
I have a similar problem: can't get desktop-server (both are `0.41.6`) sync to work.

Log on the desktop:
```
12:39:19.740 INFO  sync failed: Request to POST https://{{instance}}/trilium/api/login/sync failed, error: 400 Bad RequestError: Request to POST https://{{instance}}/trilium/api/login/sync failed, error: 400 Bad Request
    at generateError ({{trilium-dir}}\resources\app.asar\src\services\request.js:170:12)
    at ClientRequest.<anonymous> ({{trilium-dir}}\resources\app.asar\src\services\request.js:52:28)
    at ClientRequest.emit (events.js:223:5)
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:2553:12)
    at SimpleURLLoaderWrapper.emit (events.js:223:5)
```

And on the server:
```
09:39:52.153 INFO  POST /api/login/sync 
09:39:52.160 INFO  POST /api/login/sync returned 400 with response {"message":"Sync login credentials are incorrect."}
```

The setup on the server is a nginx reverse proxy to docker container: `/trilium` > `127.0.0.1:5051` > container port `8080`, SSL on the server is configured and valid.

I'm pretty certain that I use the same username-password combo in both instances. What bugs me is that I'm getting `400` instead of `401`, so the sync appears to be failing on different step. Any ideas what I can do here?

**Comment by zadam** [comment]
> I'm pretty certain that I use the same username-password combo in both instances.

Hello, this sounds like you have already two set up instances (as you mention you use same credentials in both) and you're trying to set up sync between them. 

But this is not possible - you can set up sync only between one already set up instance and one "empty" instance so that the empty one will be filled with the data from the already set up instance.

**Comment by affectiosus** [comment]
Indeed, it does work now. Thank you.
