### ISSUE TITLE
Issue with alignment in Mac 

### ISSUE THREAD

**Issue by mphat10** [zadam/trilium#604]
How to align content to the one side of the page and redistributes any empty space at the end of lines to between the words in the paragraph(s).

<img width="893" alt="Screen Shot 2019-08-01 at 05 27 16" src="https://user-images.githubusercontent.com/20958000/62245700-1ae86580-b41d-11e9-9003-90859526490a.png">

**Comment by zadam** [comment]
I think you mean is "justified text" - lines are aligned to both left and right and empty space is distributed between words. I tried that and it's quite nice for the reading but I don't think it's good for writing text because text/cursor can jump a bit unexpectedly.

However trilium is quite "hackable" - you can create [custom CSS](https://github.com/zadam/trilium/wiki/Themes#custom-css) with following:

```css
.note-detail-component-wrapper {
    text-align: justify;
}
```

BTW, in 0.34.2 I fixed the issue visible on your screenshot which makes line breaks in the middle of the word.
