### ISSUE TITLE
Renaming promoted attributes

### ISSUE THREAD

**Issue by belisama** [zadam/trilium#608]
Scenario: I create a node and give it an inherited, promoted label definition. I create a couple of children nodes and fill in the attribute value. Then I realize that the definition is misspelt and so I go back to the parent node's attribute dialog and fix them. Eep! All the children nodes have lost the attribute values I just filled in!

Given the name=value set-up, I can totally see how this would happen (and, fortunately, when I found it there were just a couple of nodes affected), but it's a major data loss waiting to happen. If the renaming can't be handled gracefully, then those fields need to be locked against accidental editing and unlocking them should pop-up a great big, ole warning dialog.

**Comment by zadam** [comment]
If I understand correctly the flow you describe then the attribute values should not be lost, they just lost promoted status (since the name now doesn't match with the parent's promoted attr) so they are not displayed as promoted, but if you go to the attributes dialog they should still be there.

I understand that defining promoted attributes can be kind of awkward, but it's quite low level and advanced feature. Currently the only way to rename attributes in bulk would be through script API.

**Comment by belisama** [comment]
Ah, okay, did some more poking about and you're quite right. So that's much less bad than I thought, more of a "mention it in the docco" level thing. Thanks for the quick reply. If I worked up an attribute renaming script (because I *know* I'll  end up typo-ing something again and need to fix it), is there a place to share it?
