### ISSUE TITLE
Has the Sync Server to run as root?

### ISSUE THREAD

**Issue by HGieselmann** [zadam/trilium#620]
Hi.
I am sorry if this is trivial, but I saw this app and had to try it, but I am not very deep into linux.
I set up a Sync Server manually and it works fine as long as I run it as root.

If I run it from a regular user the website returns a "500 Internal Server Error" after Login and Sync from the app won't work as well.

Are there additional steps required to make that work, which are missing on the Help file?

Thanks so much.

**Comment by zadam** [comment]
Hi, not sure what this could be, maybe some filesystem permissions? Are there any logs in ~/trilium-data/logs?

**Comment by HGieselmann** [comment]
Hi!
Thanks for the reply, yeah.
It throws:
INFO ERROR: Error executing transaction, execuing rollback. Inner stack: Error: Option username doen't exist at Object.getOption(.../trilium/src/services/opotions.js7:15)
As this concerns the username, the username works when running as root.

![20190822_TriliumRootError](https://user-images.githubusercontent.com/24554515/63539187-cc108600-c519-11e9-9a8b-ed5be05c0f31.jpg)

**Comment by zadam** [comment]
One thing I can think of is that the `trilium-data` is by default in home directory (`.local/share`).

If you run it from a different user (root), then the app uses different data (from different home dir).

The log you posted looks like from a DB with unfinished sync somehow. I would try to move the root's trilium-data folder to your user's home since the root's data seem to work ...

**Comment by HGieselmann** [comment]
Hey,
Thanks so much, that kinda worked.
In the end I just got rid of all trilium-data folders and reconfigured the server after starting it form the non-root user. Works like a charm!
Great work on this tool!
