### ISSUE TITLE
Feature Request: Encrypt document.db

### ISSUE THREAD

**Issue by ttlequals0** [zadam/trilium#626]
Do you have any plans on adding encryption of all content stored in document.db? This would be a huge plus to this tool, as of now you can simply grep for strings stored within the DB.

**Comment by zadam** [comment]
Hello, Trilium uses a more fine-grained method where you choose only certain notes which should be encrypted - this is called [protected note](https://github.com/zadam/trilium/wiki/Protected-notes).

Full DB encryption might be easily done using a full disk encryption though.

**Comment by zadam** [comment]
Application would have to ask the user for the password here as well since the encryption key would have to be derived from the password as well (no point in encrypting the document if we store the key next to it). So it kind of seems like a usability hurdle to always require password even for less sensitive notes ...

It's kind of possible to encrypt all notes by default - protected status is taken from the parent note during the note creation so when you protect the root note, then you'll be always protecting child notes as well. But Trilium is not exactly geared towards this use case so the usability would not be great.
