### ISSUE TITLE
[Feature Request] Also include TinyMCE WYSIWYG editor

### ISSUE THREAD

**Issue by discernment** [zadam/trilium#678]
TinyMCE is another popular OpenSource WYSIWYG editor.  There is a demo [here](https://www.tiny.cloud/docs/demo/full-featured/#fullfeaturednon-premiumplugins).  Would it be possible to add an option to choose which WYSIWYG editor to use?  TinyMCE has some features lacking in CKEditor.  Here are some examples:

1. Hitting the down arrow in a table in CKEditor causes it go to the next column instead of the next row in Chrome, but not in Firefox.  This is an [open issue a year old](https://github.com/ckeditor/ckeditor5/issues/3227).  This is not an issue in TinyMCE.
2. TinyMCE has a mode to allow the user to directly edit the HTML.
3. The current configuration of CKEditor doesn't seem to allow images to justify left.  It's always stuck at the center.  TinyMCE has options to justify left, right or center for each individual image.
4. TinyMCE can import a pasted image directly into the HTML as a base64 blob instead of making a new sub-note.

There may be some ways that CKEditor is better but TinyMCE does have some advantages.  It'd be wonderful to see either editor as an option (maybe a tab on the note detail or a global setting).

**Comment by zadam** [comment]
1) and 3) I consider issues which will be hopefully addressed in the future

2) I don't really consider this a problem in the scope of note taking and I'm in agreement with the CKEditor team motivation for this limitation

4) I think CKEditor supports this, but the build in trilium is setup so that the upload is triggered instead of pasting the image inline as base64

In the ideal world where people have unlimited time it would make sense to offer a different text editor. But for me it just seems like not wise way to invest the time - it's not just setting up the editor itself, but there are various integrations (add trilium link, upload image, insert markdown etc.) which need to be handcrafted for a particular editor.
