### ISSUE TITLE
Space between lines- How to remove that

### ISSUE THREAD

**Issue by maniasso** [zadam/trilium#712]
Hello, is there a way to reduce the space between lines? When I press enter the space between the current and new line is about one line. (attach file)
If I use shift enter it reduce this space however if I copy the content to other application like a notepad, it doesn't keep the formatting and both lines become one. 
I use trillium over Docker and my host OS is MacOS.

![image (1)](https://user-images.githubusercontent.com/43616714/69103562-7a0dcc80-0a44-11ea-87a0-7de48a893ba0.png)

**Comment by zadam** [comment]
Unfortunately this is not possible. If you really want a line break, you can press `shift-enter` and that will insert a page break instead of new paragraph.

Long story: this comes from the fact that Trilium is built on the web technologies and the HTML is "paragraph oriented" so every time you press enter you are actually creating a paragraph which has extra padding. I remember this was bothering me as well initially and I tried to fix this by changing the paragraph padding in CSS. This kind of works, but produces some other issues (produced HTML does not look the same in the standard rendering with padding, copy paste issues etc). In the end I learned to live with this and even enjoy it more since it seems more semantic. Often times when I wanted to use new lines, these were actually better served by lists than just line break for example (also applicable to you example).

**Comment by nil0x42** [comment]
@maniasso if your issue is purely visual (you would like to see less spacing between lines), you can change the default line-height by creating your own theme.
I personally use a line-height of 1.3, the default is too much for me.

```css
body.theme-my-theme {
    line-height: 1.3; /* less spacing between lines (default=1.5) */
```
https://github.com/zadam/trilium/wiki/Themes

**Comment by maniasso** [comment]
@nil0x42 yes, it's only visual, I don't like to see all these spaces in the lines ... I tried to do what you said, but I'm not a programmer, so I have some difficult to insert the code, I followed the instructions to use note as CSS and do the attribute thing... I think my doubt is more about the code, are you able to say if the code I'm using is correct? I copied from the link you pasted and add the line you mentioned.

 @font-face {
  font-family: 'Raleway';
  font-style: normal;
  font-weight: 400;
  src: url('/custom/fonts/raleway.woff2') format('woff2');
}

body.theme-my-theme {
    --line-height: 1.3;
    --main-font-family: 'Raleway' !important;
    --main-font-size: normal;
    --tree-font-family: inherit;
    --tree-font-size: normal;
    --detail-font-family: inherit;
    --detail-font-size: normal;
    --detail-text-font-family: 'Garamond' !important;

    --main-background-color: #404552;
    --main-text-color: #AFB8C6;
    --main-border-color: #AFB8C6;
    --accented-background-color: #383C4A;
    --more-accented-background-color: #2F343F;
    --header-background-color: #383C4A;
    --button-background-color: #2F343F;
    --button-disabled-background-color: #404552;
    --button-border-color: #333;
    --button-text-color: #AFB8C6;
    --button-border-radius: 2px;
    --muted-text-color: #86919F;
    --input-text-color: #AFB8C6;
    --input-background-color: #404552;
    --modal-background-color: #404552;
    --hover-item-text-color: white;
    --hover-item-background-color: #4877B1;
    --active-item-text-color: white;
    --active-item-background-color: #4877B1;
    --menu-text-color: #AFB8C6;
    --menu-background-color: #383C4A;
    --tooltip-background-color: #383C4A;
    --link-color: lightskyblue;
}

body.theme-my-theme .note-detail-text {
    font-size: 120%;
    line-height: 1.3;
}

**Comment by akhiljalagam** [comment]
A simple approach to fix line spaces and fancy tree height by using extension
1. install custom css extention -> https://chrome.google.com/webstore/detail/custom-css-by-denis/cemphncflepgmgfhcdegkbkekifodacd/related
2. add the following content and adjust the css.
```css
p {
  line-height: 15px;  
}

body .fancytree-node {
    display: flex;
    align-items: center;
    height: 25px;
    padding: 2px;
    border: 1px solid transparent;
    border-radius: 5px;
    cursor: pointer;
    overflow: hidden;
    white-space: nowrap;
    text-overflow: ellipsis;
}
```
