### ISSUE TITLE
How to move past a table inside a Note?

### ISSUE THREAD

**Issue by AndyCoach** [zadam/trilium#742]
In a new note, I created a table. Now I cannot get past the table to keep writing text under that table. 
Do I need to delete the table, press Enter a bunch of times to create empty lines, and then add the table, to be able to use the space after the table?

**Comment by zadam** [comment]
![image](https://user-images.githubusercontent.com/617641/70076685-9478a600-15ff-11ea-90a0-fd1aa991c3d9.png)

Click on the thingie in the upper left corner and press enter.

**Comment by cbop-dev** [comment]
This feature no longer seems to work (in Android, Linux desktop, or the web), since at least version 0.44.9 (and currently, for version 0.45.2) when there is no content above the table. In such cases, the "thingie" above the table never appears, and thus there is no apparent way to add any content either above or below the table (if the table is all that exists).
