### ISSUE TITLE
Reordering notes pulls other notes along with the moved note

### ISSUE THREAD

**Issue by jbhanks** [zadam/trilium#767]
When I try to set up my notes in a specific order, it often happens that other notes will be pulled along with the one that I am using, instead of just moving the selected one. Is this expected behavior?
See a video of it here:
https://www.youtube.com/watch?v=zEFsaEbtT9Q&feature=youtu.be

**Comment by nil0x42** [comment]
Hi ! From what i think i saw the notes that were pulled along were in italic. Meaning that you previously selected them with shift+click, so they were in the "notes moving clipboard".
In order to empty clipboard before moving a note, you must first click on any note, **and then** drag the note you want to some place.

**Comment by jbhanks** [comment]
Ok that explains it, I was just clicking and dragging it. I had no idea that shift-click added them to the clipboard. You might want that to be more prominent in the documentation, as I doubt most people expect that behavior.
