### ISSUE TITLE
some tips and issues useing it on Windows

### ISSUE THREAD

**Issue by suifengtec** [zadam/trilium#783]
The package named `electron-installer-debian` in the file  package.json only support Linux and macOS,Windows User need to remove it:

```bash

# for Windows user
npm rm electron-installer-debian
npm i electron-installer-windows -D

```

what is TRILIUM_ENV?I do not know it, now I will use `cross-env` instead of it:

```bash

# install cross-env
npm i cross-env -D
# modify `TRILIUM_ENV` to `cross-env NODE_ENV` in the package.json

```

the package.json may missing a package named `sqlite3`, installing it:

```bash
# install sqlite3
npm i sqlite3 -S

```

run now:

```bash
# start server
npm run start-server

```

I found some notification about the db not initialled:

```bash

App HTTP server starting up at port 8080
{
  "appVersion": "0.39.0-beta",
  "dbVersion": 155,
  "syncVersion": 13,
  "buildDate": "2019-12-25T12:18:52+01:00",
  "buildRevision": "4cb511bad0590cc4015266643542a43a27c196a9",
  "dataDirectory": "C:\\Users\\Administrator\\AppData\\Roaming/trilium-data",
  "clipperProtocolVersion": "1.0"
}
DB not initialized, please visit setup page to see instructions on how to initialize Trilium.
```

I found some errors:

```bash

Error: Router not found for request /offline.js?617904
Error: Router not found for request /sw.js

```

the first file ... I do not know where is it.
the second file may belong to the package `dayjs`.

opening Trilium via Chrome:

```bash

chrome 127.0.0.1:8080

```

Now, setup it.

It works for me via Chrome, I do not test pack it via Electron now,maybe later.

**Comment by zadam** [comment]
For the electron-installer-debian issue, it is known, but I don't know how to conditionally include a package dependency on some platform only ...

TRILIUM_ENV contains a prod/dev environment, normally you don't need to care about it. Useful for development only.

sqlite3 is actually defined as a dependency in the package.json ...

`DB not initialized, please visit setup page to see instructions on how to initialize Trilium.` is expected since you need to finish the trilium setup from a browser.

```
Error: Router not found for request /offline.js?617904
Error: Router not found for request /sw.js
```

These 2 errors probably don't originate from Trilium, but some other software on your computer tries to load them from the standard 8080 port.

**Comment by suifengtec** [comment]
this Q&A may help you [npm package.json OS specific dependency
](https://stackoverflow.com/questions/15176082/npm-package-json-os-specific-dependency).

Merry Xmas!

**Comment by zadam** [comment]
Thanks for the tip!
