### ISSUE TITLE
sort newest/oldest

### ISSUE THREAD

**Issue by pcause** [zadam/trilium#824]
you have sort alphabetically can you add sort newest/oldest.  Sometimes I want to have the most recent things in the list first, other times the oldest.

**Comment by msbentley** [comment]
This would be really helpful - even without the list view I was thinking about in #548 - the ability to sort the children of a node according to their creation and modification date would be great. A global setting, or remembering per-node would be fine for my use case.

**Comment by MYX-GitHub** [comment]
I think this feature would be more than helpful - for me, its an absolute must.
I've imported almost 4K notes from Evernote, and sorting alphabetically doesn't do anything for me ... sorting by newest first gives me a chronological history of a folder or tagged notes, with the latest item on top for the most recent information.

Because of this, I had to scrap switching over from Evernote, and will just use Trilium for a subset of notes where date is not important. Otherwise, I would abandon EN in a heartbeat!!!

Thanks!

Mike

**Comment by rosewills** [comment]
I would also very much appreciate this feature (particularly for imported evernote notes). I rarely have a reason to sort alphabetically, but much of the work I do depends on my notes being in chronological order.

**Comment by zadam** [comment]
Sort by "date created" and "date modified" has been added as a one time action (next 0.46 release).   
  
`(@sorted` still sorts only alphabetically)

![](https://user-images.githubusercontent.com/617641/109723968-1ebb0b80-7baf-11eb-8fff-7a8519b759a1.png)
