### ISSUE TITLE
Markdown has code highlighting in the browser but not in the desktop app

### ISSUE THREAD

**Issue by gerroon** [zadam/trilium#828]
Hi

It seems like when I look at the same file in the Win desktop  and Firefox(via login) I see that the browser version has syntax hilight support for markdown (like in Joplin) but the desktop app does not have it.

The browser version is the one I compiled locally on Linux (from the repo).  And the Browser is FF 71 on Linux.

See the image for some sample code page comparison (left is browser, right is win desktop app)

![trilium_b4qqTQmgQ6](https://user-images.githubusercontent.com/8519469/72578342-6a233500-389b-11ea-9ffa-bf9da799904e.png)

**Comment by gerroon** [comment]
Ok I tested this with my own builds against the web version and it seems to me that the electorn based desktop apps cant do code syntax in markdown files unlike the web version.

@zadam

I am wondering if it is possible to enable code hilight in markdown files in the desktop apps. Do you know this is an electron issue or something else?

**Comment by zadam** [comment]
The difference does not seem to be between a desktop and a web.

The problem is explained here: https://discuss.codemirror.net/t/autoload-module-with-gfm-code-fences/1042

Each language highlighting etc. is handled by a language module which is lazy loaded. When rendering markdown, code blocks will be highlighted when the appropriate language mode is already loaded, but if not it won't autoload it itself.

In your case if you first load a python code note, the python mode gets loaded and then the markdown is rendered correctly as well.

**Comment by gerroon** [comment]
Interesting. Now I see how it works, I can only get this to work if I add an empty Python note first, however why  I did not need that with the web app is the curious thing to me.
