### ISSUE TITLE
Free editing issues

### ISSUE THREAD

**Issue by n0umenon** [zadam/trilium#875]
I've just got into Trilium and immediately noticed a problem with the free editing. I have to move around my notes content with the arrows without be able to make any new selection, can't go back or select all with cltr+a, there's no free selection except if that's the first time I make mouse moves over any paragraph in the specific note. Once I've made a selection, the formating tool doesn't go away and I have to switch to different note to disappear.

I've downloaded the latest version for Linux, 0.40.3, and I've run it on KDE Plasma.

Dunno if a log file would do any good for this problem, if you need it - let me know how to get one. 

Thanks!

P.S. Bizarrely enough, I've opened and closed the program a few times before wrote here. But after the above comment, I did a reboot of my system and now everything works pretty fine.

P.S. Okay, it's back after some time of usage. It's really annoying and it gets fix only by restart.

.

**Comment by n0umenon** [comment]
Bizarrely enough, I've opened and closed the program a few times before wrote here. But after the above comment, I did reboot of my system and now everything works pretty fine.

**Comment by zadam** [comment]
Hello, thank you for reporting this issue. Unfortunately this is the first time I hear something like this and I'm not able to reproduce this. From the description it sounds like something in the editing component - CKEditor. I tried to search their issue tracker but did not find something similar.

It would be helpful if you could take a look into the developer console when this problem appears - just press `CTRL-SHIFT-I` and copy the content. Potentially there might be some error which would shed some light on this issue.

One other thing is that sometimes there are some issues with some window managers so it would be interesting to see if this issue is reproducible if you e.g. switch to Gnome or some other WM.
