### ISSUE TITLE
Don't treat images as children

### ISSUE THREAD

**Issue by Karol-G** [zadam/trilium#892]
Hi,

whenever I insert an image into a note it is created as a child node. This makes the tree view menu quite ugly (related to  #546). Furthermore if you view the node as book, every image is getting shown twice, which is extremly annoying.

See example:
![grafik](https://user-images.githubusercontent.com/3471895/75778806-c1e90300-5d58-11ea-97ab-979d7e4351b3.png)

My current workaround is to create a seperate main image node and move all image nodes to this main node. The images are still referenced in the original node and displayed correctly -> Tree view is clear and books are displayed better. However I have to do this manually all the time.

Is it possible to not create images as child nodes?

If this is not so easy for you to do (as you said in #546), is it possible for you to automate my workaround? Like a checkbox in the options menu, that when activated moves all image nodes to a main image node and does so for all future images. Maybe it would even be possible to hide that main image node?

Best
Karol

**Comment by zadam** [comment]
I understand this is annoying in certain situations.

I think with the "book" note type this can be fully solved by an exception - if there is a child note of type image which has an "imageLink" relation to the parent, then it's not displayed (since the relation implies it is being displayed as part of the parent).

For the other issues I propose following mitigation - new relation, e.g. `imageParent`. If you paste an image in the note which has this relation defined, then the image will be created instead in the target of the relation (and of course linked with the original note through `imageLink`). You can mark this relation as inheritable and put it to root note and thus effectively define a global "storage" for images. Or you can define it for a sub-tree - you're writing a book and you want all its images in one place, but also don't want them to mix up with the rest of unrelated images ...

**Comment by Karol-G** [comment]
Thanks. It seems to be fixed in the newest version.
