### ISSUE TITLE
'Tomorrow Note' Shortcut

### ISSUE THREAD

**Issue by bwat47** [zadam/trilium#907]
Trilium has a shortcut to create a 'today note' in the calendar hierarchy (ctrl + alt + p)

for me it would be useful if there was also a shortcut to automatically create a new note under tomorrow's date

**Comment by leoossa** [comment]
You can easily achieve this with Scripting. Base your button on:
https://github.com/zadam/trilium/wiki/Day-notes
https://github.com/zadam/trilium/wiki/Task-manager
(basically what I would do at your place is just copy the 'Day note' Button and change in one place to get tomorrow's date instead of today's)

**Comment by zadam** [comment]
Yes, @leoossa is correct, this should be easily scriptable. Actually even the "Today" button is just a script, not part of the "core" Trilium (although provided in the demo document).

**Comment by bwat47** [comment]
I couldn't javascript my way out of a paper bag, so I haven't had any luck scripting this myself :)

I think this previously entered feature request I just came across would do exactly what I'm looking for though: #50

**Comment by bwat47** [comment]
actually, it looks like #50 is already implemented lol... if I say click on the 28th in the calendar it creates a 28th day note!!! so I'll close this :)

**Comment by zadam** [comment]
Yes, calendar widget can do that, but this widget is present only on day notes. That's why #50 is stil open, that one should be triggerable from anywhere ...
