### ISSUE TITLE
Unable to export notes with non-ASCII titles

### ISSUE THREAD

**Issue by idelem** [zadam/trilium#918]
I use v0.40.6 on windows 10. 

I tried to export a subtree of notes. Those with non-ASCII titles weren't extracted from the `.tar` file. Others were correctly generated and extracted. 

Issue #746 addressed this problem as something to do with PaxHeaders, but I couldn't find a solution for windows. Here are the file archivers I've tested and failed on:

|          | Handles PaxHeader | Can extract | Can view |
|----------|-------------------|-------------|----------|
| PeaZip   | Yes?              | No          | No       |
| Bandizip | No                | No          | No       |
| WinRAR   | Yes?              | No          | No       |
| 7-Zip    | Yes?              | No          | No       |

If anyone finds an archiver that works with PaxHeaders, I would love to know. Otherwise, I wonder if there is a more general way to export these notes that works with those common softwares.

**Comment by zadam** [comment]
I was not aware that the situation on windows with support for Pax headers is so bad.

I use [Double Commander](https://doublecmd.sourceforge.io/) and even though it is not a dedicated archiver tool, it can extract tars with Pax headers without issue. It is available for Linux, Windows and Mac.

Otherwise I think it should be possible to get GNU tar for windows, but that's of course a command line tool.

**Comment by zadam** [comment]
I was not aware that the situation on windows with support for Pax headers is so bad.

I use [Double Commander](https://doublecmd.sourceforge.io/) and even though it is not a dedicated archiver tool, it can extract tars with Pax headers without issue. It is available for Linux, Windows and Mac.

Otherwise I think it should be possible to get GNU tar for windows, but that's of course a command line tool.

**Comment by idelem** [comment]
Thank you, Double Commander does the job. I'll close this issue now and see if GNU tar also works.

**Comment by zadam** [comment]
FYI I implemented ZIP export so from 0.41 there should be fewer problems with unicode.
