### ISSUE TITLE
Multiple Windows

### ISSUE THREAD

**Issue by sambbaron** [zadam/trilium#950]
I am finding a major limitation of Trilium is not being able to work with multiple notes at the same time. I know this is a complicated topic, but at minimum, I would like to be able to open multiple windows/instances. Notion supports this in their Electron app.

**Comment by zadam** [comment]
This is something I have been thinking about for a long time. First step in this direction was addition of tabs.

Then there's the need to have multiple notes open side by side, there are several options:

1. open another instance
2. open just a note (without other widgets) in a separate window
3. open a note in a "split view" mode (e.g. what VSCode does)

You suggest 1) but I'd rather avoid that since that means we'd have to deal with concurrency in various ways (technical in SQLite, logical that e.g. sidebar panels from both windows want to save their state but there's just one setting so they will overwrite each other ...).

Also I don't think it's actually what satisfies the use case the best.

If we want to choose between 2) and 3), I would probably choose 2) since it allows more flexibility - e.g. you can move the note window on a different display which you can't do with split view.

**Comment by sambbaron** [comment]
That's great, thank you for the thoughtful reply. I chose 1 because I thought it would be quick and easy, but I hadn't considered concurrency. If I am working in multiple instances, I would never be sending DB transactions at the same time from both instances, right?

2 is confusing to me. Having two windows, one with widgets and one without, but you bring up a good point about managing multiple displays. 

I like 3. You could do window splits like an IDE or other apps spawn an infinite number of columns that you scroll horizontally through.

**Comment by en3r0** [comment]
Found myself wanting to do this today, would love to see it implemented.

**Comment by zadam** [comment]
This has been implemneted in 0.42, see e.g. tree context menu:

![](https://user-images.githubusercontent.com/617641/82125481-829e5000-97a6-11ea-8817-79ced835a2bf.png)

**Comment by en3r0** [comment]
Sorry @zadam I thought this was talking about opening multiple notes side by side in the same browser window. Let me know if that is not the case and I can open a new ticket.

**Comment by zadam** [comment]
Discussion was about different approaches how to open multiple notes, but the title is "multiple windows" so let's just keep it like that. You can open a separate issue for multiple notes side by side in  window.
