### ISSUE TITLE
Reload DB/App if database file was modified by an external application

### ISSUE THREAD

**Issue by wadbr** [zadam/trilium#995]
This will allow for local file sync (syncing using dropbox/mega etc) with 2 or more instances running. 

Maybe this would work as an Advanced option to check DB before saving/accessing or every X seconds? 

And thank you for the work you do, Trilium is amazing.

**Comment by zadam** [comment]
Syncing DB file using general purpose tools is generally difficult, I described some of the problems in #913

**Comment by wadbr** [comment]
Yes that is the exact problem I ran into when trying this currently, I would leave the instance running on computer A and let it sleep then access it from computer B who is waking up from sleep (so instance B is already working/saving before the sync occurs) and this leads to loss of data from computer A. 

But would this not be fixed if there's a check if the file was modified externally that runs before accessing or modifying the DB? 

Make note "123" on instance A > sync app syncs DB containing "123" > instance B finds out DB was modified externally > instance B reloads itself or the DB > note "123" present in instance A and B. 

I apologize if this is getting out of scope of the current project.

**Comment by zadam** [comment]
I guess it could work in theory, but in practice it's just incredibly fragile - it relies on the fact that on one instance there's absolutely no change to the database so it can be updated from another instance.

But any action in the app can cause a DB change - e.g. clicking on a tab is a DB change to remember it. Looking at a note is a DB change ...

Sometimes the DB is changed without user interaction - e.g. trilium has sort of a trash can which permanently erases deleted notes after a period of time. So you think the DB will sync but it won't since both instances made DB changes and the dropbox won't know what to do ...

**Comment by wadbr** [comment]
> Sometimes the DB is changed without user interaction - e.g. trilium has sort of a trash can which permanently erases deleted notes after a period of time. So you think the DB will sync but it won't since both instances made DB changes and the dropbox won't know what to do ...

Oh yes, that explains the random changes to the .db file I have been seeing while debugging this. 

And that makes total sense why it would be hard/pointless to implement, I guess one way this would work was if the DB system was overhauled or the use of a swap file? that saves changes locally and periodically empties it to the proper DB file

Even typing that out was a chore so I would totally understand this not being a viable option.
